// Familia "absurd": burocracias disparatadas y negocios retro (TASK-048). Todo original, con la cara seria.
import { defineTheme, text, area, num, date, chk, sel, rad, pat } from './build.js'

const specs = [
  {
    id: 'oficina-patos-mensajeros',
    name: 'Oficina Central de Patos Mensajeros|Central Office of Messenger Ducks',
    tag: 'Cuac con sello oficial, entrega garantizada|Quack with an official seal, delivery guaranteed',
    style: [52, 200, 'rounded', 14, 'playful'],
    cur: ['🪙', 'MIG', 0, 'after'],
    nouns: ['envío|envíos|delivery|deliveries', 'remitente|remitentes|sender|senders', 'encomienda|encomiendas|parcel|parcels', 'estanque|estanques|pond|ponds'],
    nav: ['Ventanilla del estanque|Pond counter', 'Mis cartas en vuelo|My letters in flight', 'Despachar un pato|Dispatch a duck', 'Tablero de migraciones|Migration board', 'Gacetilla de plumas|Feather gazette'],
    cats: ['Cartas simples|Plain letters', 'Paquetes pequeños|Small parcels', 'Urgentes de ala|Wing-rush', 'Mensajes secretos|Secret messages'],
    items: [
      ['Carta con pato local|Local-duck letter', 'Entrega en el mismo pueblo antes del almuerzo|Same-town delivery before lunch', 3, 0],
      ['Postal con migas de pan|Postcard with breadcrumbs', 'El pato cobra con migas, no con monedas|The duck is paid in crumbs, not coins', 2, 0],
      ['Carta certificada con anillo|Certified letter with ring', 'El pato lleva un anillo numerado en la pata|The duck wears a numbered ankle ring', 6, 0],
      ['Paquete de hasta 200 g|Parcel up to 200 g', 'Mochila impermeable incluida|Waterproof backpack included', 8, 1],
      ['Entrega de bocadillo caliente|Hot sandwich delivery', 'El pato espera a que lo abras|The duck waits for you to open it', 10, 1],
      ['Semillas por correo|Seeds by post', 'En sobres con pico de ahorro|In envelopes with a thrift beak', 5, 1],
      ['Entrega exprés de tormenta|Storm express delivery', 'Con casco y plumas de repuesto|With helmet and spare feathers', 15, 2],
      ['Mensaje urgente nocturno|Urgent night message', 'Patos de vuelo nocturno con linterna|Night-flying ducks with a lantern', 18, 2],
      ['Aviso al otro lado del lago|Notice across the lake', 'Cruce directo sin escalas|Direct crossing, no stops', 12, 2],
      ['Mensaje cifrado en graznido|Quack-encoded message', 'Solo el pato destinatario lo entiende|Only the receiving duck understands it', 20, 3],
      ['Entrega a un nido secreto|Delivery to a secret nest', 'Sin preguntas ni fotografías|No questions or photographs', 25, 3],
      ['Pato doble espía|Double-agent duck', 'Entrega a ambos bandos con el mismo sobre|Delivers to both sides with the same envelope', 30, 3],
    ],
    fields: [
      text('senderName', 'Nombre del remitente|Sender name', { minLength: 2, maxLength: 60 }),
      pat('duckTag', 'Anilla del pato asignado|Assigned duck ring', '^PTO-\\d{3}-[A-Z]$', 'PTO-, tres dígitos, guion y una letra, ej. PTO-417-Q|PTO-, three digits, a dash and a letter, e.g. PTO-417-Q', false),
      sel('breed', 'Raza de pato preferida|Preferred duck breed', ['Colorado|Mallard', 'Mandarín|Mandarin', 'Criollo|Muscovy', 'Cualquiera|Any']),
      num('parcelGrams', 'Peso de la encomienda en gramos|Parcel weight in grams', 1, 400),
      num('distanceKm', 'Distancia en kilómetros|Distance in kilometers', 1, 90),
      chk('waterproof', 'La carta es sensible al agua|The letter is water-sensitive'),
    ],
    contact: ['Mi pato se perdió|My duck got lost', 'Carta mojada|Soggy letter', 'Quiero ser pato mensajero|I want to be a messenger duck', 'Huelga de patos|Duck strike'],
    faq: [
      ['¿Qué distancia cubren?|How far do they fly?', 'Hasta noventa kilómetros por día, menos si hay viento en contra.|Up to ninety kilometers a day, less with a headwind.'],
      ['¿Cómo vuelan bajo la lluvia?|How do they fly in the rain?', 'A los patos les encanta; el sobre va en una funda impermeable.|Ducks love it; the envelope rides in a waterproof sleeve.'],
      ['¿Qué pasa si el pato no llega?|What if the duck does not arrive?', 'Se abre una búsqueda por los estanques vecinos y se devuelve el envío.|A search of nearby ponds opens and the fee is refunded.'],
      ['¿Qué comen durante el viaje?|What do they eat on the way?', 'Migas, maíz y un poco de lenteja de agua.|Crumbs, corn and some duckweed.'],
      ['¿Pueden enviar objetos frágiles?|Can they carry fragile items?', 'Solo huevos de codorniz, bajo su responsabilidad.|Only quail eggs, at your own risk.'],
    ],
    posts: [
      ['Cómo elegir un pato para tu carta|How to choose a duck for your letter', 'Tres señales de un mensajero confiable.|Three signs of a reliable messenger.', 'Jefe de estanque Ovidio Pluma'],
      ['La ruta del lago al molino|The lake-to-mill route', 'Una crónica con curvas y pantanos.|A chronicle with bends and bogs.', 'Cartera Celia Cuac'],
      ['Récord de velocidad: 42 km/h|Speed record: 42 km/h', 'Habla el pato más rápido del estanque.|The pond\'s fastest duck speaks.', 'Pato Ramón'],
    ],
    wiz: {
      title: 'Despachar un mensaje|Dispatch a message',
      steps: [
        ['Tipo de mensaje|Message type', [rad('messageKind', 'Tipo de mensaje|Message type', ['Carta común|Plain letter', 'Mensaje secreto|Secret message'])]],
        ['Distancia y fecha|Distance and date', [num('flightKm', 'Kilómetros de vuelo|Flight kilometers', 1, 90), date('dispatchDay', 'Día de despacho|Dispatch day', 'noPast')]],
        ['Clave|Cipher', [text('cipherWord', 'Palabra clave del graznido|Quack keyword', { minLength: 3, maxLength: 20 })]],
        ['Entrega|Delivery', [chk('receipt', 'Pedir acuse de recibo con pluma|Request a feather receipt')]],
      ],
      cond: ['messageKind', 'secret-message', ['cipherWord']],
    },
    dash: { cols: ['Servicio|Service', 'Patos despachados|Ducks dispatched', 'Fecha de vuelo|Flight date', 'Migas cobradas|Crumbs collected'], pool: ['Carta con pato local|Local-duck letter', 'Paquete pequeño|Small parcel', 'Entrega de tormenta|Storm delivery', 'Mensaje nocturno|Night message', 'Mensaje cifrado|Encoded message', 'Pato doble espía|Double-agent duck'], n: [2, 60], m: [5, 600] },
  },
  {
    id: 'ministerio-del-tiempo-libre',
    name: 'Ministerio del Tiempo Sobrante|Ministry of Spare Time',
    tag: 'Si te sobran cinco minutos, devolvelos|If you have five spare minutes, return them',
    style: [265, 40, 'serif', 2, 'ornate'],
    cur: ['⧗', 'MIN', 0, 'after'],
    nouns: ['trámite|trámites|procedure|procedures', 'ciudadano|ciudadanos|citizen|citizens', 'expediente|expedientes|file|files', 'minuto|minutos|minute|minutes'],
    nav: ['Sala de espera eterna|Eternal waiting room', 'Mis minutos|My minutes', 'Sellar el tiempo|Stamp the time', 'Reloj central|Central clock', 'Anuario de segundos|Seconds yearbook'],
    cats: ['Minutos y segundos|Minutes and seconds', 'Retrasos y adelantos|Delays and advances', 'Siestas oficiales|Official naps', 'Certificados temporales|Time certificates'],
    items: [
      ['Devolución de cinco minutos|Five-minute return', 'Se acredita en tu cuenta de tiempo|Credited to your time account', 2, 0],
      ['Prórroga de un segundo|One-second extension', 'Para terminar una frase pendiente|To finish a pending sentence', 1, 0],
      ['Canje de un lunes por un martes|Trade a Monday for a Tuesday', 'Solo una vez por trimestre|Once per quarter only', 15, 0],
      ['Registro de retraso justificado|Justified-delay registration', 'Con comprobante de tránsito|With proof of traffic', 4, 1],
      ['Adelanto de reloj, cinco horas|Five-hour clock advance', 'Para quienes madrugan de más|For those who rise too early', 12, 1],
      ['Aplazamiento de una Navidad|Christmas postponement', 'Para quienes no están listos|For those who are not ready', 40, 1],
      ['Siesta oficial de veinte minutos|Official twenty-minute nap', 'Con almohada del Ministerio|With a Ministry pillow', 6, 2],
      ['Pase de bostezo|Yawn pass', 'Permite un bostezo largo en horario laboral|Allows one long yawn during work hours', 3, 2],
      ['Sueño profundo con certificado|Certified deep sleep', 'Con aviso a tu jefe incluido|With notice to your boss included', 20, 2],
      ['Certificado de puntualidad perfecta|Perfect punctuality certificate', 'Una vez en la vida|Once in a lifetime', 25, 3],
      ['Constancia de estar tarde sin culpa|Guilt-free lateness certificate', 'Válida en tres reuniones|Valid for three meetings', 8, 3],
      ['Acta de un buen momento|Record of a good moment', 'Para que no se te olvide|So you never forget it', 5, 3],
    ],
    fields: [
      text('citizenName', 'Nombre del ciudadano|Citizen name', { minLength: 3, maxLength: 70 }),
      pat('timeFile', 'Número de expediente temporal|Time file number', '^T-\\d{2}:\\d{2}-\\d{3}$', 'T-, hora:minutos, guion y tres dígitos, ej. T-14:35-007|T-, hh:mm, a dash and three digits, e.g. T-14:35-007'),
      num('minutesRequested', 'Minutos solicitados|Minutes requested', 1, 1440),
      sel('timeZone', 'Huso horario preferido|Preferred time zone', ['Mañana eterna|Eternal morning', 'Siempre las cinco|Always five o\'clock', 'Domingo a la tarde|Sunday afternoon']),
      date('desiredDay', 'Día deseado para el trámite|Desired date for the procedure', 'noPast'),
      chk('rush', 'Es urgente (puede demorar el doble)|It is urgent (may take twice as long)'),
    ],
    contact: ['Minutos extraviados|Missing minutes', 'Reloj atrasado|Slow clock', 'Reclamo por una espera|Waiting complaint', 'Trabajar en el Ministerio|Work at the Ministry'],
    faq: [
      ['¿Cuánto tarda un trámite?|How long does a procedure take?', 'Exactamente lo que le sobre al funcionario de turno.|Exactly whatever the clerk on duty has to spare.'],
      ['¿Se pueden devolver horas?|Can hours be returned?', 'Sí, aunque nunca sabemos a quién se las damos.|Yes, though we never know whom to give them to.'],
      ['¿Qué pasa si llego tarde?|What if I arrive late?', 'Te reciben igual, pero con un sello que dice "tarde".|You are received anyway, with a stamp that says "late".'],
      ['¿Cómo se cobra?|How are fees paid?', 'En minutos, a razón de cinco por trámite.|In minutes, at five per procedure.'],
      ['¿Puedo hacer el trámite en otro tiempo?|Can I do the procedure in a different time?', 'Por pasado o futuro, solo en horario laboral del año actual.|Past or future, only during working hours of the current year.'],
    ],
    posts: [
      ['Cinco minutos que nadie reclamó|Five minutes nobody claimed', 'La historia de un depósito en el reloj central.|The story of a deposit in the central clock.', 'Director Lucio Segundo'],
      ['El domingo que se repitió|The Sunday that repeated', 'Informe de un trámite fuera de calendario.|Report on an out-of-calendar procedure.', 'Inspectora Marta Hora'],
      ['Cómo hacer fila sin envejecer|Queuing without aging', 'Técnicas de espera respaldadas por la ciencia.|Waiting techniques backed by science.', 'Funcionario Tadeo Reloj'],
    ],
    wiz: {
      title: 'Solicitud de ajuste horario|Schedule adjustment request',
      steps: [
        ['Dirección|Direction', [rad('direction', 'Qué necesitás|What you need', ['Más tiempo|More time', 'Menos tiempo|Less time'])]],
        ['Cantidad y fecha|Amount and date', [num('amountMin', 'Minutos|Minutes', 1, 600), date('applyOn', 'Aplicar el|Apply on', 'noPast')]],
        ['Motivo|Reason', [area('whyMoreTime', 'Justificá por qué necesitás más tiempo|Justify why you need more time', 250)]],
        ['Firma|Signature', [chk('swear', 'Declaro no usar el tiempo para cosas útiles|I declare not to use the time for anything useful')]],
      ],
      cond: ['direction', 'more-time', ['whyMoreTime']],
    },
    dash: { cols: ['Trámite|Procedure', 'Minutos tramitados|Minutes processed', 'Fecha de sello|Stamp date', 'Tasa en minutos|Fee in minutes'], pool: ['Devolución de minutos|Minute return', 'Prórroga de segundos|Second extension', 'Siesta oficial|Official nap', 'Aplazamiento de feriado|Holiday postponement', 'Certificado de puntualidad|Punctuality certificate', 'Constancia de demora|Delay record'], n: [1, 480], m: [1, 90] },
  },
  {
    id: 'sindicato-fantasmas-asustadores',
    name: 'Sindicato Unido de Fantasmas y Aparecidos|United Union of Ghosts and Apparitions',
    tag: 'Asustar sin sueldo es explotación ectoplásmica|Haunting unpaid is ectoplasmic exploitation',
    style: [220, 170, 'serif', 12, 'ornate'],
    cur: ['☠', 'ECT', 0, 'after'],
    nouns: ['servicio|servicios|service|services', 'fantasma|fantasmas|ghost|ghosts', 'trámite|trámites|petition|petitions', 'planta|plantas|floor|floors'],
    nav: ['Atrio sindical|Union atrium', 'Mi turno de aparición|My haunting shift', 'Afiliarme|Join the union', 'Panel del delegado|Delegate panel', 'Boletín de ultratumba|Beyond-the-grave bulletin'],
    cats: ['Apariciones|Hauntings', 'Derechos laborales|Labor rights', 'Capacitación|Training', 'Casas y castillos|Houses and castles'],
    items: [
      ['Aparición nocturna estándar|Standard night haunting', 'Entre medianoche y las tres, con cadenas|Between midnight and three, with chains', 20, 0],
      ['Susurro en pasillo largo|Long-corridor whisper', 'Voz profunda y eco garantizado|Deep voice and guaranteed echo', 12, 0],
      ['Puerta que se cierra sola|Self-closing door', 'Efecto sonoro con bisagra oxidada|Sound effect with a rusty hinge', 8, 0],
      ['Convenio por descanso diurno|Daytime rest agreement', 'Nadie asusta antes de las 18 h|Nobody haunts before 6 pm', 0.5, 1],
      ['Aumento por hora extra de ulular|Overtime hooting raise', 'Dos tercios más por hora extra|Two-thirds more per overtime hour', 1, 1],
      ['Seguro contra exorcismos|Exorcism insurance', 'Indemniza por desalojo forzoso|Compensates for forced eviction', 15, 1],
      ['Curso de aullido básico|Basic howling course', 'Respiración y proyección de voz|Breathing and voice projection', 30, 2],
      ['Taller de transparencia parcial|Partial transparency workshop', 'Aparecer solo de cintura para arriba|Appearing waist-up only', 35, 2],
      ['Clase de atravesar paredes|Wall-walking class', 'Sin raspones y con enseñanza práctica|No scrapes and hands-on teaching', 28, 2],
      ['Contrato para casa antigua|Old-house contract', 'Con cláusula de visitas guiadas|With a guided-tour clause', 90, 3],
      ['Alquiler de castillo en ruinas|Ruined castle rental', 'Torres, mazmorra y niebla propia|Towers, dungeon and own fog', 160, 3],
      ['Permiso para hacer cosas en la bruma|Haunting-in-mist permit', 'Solo en madrugadas de niebla espesa|Dense-fog dawns only', 14, 3],
    ],
    fields: [
      text('ghostName', 'Nombre en vida|Name in life', { minLength: 2, maxLength: 60 }),
      num('yearsDeceased', 'Años desde el fallecimiento|Years since passing', 0, 2000),
      pat('unionCard', 'Carnet sindical|Union card', '^SF-\\d{4}-\\+$', 'SF-, cuatro dígitos, guion y un signo +, ej. SF-0913-+|SF-, four digits, a dash and a plus sign, e.g. SF-0913-+'),
      sel('haunting', 'Especialidad de aparición|Haunting specialty', ['Susurros|Whispers', 'Cadenas|Chains', 'Figura vaporosa|Misty figure', 'Objetos que se mueven|Moving objects']),
      sel('origin', 'Lugar de residencia|Place of residence', ['Castillo|Castle', 'Casa antigua|Old house', 'Cementerio|Cemetery', 'Teatro|Theater']),
      chk('transparent', 'Soy más transparente que opaco|I am more transparent than opaque'),
    ],
    contact: ['Turno excesivo|Excessive shift', 'Mudanza de casa embrujada|Moving a haunted house', 'Exorcismo no consentido|Non-consensual exorcism', 'Quiero ser delegado|I want to be a delegate'],
    faq: [
      ['¿Quién puede afiliarse?|Who is eligible to affiliate?', 'Cualquier fantasma, aparecido o presencia con evidencia reconocida.|Any ghost, apparition or presence with recognized evidence.'],
      ['¿Cuánto cuesta la cuota?|How much are dues?', 'Un susurro por mes, cobrado en cada luna llena.|One whisper a month, collected each full moon.'],
      ['¿El sindicato defiende en exorcismos?|Does the union defend against exorcisms?', 'Sí, con abogados que atraviesan expedientes.|Yes, with lawyers who walk through case files.'],
      ['¿Hay descansos?|Are there breaks?', 'Cuatro semanas anuales de vacaciones en un armario.|Four annual weeks of holiday in a wardrobe.'],
      ['¿Se pueden asustar niños?|May we haunt children?', 'Solo con permiso de los padres y sin pesadillas persistentes.|Only with parental permission and no lingering nightmares.'],
    ],
    posts: [
      ['Cómo asustar con dignidad|How to haunt with dignity', 'Reglas de oro para aparecerse con respeto.|Golden rules for respectful appearances.', 'Delegado Baltasar Niebla'],
      ['Huelga del pasillo largo|The long-corridor strike', 'La historia de una huelga que duró un siglo.|The story of a strike that lasted a century.', 'Delegada Ofelia Sombra'],
      ['Los mejores castillos del mes|Best castles of the month', 'Calificados por temperatura y por eco.|Rated by temperature and echo.', 'Cronista Remigio Frío'],
    ],
    wiz: {
      title: 'Afiliación sindical|Union membership',
      steps: [
        ['Situación|Situation', [rad('status', 'Tu situación|Your status', ['Fantasma libre|Free ghost', 'Fantasma con casa|Ghost with a house'])]],
        ['Antigüedad y alta|Seniority and date', [num('haunted', 'Años de trayectoria|Years of experience', 0, 1500), date('joinDate', 'Fecha de alta|Joining date', 'noPast')]],
        ['Casa|House', [text('houseAddress', 'Dirección de la casa|House address', { minLength: 5, maxLength: 80 })]],
        ['Compromiso|Pledge', [chk('pledgeUnion', 'Prometo no asustar sin ser contratado|I pledge not to haunt unhired', true)]],
      ],
      cond: ['status', 'ghost-with-a-house', ['houseAddress']],
    },
    dash: { cols: ['Servicio|Service', 'Fantasmas inscritos|Registered ghosts', 'Fecha|Date', 'Cuotas cobradas|Dues collected'], pool: ['Aparición nocturna|Night haunting', 'Susurros|Whispers', 'Curso de aullido|Howling course', 'Seguro anti-exorcismo|Anti-exorcism insurance', 'Alquiler de castillo|Castle rental', 'Taller de transparencia|Transparency workshop'], n: [1, 45], m: [1, 500] },
  },
  {
    id: 'agencia-de-nubes-algodon',
    name: 'Agencia Municipal de Nubes Algodón de Azúcar|Cotton Candy Municipal Cloud Agency',
    tag: 'Contratá la nube que mejor le queda a tu fiesta|Hire the cloud that best suits your party',
    style: [205, 340, 'rounded', 16, 'playful'],
    cur: ['☁', 'NUB', 0, 'after'],
    nouns: ['nube|nubes|cloud|clouds', 'cliente|clientes|client|clients', 'contrato|contratos|contract|contracts', 'altitud|altitudes|altitude|altitudes'],
    nav: ['Cielo abierto|Open sky', 'Mis nubes|My clouds', 'Contratar nube|Hire a cloud', 'Panel meteorológico|Weather panel', 'Pronóstico poético|Poetic forecast'],
    cats: ['Nubes de fiesta|Party clouds', 'Nubes de sombra|Shade clouds', 'Nubes de lluvia|Rain clouds', 'Nubes decorativas|Decorative clouds'],
    items: [
      ['Cúmulo blanco clásico|Classic white cumulus', 'Ideal para fotos de cumpleaños|Ideal for birthday photos', 25, 0],
      ['Nube con forma de torta|Cake-shaped cloud', 'Cuatro pisos y cobertura de azúcar|Four tiers and sugar frosting', 40, 0],
      ['Nube rosa de atardecer|Sunset pink cloud', 'Se entrega al caer el sol|Delivered at sundown', 55, 0],
      ['Nube sombrilla|Umbrella cloud', 'Sombra para cuarenta personas|Shade for forty people', 30, 1],
      ['Nube alta de verano|High summer cloud', 'Para refrescar sin tapar el sol|To cool without blocking the sun', 22, 1],
      ['Nube de siesta|Nap cloud', 'Sombra y brisa suave para dormir|Shade and a soft breeze for napping', 18, 1],
      ['Nube regadora para jardín|Garden watering cloud', 'Lluvia ligera durante una hora|Light rain for one hour', 35, 2],
      ['Llovizna para una boda|Wedding drizzle', 'Una lluvia ligera para dar suerte|A light shower for good luck', 90, 2],
      ['Nube tormentosa mini|Mini storm cloud', 'Rayos decorativos, sin truenos fuertes|Decorative lightning, no loud thunder', 60, 2],
      ['Nube con tu nombre|Cloud with your name', 'Escrita con vapor, dura una hora|Written in vapor, lasts one hour', 70, 3],
      ['Nube en forma de animal|Animal-shaped cloud', 'Elegí entre perro, gato y ballena|Choose from dog, cat and whale', 45, 3],
      ['Neblina de misterio|Mystery mist', 'Ambientación para cuentos de terror|Atmosphere for ghost stories', 38, 3],
    ],
    fields: [
      text('clientName', 'Nombre del cliente|Client name', { minLength: 2, maxLength: 60 }),
      sel('weatherNeed', 'Clima buscado|Desired weather', ['Soleado con nubes|Sunny with clouds', 'Fresco y sombreado|Cool and shaded', 'Llovizna ligera|Light drizzle']),
      num('altitudeM', 'Altitud deseada en metros|Desired altitude in meters', 50, 4000),
      pat('permit', 'Permiso de espacio aéreo|Airspace permit', '^NB-\\d{3}-[A-Z]{2}$', 'NB-, tres dígitos, guion y dos letras, ej. NB-207-CU|NB-, three digits, a dash and two letters, e.g. NB-207-CU'),
      num('guests', 'Invitados bajo la nube|Guests under the cloud', 1, 300),
      chk('wind', 'Hay viento fuerte en la zona|There is strong wind in the area'),
    ],
    contact: ['Nube que se fue|A cloud that left', 'Lluvia fuera de horario|Off-schedule rain', 'Forma personalizada|Custom shape', 'Contratar para eventos|Hire for events'],
    faq: [
      ['¿Las nubes son reales?|Are the clouds real?', 'Son de vapor cultivado, pero el efecto sobre tus invitados es verdadero.|They are cultivated vapor, but the effect on your guests is real.'],
      ['¿Cuánto dura una nube?|How long does a cloud last?', 'Entre dos y seis horas, dependiendo del viento.|Two to six hours depending on wind.'],
      ['¿Qué pasa si la nube llueve de más?|What if the cloud rains too much?', 'Hay un botón de cierre y una sombrilla de cortesía.|There is a shutoff button and a courtesy umbrella.'],
      ['¿Hacen nubes con formas?|Do you do shaped clouds?', 'Sí, aunque los gatos salen mejor que los elefantes.|Yes, though cats come out better than elephants.'],
      ['¿Hay una nube de emergencia?|Is there an emergency cloud?', 'En verano, la nube de sombra está disponible las 24 horas.|In summer, the shade cloud is available 24 hours.'],
    ],
    posts: [
      ['Cómo preparar un cielo para una boda|Preparing a sky for a wedding', 'Tres consejos de viento y de vapor.|Three tips on wind and vapor.', 'Nubicultora Perla Cirro'],
      ['Nubes con alma de algodón|Cotton-souled clouds', 'La fórmula del vapor azucarado.|The sugary vapor formula.', 'Nubicultora Perla Cirro'],
      ['La nube más grande del año|The year\'s biggest cloud', 'Una crónica de la fiesta del pueblo.|A chronicle of the village feast.', 'Cronista Ismael Brisa'],
    ],
    wiz: {
      title: 'Diseñá el cielo de tu evento|Design your event\'s sky',
      steps: [
        ['Tipo de evento|Event type', [sel('eventType', 'Tipo de evento|Event type', ['Cumpleaños|Birthday', 'Boda|Wedding', 'Picnic|Picnic'])]],
        ['Fecha y duración|Date and duration', [date('eventSky', 'Día del evento|Event day', 'noPast'), num('skyHours', 'Horas de nube|Cloud hours', 1, 10)]],
        ['Boda|Wedding', [text('weddingNames', 'Nombres de los novios para escribir en la nube|Couple names to write in the cloud', { minLength: 3, maxLength: 40 })]],
        ['Clima|Weather', [chk('drizzle', 'Agregar llovizna de buena suerte|Add a good-luck drizzle')]],
      ],
      cond: ['eventType', 'wedding', ['weddingNames']],
    },
    dash: { cols: ['Nube|Cloud', 'Contratos|Contracts', 'Fecha|Date', 'Facturado|Billed'], pool: ['Cúmulo clásico|Classic cumulus', 'Nube de torta|Cake cloud', 'Nube sombrilla|Umbrella cloud', 'Llovizna de boda|Wedding drizzle', 'Nube con nombre|Named cloud', 'Neblina de misterio|Mystery mist'], n: [1, 22], m: [18, 1600] },
  },
  {
    id: 'registro-siestas-modorra',
    name: 'Registro Nacional de Siestas Modorra|Modorra National Nap Registry',
    tag: 'Dormirse es un derecho, despertarse es opcional|Falling asleep is a right, waking up is optional',
    style: [270, 30, 'rounded', 14, 'playful'],
    cur: ['Zz', 'ZZZ', 0, 'after'],
    nouns: ['siesta|siestas|nap|naps', 'durmiente|durmientes|sleeper|sleepers', 'registro|registros|registration|registrations', 'cama|camas|bed|beds'],
    nav: ['Sala de bostezos|Yawn lobby', 'Mis siestas|My naps', 'Inscribir una siesta|Register a nap', 'Panel de ronquidos|Snore panel', 'Sueños del mes|Dreams of the month'],
    cats: ['Siestas cortas|Short naps', 'Siestas largas|Long naps', 'Equipamiento|Gear', 'Ambientes|Settings'],
    items: [
      ['Siesta relámpago de diez minutos|Ten-minute power nap', 'La más vendida de la oficina|The office bestseller', 2, 0],
      ['Siesta de sobremesa|After-lunch nap', 'Con digestión asistida|With assisted digestion', 4, 0],
      ['Cabeceo discreto en reunión|Discreet meeting nod-off', 'Técnica para no ser descubierto|A technique to avoid detection', 3, 0],
      ['Siesta de domingo|Sunday nap', 'Dos horas de duración con manta|Two hours long with a blanket', 8, 1],
      ['Siesta de lluvia|Rainy-day nap', 'Con sonido de gotas incluido|With raindrop soundtrack included', 7, 1],
      ['Siesta de hibernación breve|Brief hibernation nap', 'Cuatro horas con despertar suave|Four hours with a gentle wake-up', 15, 1],
      ['Almohada de rodilla|Knee pillow', 'Para dormir en el sillón|For sleeping on the sofa', 18, 2],
      ['Antifaz de lavanda|Lavender eye mask', 'Bloquea la luz y el estrés|Blocks light and stress', 9, 2],
      ['Hamaca plegable|Folding hammock', 'Se arma en tres minutos|Sets up in three minutes', 35, 2],
      ['Sala de siestas urbana|Urban nap room', 'Camas individuales con cortina|Single beds with curtain', 12, 3],
      ['Siesta en jardín|Garden nap', 'Reposeras a la sombra de un nogal|Loungers in the shade of a walnut tree', 10, 3],
      ['Siesta en tren|Train nap', 'Vagón silencioso con balanceo|Silent car with gentle rocking', 14, 3],
    ],
    fields: [
      text('sleeperName', 'Nombre del durmiente|Sleeper name', { minLength: 2, maxLength: 60 }),
      num('napMinutes', 'Minutos de siesta|Nap minutes', 5, 360),
      sel('pillow', 'Almohada preferida|Preferred pillow', ['Alta|High', 'Baja|Low', 'Sin almohada|No pillow']),
      pat('registryNo', 'Número de siesta registrada|Registered nap number', '^SZ-\\d{5}$', 'SZ- y cinco dígitos, ej. SZ-00731|SZ- and five digits, e.g. SZ-00731'),
      date('napDay', 'Día de la siesta|Nap day', 'noPast'),
      chk('snore', 'Ronco a veces|I snore at times'),
    ],
    contact: ['Siesta interrumpida|Interrupted nap', 'Insomnio persistente|Persistent insomnia', 'Sala de siestas en mi empresa|Nap room at my company', 'Ronquidos en grupo|Group snoring'],
    faq: [
      ['¿Cuánto debe durar una siesta?|How long should a nap last?', 'De diez a veinte minutos para despertar bien, o dos horas para despertar mal.|Ten to twenty minutes to wake well, or two hours to wake badly.'],
      ['¿Puedo dormir en el trabajo?|May I nap at work?', 'Con permiso, almohada y un cartel de "no molestar".|With permission, a pillow and a "do not disturb" sign.'],
      ['¿Hay siestas en grupo?|Are there group naps?', 'Sí, los viernes, en la sala principal con música suave.|Yes, on Fridays in the main hall with soft music.'],
      ['¿Qué pasa si no logro dormirme?|What if I cannot fall asleep?', 'Te acompañamos con una lectura monótona de cuarenta minutos.|We accompany you with a forty-minute monotone reading.'],
      ['¿Cómo me despiertan?|How do you wake me?', 'Con una taza de té tibio y una canción de cuna invertida.|With a lukewarm tea and a reversed lullaby.'],
    ],
    posts: [
      ['La siesta perfecta, paso a paso|The perfect nap, step by step', 'Temperatura, luz y una postura que no duele.|Temperature, light and a posture that does not hurt.', 'Dra. Morfea Ladrón'],
      ['Sueños más raros del mes|Weirdest dreams of the month', 'Un elefante en el ascensor, entre otros.|An elephant in the elevator, among others.', 'Cronista Lalo Duerme'],
      ['Historia del antifaz|History of the sleep mask', 'De los egipcios a tu cajón.|From Egyptians to your drawer.', 'Archivista Nuria Bostezo'],
    ],
    wiz: {
      title: 'Programá tu siesta|Schedule your nap',
      steps: [
        ['Lugar|Place', [rad('where', 'Dónde vas a dormir|Where you will sleep', ['En casa|At home', 'Fuera de casa|Away from home'])]],
        ['Duración y día|Length and day', [num('lengthMin', 'Duración en minutos|Length in minutes', 5, 240), date('plannedDay', 'Día elegido|Chosen day', 'noPast')]],
        ['Fuera de casa|Away', [text('venue', 'Lugar de la siesta|Nap venue', { minLength: 3, maxLength: 60 })]],
        ['Despertar|Wake-up', [chk('gentle', 'Quiero despertar con canción de cuna invertida|I want a reversed-lullaby wake-up')]],
      ],
      cond: ['where', 'away-from-home', ['venue']],
    },
    dash: { cols: ['Tipo de siesta|Nap type', 'Siestas registradas|Naps registered', 'Fecha|Date', 'Aportes|Contributions'], pool: ['Relámpago|Power nap', 'De sobremesa|After-lunch', 'De domingo|Sunday', 'De lluvia|Rainy-day', 'En jardín|Garden', 'En tren|Train'], n: [2, 200], m: [1, 80] },
  },
  {
    id: 'academia-bostezos-estiramiento',
    name: 'Academia Superior de Bostezos y Estiramientos|Higher Academy of Yawns and Stretches',
    tag: 'Abrí grande, soltá todo|Open wide, let it all go',
    style: [10, 175, 'serif', 10, 'playful'],
    cur: ['◌', 'BZT', 0, 'after'],
    nouns: ['clase|clases|class|classes', 'alumno|alumnos|student|students', 'inscripción|inscripciones|enrollment|enrollments', 'cátedra|cátedras|chair|chairs'],
    nav: ['Aula magna|Great lecture hall', 'Mi cursada|My coursework', 'Matricularme|Enroll', 'Tablero del decano|Dean board', 'Revista de estiramientos|Stretch journal'],
    cats: ['Bostezos|Yawns', 'Estiramientos|Stretches', 'Suspiros y resoplidos|Sighs and huffs', 'Posgrados|Postgraduate'],
    items: [
      ['Bostezo elemental|Elementary yawn', 'Mandíbula, aire y lagrimita|Jaw, air and a tiny tear', 12, 0],
      ['Bostezo contagioso avanzado|Advanced contagious yawn', 'Cómo lograr que toda la sala bostece|How to make the whole room yawn', 25, 0],
      ['Bostezo silencioso|Silent yawn', 'Ideal para reuniones aburridas|Ideal for boring meetings', 18, 0],
      ['Estiramiento de gato|Cat stretch', 'Lomo, patas y mirada de reproche|Back, paws and a look of reproach', 14, 1],
      ['Estiramiento de oficina|Office stretch', 'Cuello, hombros y nostalgia|Neck, shoulders and nostalgia', 10, 1],
      ['Estiramiento matutino|Morning stretch', 'Para empezar el día sin quejarse|To start the day without complaint', 12, 1],
      ['Suspiro dramático|Dramatic sigh', 'Con gesto de manos y mirada perdida|With hand gesture and a distant gaze', 15, 2],
      ['Resoplido de impaciencia|Impatient huff', 'Técnica de fila de supermercado|Supermarket queue technique', 11, 2],
      ['Suspiro de alivio|Sigh of relief', 'Se aprende en la fase de exámenes|Learned during exam season', 9, 2],
      ['Maestría en bostezo comparado|Master\'s in Comparative Yawning', 'Seis ciclos y una tesis sobre leones|Six terms and a thesis on lions', 300, 3],
      ['Doctorado en cansancio crónico|Doctorate in Chronic Tiredness', 'Con tutor y siesta incluida|With a tutor and nap included', 450, 3],
      ['Cátedra libre de pereza|Open chair of laziness', 'Sin horario, sin examen, con almohadones|No schedule, no exams, with cushions', 5, 3],
    ],
    fields: [
      text('studentName', 'Nombre del alumno|Student name', { minLength: 2, maxLength: 60 }),
      num('yawnsPerDay', 'Bostezos por día|Yawns per day', 0, 400),
      pat('studentCode', 'Legajo|Student ID', '^BZ\\d{4}-\\d$', 'BZ, cuatro dígitos, guion y un dígito, ej. BZ0452-8|BZ, four digits, a dash and a digit, e.g. BZ0452-8'),
      sel('yawnType', 'Tipo de bostezo preferido|Preferred yawn type', ['Abierto|Wide-open', 'Silencioso|Silent', 'Con sonido|Audible']),
      date('startDate', 'Fecha de inicio|Start date', 'noPast'),
      chk('coffee', 'No tomo café antes de clase|I do not drink coffee before class', true),
    ],
    contact: ['Falta por bostezo ajeno|Absence due to someone else\'s yawn', 'Examen aplazado|Postponed exam', 'Beca de pereza|Laziness scholarship', 'Convenio con empresas|Company partnership'],
    faq: [
      ['¿Hay que saber bostezar?|Must I already know how to yawn?', 'No, los primeros bostezos son guiados.|No, the first yawns are guided.'],
      ['¿Cuánto dura una clase?|How long is a class?', 'Treinta minutos, con diez de estiramiento al medio.|Thirty minutes, with ten of stretching in the middle.'],
      ['¿Dan certificado?|Do you give a certificate?', 'Sí, firmado por el decano con un bostezo.|Yes, signed by the dean with a yawn.'],
      ['¿Hay exámenes?|Are there exams?', 'Uno oral: debe bostezar el tribunal.|One oral exam: the jury has to yawn.'],
      ['¿Aceptan alumnos que no duermen?|Do you accept students who do not sleep?', 'Especialmente esos, con un tratamiento personalizado.|Especially those, with a personalized treatment.'],
    ],
    posts: [
      ['Por qué bostezamos|Why we yawn', 'Cinco teorías, ninguna confirmada.|Five theories, none confirmed.', 'Decano Anselmo Soñoliento'],
      ['El bostezo más largo del año|The year\'s longest yawn', 'Récord de seis segundos y una ovación.|A six-second record and an ovation.', 'Cronista Basilio Ojeras'],
      ['Estirarse en el colectivo|Stretching on the bus', 'Seis ejercicios sin molestar al vecino.|Six exercises without bothering your neighbor.', 'Profesora Marina Tendón'],
    ],
    wiz: {
      title: 'Elegí tu plan de estudios|Choose your study plan',
      steps: [
        ['Nivel|Level', [rad('track', 'Nivel de estudios|Study level', ['Grado|Undergraduate', 'Posgrado|Postgraduate'])]],
        ['Carga horaria y fecha|Hours and date', [num('weeklyHours', 'Horas semanales|Weekly hours', 1, 30), date('beginTerm', 'Inicio de cursada|Term start', 'noPast')]],
        ['Tesis|Thesis', [text('thesisTopic', 'Tema de tu tesis|Thesis topic', { minLength: 5, maxLength: 100 })]],
        ['Matrícula|Enrollment', [chk('termsLazy', 'Acepto el reglamento de pereza|I accept the laziness code', true)]],
      ],
      cond: ['track', 'postgraduate', ['thesisTopic']],
    },
    dash: { cols: ['Cátedra|Chair', 'Alumnos|Students', 'Fecha de inicio|Start date', 'Matrículas cobradas|Tuition collected'], pool: ['Bostezo elemental|Elementary yawn', 'Estiramiento de gato|Cat stretch', 'Suspiro dramático|Dramatic sigh', 'Maestría en bostezo|Master\'s in yawning', 'Pereza libre|Open laziness', 'Resoplido|Huff'], n: [3, 120], m: [50, 14000] },
  },
  {
    id: 'museo-objetos-que-faltan',
    name: 'Museo de los Objetos Que Faltan|Museum of Things That Are Missing',
    tag: 'Entrada gratuita: no hay nada que ver|Free admission: there is nothing to see',
    style: [200, 12, 'serif', 4, 'clean'],
    cur: ['∅', 'VAC', 0, 'after'],
    nouns: ['pieza|piezas|exhibit|exhibits', 'visitante|visitantes|visitor|visitors', 'visita|visitas|visit|visits', 'sala|salas|hall|halls'],
    nav: ['Vestíbulo vacío|Empty lobby', 'Mi recorrido|My tour', 'Reservar visita|Book a visit', 'Panel de curaduría|Curatorial panel', 'Catálogo de ausencias|Catalog of absences'],
    cats: ['Calcetines desaparecidos|Vanished socks', 'Llaves sin dueño|Keys without owners', 'Paraguas perdidos|Lost umbrellas', 'Cosas inexistentes|Nonexistent things'],
    items: [
      ['El calcetín izquierdo de 1987|The Left Sock of 1987', 'Pieza ausente, con vitrina climatizada|Absent piece with a climate-controlled case', 5, 0],
      ['Colección de pares incompletos|Odd-pair Collection', 'Cuarenta calcetines que buscan pareja|Forty socks seeking a partner', 8, 0],
      ['La media de seda perdida|The Lost Silk Stocking', 'Se dice que anda por el sur|Rumored to roam the south', 7, 0],
      ['Llave del cajón de los cables|Key to the Cable Drawer', 'Nadie recuerda qué abre|Nobody remembers what it opens', 4, 1],
      ['Llavero sin llaves|Keyless Keychain', 'Escultura de un tintineo|A sculpture of a jingle', 3, 1],
      ['La llave maestra que no existe|The Master Key That Does Not Exist', 'Una réplica fiel de la nada|A faithful replica of nothing', 10, 1],
      ['Paraguas olvidado en el tren|Umbrella Left on the Train', 'Con restos de lluvia de 2009|With remnants of 2009 rain', 6, 2],
      ['Sombrilla de playa sin playa|Beach Umbrella Without a Beach', 'Perdida en la tormenta de arena|Lost in the sandstorm', 6, 2],
      ['Paraguas que solo existió en el sueño|Umbrella That Existed Only in a Dream', 'Imposible de tocar, difícil de olvidar|Impossible to touch, hard to forget', 9, 2],
      ['La sala de lo que podría haber sido|The Hall of What Might Have Been', 'Un pasillo con eco suave|A corridor with a soft echo', 12, 3],
      ['El color que nunca existió|The Color That Never Existed', 'Una pared sin pintura, con explicación|A wall without paint, with explanation', 8, 3],
      ['El silencio de la sala 4|Silence of Hall 4', 'Audio guía de cuarenta minutos sin sonido|Forty-minute audio guide with no sound', 5, 3],
    ],
    fields: [
      text('visitorName', 'Nombre del visitante|Visitor name', { minLength: 2, maxLength: 60 }),
      num('missingItems', 'Cantidad de objetos que te faltan|Number of items you are missing', 0, 999),
      sel('lostCategory', 'Categoría de lo perdido|Category of lost things', ['Calcetines|Socks', 'Llaves|Keys', 'Paraguas|Umbrellas', 'Otra cosa|Something else']),
      pat('ticketCode', 'Código de entrada|Ticket code', '^AUS-\\d{4}$', 'AUS- y cuatro dígitos, ej. AUS-0073|AUS- and four digits, e.g. AUS-0073'),
      date('visitDay', 'Día de la visita|Visit day', 'noPast'),
      area('description', 'Describí lo que perdiste|Describe what you lost', 250),
    ],
    contact: ['Quiero donar una ausencia|I want to donate an absence', 'Visita escolar|School visit', 'Reclamo por falta de piezas|Complaint about missing pieces', 'Colaborar como curador|Join as curator'],
    faq: [
      ['¿Qué hay en el museo?|What is in the museum?', 'Todo lo que no encontraste; las vitrinas están intencionalmente vacías.|Everything you could not find; the cases are deliberately empty.'],
      ['¿Se puede tocar algo?|May I touch something?', 'No hay nada, entonces sí, con cuidado.|There is nothing, so yes, carefully.'],
      ['¿Cuánto cuesta la entrada?|How much is admission?', 'Es gratis; los gastos se cubren con los objetos que no devolvemos.|It is free; costs are covered by the things we do not return.'],
      ['¿Reciben donaciones?|Do you take donations?', 'Aceptamos solo objetos que no tenés, con certificado de ausencia.|We accept only objects you do not have, with a certificate of absence.'],
      ['¿Hay audioguía?|Is there an audio guide?', 'Sí, de cuarenta minutos y de absoluto silencio.|Yes, forty minutes of absolute silence.'],
    ],
    posts: [
      ['Por qué los calcetines desaparecen|Why socks disappear', 'Una teoría del lavarropas.|A washing-machine theory.', 'Curadora Eugenia Vacío'],
      ['La llave que abrió una puerta que no estaba|The key that opened a door that was not there', 'Una historia sin final.|A story with no ending.', 'Guía Ciro Nadie'],
      ['Reseña: una sala sin objetos|Review: a hall without objects', 'Cinco estrellas por la acústica.|Five stars for the acoustics.', 'Crítico Anselmo Hueco'],
    ],
    wiz: {
      title: 'Declarar una ausencia|Declare an absence',
      steps: [
        ['Tipo de ausencia|Absence type', [sel('absence', 'Qué perdiste|What you lost', ['Un objeto físico|A physical object', 'Una idea|An idea', 'Una oportunidad|An opportunity'])]],
        ['Fecha y valor|Date and value', [date('lostOn', 'Día de la pérdida|Day of loss', 'noFuture'), num('sentimental', 'Valor sentimental (1 a 10)|Sentimental value (1 to 10)', 1, 10)]],
        ['Objeto|Object', [text('objectName', 'Nombre del objeto|Object name', { minLength: 2, maxLength: 60 })]],
        ['Historia|Story', [area('lostStory', 'Contá cómo se perdió|Tell how it was lost', 300)]],
      ],
      cond: ['absence', 'a-physical-object', ['objectName']],
    },
    dash: { cols: ['Sala|Hall', 'Visitantes|Visitors', 'Fecha de visita|Visit date', 'Donaciones de ausencia|Absence donations'], pool: ['Calcetines|Socks', 'Llaves|Keys', 'Paraguas|Umbrellas', 'Cosas inexistentes|Nonexistent things', 'Sala del silencio|Silence hall', 'Sala de lo posible|Hall of the possible'], n: [3, 120], m: [0, 60] },
  },
  {
    id: 'banco-de-suenos-almohada-mayor',
    name: 'Banco de Sueños Almohada Mayor|Pillow Major Dream Bank',
    tag: 'Depositá tus sueños: te devolvemos un viaje con intereses|Deposit your dreams: we pay back a trip with interest',
    style: [255, 320, 'rounded', 14, 'playful'],
    cur: ['☾', 'SNO', 0, 'after'],
    nouns: ['sueño|sueños|dream|dreams', 'ahorrista|ahorristas|saver|savers', 'depósito|depósitos|deposit|deposits', 'cuenta|cuentas|account|accounts'],
    nav: ['Ventanilla nocturna|Night counter', 'Mi caja de sueños|My dream box', 'Hacer depósito|Make a deposit', 'Libro mayor de sueños|Dream ledger', 'Interpretación del mes|Interpretation of the month'],
    cats: ['Sueños felices|Happy dreams', 'Sueños lúcidos|Lucid dreams', 'Pesadillas con descuento|Discounted nightmares', 'Fantasías diurnas|Daydreams'],
    items: [
      ['Sueño de vuelo libre|Free-flight dream', 'Planeo sobre una ciudad de caramelo|Gliding over a candy city', 6, 0],
      ['Sueño de playa infinita|Endless-beach dream', 'Arena tibia y sin turistas|Warm sand and no tourists', 8, 0],
      ['Sueño de mesa grande|Big-table dream', 'Cena con todos los que quisiste ver|Dinner with everyone you wanted to see', 10, 0],
      ['Sueño lúcido de principiante|Beginner lucid dream', 'Aprendé a notar que soñás|Learn to notice you are dreaming', 14, 1],
      ['Control de escenario|Scene control', 'Cambia el paisaje con un chasquido|Change scenery with a snap', 22, 1],
      ['Conversación con tu yo del futuro|Chat with your future self', 'Tres preguntas y una advertencia|Three questions and a warning', 30, 1],
      ['Pesadilla de examen final|Final-exam nightmare', 'Con descuento del cincuenta por ciento|At fifty percent off', 3, 2],
      ['Pesadilla de caída libre|Freefall nightmare', 'Termina antes del impacto|Ends before impact', 3, 2],
      ['Pesadilla con payasos|Clown nightmare', 'Solo para valientes|For the brave only', 2, 2],
      ['Fantasía de ser astronauta|Astronaut daydream', 'Duración de una pausa de café|Lasts one coffee break', 5, 3],
      ['Fantasía de ganar la lotería|Lottery daydream', 'Con auto, casa y perro|With car, house and dog', 5, 3],
      ['Fantasía de renunciar con estilo|Quit-in-style daydream', 'Discurso incluido|Speech included', 7, 3],
    ],
    fields: [
      text('saverName', 'Nombre del ahorrista|Saver name', { minLength: 2, maxLength: 60 }),
      num('nightsSlept', 'Noches de sueño acumuladas|Accumulated nights of sleep', 1, 30000),
      sel('dreamMood', 'Tipo de sueño predominante|Predominant dream type', ['Felices|Happy', 'Lúcidos|Lucid', 'Extraños|Strange']),
      pat('dreamAccount', 'Número de cuenta onírica|Dream account number', '^SU-\\d{4}-[0-9]{2}$', 'SU-, cuatro dígitos, guion y dos dígitos, ej. SU-5120-08|SU-, four digits, a dash and two digits, e.g. SU-5120-08'),
      date('firstDeposit', 'Fecha del primer depósito|First deposit date', 'noFuture'),
      chk('nightmareInsurance', 'Quiero seguro contra pesadillas|I want nightmare insurance'),
    ],
    contact: ['Sueño perdido|Lost dream', 'Intereses en pesadillas|Interest on nightmares', 'Sueño duplicado|Duplicate dream', 'Préstamo de sueños|Dream loan'],
    faq: [
      ['¿Cómo deposito un sueño?|How do I deposit a dream?', 'Lo contás al despertar en tu cuenta, antes de tomar el primer café.|Tell it in your account on waking, before the first coffee.'],
      ['¿Qué tasa de interés pagan?|What interest rate do you pay?', 'Doce por ciento anual, pagado en sueños más largos.|Twelve percent annual, paid in longer dreams.'],
      ['¿Puedo retirar sueños de otro?|Can I withdraw someone else\'s dreams?', 'Solo con autorización firmada de la persona que los soñó.|Only with signed authorization from the dreamer.'],
      ['¿Qué pasa con las pesadillas?|What about nightmares?', 'Se guardan en una cuenta aparte y se amortizan en siestas felices.|They go in a separate account and are amortized with happy naps.'],
      ['¿Cuántos sueños puedo tener?|How many dreams may I hold?', 'No hay límite, pero el espacio es limitado.|No limit, but space is limited.'],
    ],
    posts: [
      ['Cómo contar un sueño sin que se olvide|Telling a dream before it fades', 'Cinco trucos con papel y lápiz.|Five tricks with pen and paper.', 'Asesora Calíope Brisa'],
      ['Pesadillas: ¿buen negocio?|Nightmares: a good investment?', 'Una mirada a los mercados de oscuridad.|A look at the markets of darkness.', 'Economista Lorenzo Sombra'],
      ['La primera cuenta con un sueño volador|The first account with a flying dream', 'Un ahorrista cuenta su aventura.|A saver tells his adventure.', 'Ahorrista Dalmiro Nube'],
    ],
    wiz: {
      title: 'Abrí tu cuenta onírica|Open your dream account',
      steps: [
        ['Tipo de ahorrista|Saver type', [rad('saverKind', 'Perfil de ahorro|Saving profile', ['Conservador|Conservative', 'Aventurero|Adventurous'])]],
        ['Depósito inicial|Initial deposit', [num('firstDreams', 'Sueños a depositar|Dreams to deposit', 1, 100), date('openDay', 'Fecha de apertura|Opening date', 'noPast')]],
        ['Riesgo|Risk', [chk('acceptNightmares', 'Acepto invertir en pesadillas|I accept investing in nightmares')]],
        ['Cierre|Wrap-up', [area('goalDream', 'El sueño que más querés alcanzar|The dream you most want to reach', 200)]],
      ],
      cond: ['saverKind', 'adventurous', ['acceptNightmares']],
    },
    dash: { cols: ['Tipo de sueño|Dream type', 'Depósitos|Deposits', 'Fecha|Date', 'Intereses pagados|Interest paid'], pool: ['Vuelo libre|Free flight', 'Playa infinita|Endless beach', 'Sueño lúcido|Lucid dream', 'Pesadilla de examen|Exam nightmare', 'Fantasía diurna|Daydream', 'Mesa grande|Big table'], n: [3, 300], m: [1, 220] },
  },
  {
    id: 'departamento-excusas-creibles',
    name: 'Departamento de Excusas Creíbles|Department of Believable Excuses',
    tag: 'Mentir mal es un arte menor; nosotros somos el arte mayor|Lying badly is a minor art; we are the major one',
    style: [18, 220, 'sans', 6, 'clean'],
    cur: ['‽', 'EXC', 2, 'after'],
    nouns: ['excusa|excusas|excuse|excuses', 'cliente|clientes|client|clients', 'pedido|pedidos|order|orders', 'rubro|rubros|category|categories'],
    nav: ['Mesa de entradas|Front desk', 'Mis excusas|My excuses', 'Aprobar excusa|Approve excuse', 'Mesa de verificación|Verification desk', 'Casos de la semana|Cases of the week'],
    cats: ['Trabajo|Work', 'Familia|Family', 'Amistades|Friends', 'Trámites|Paperwork'],
    items: [
      ['Llegué tarde por un cartero perdido|Late because a mailman got lost', 'Con detalles de la calle y del perro|With details about the street and the dog', 4, 0],
      ['No pude conectarme: se cortó un cable|Could not log in: a cable snapped', 'Con foto de un cable de verdad|With a photo of a real cable', 5, 0],
      ['Mi reloj se atrasó una hora|My watch lost an hour', 'Mecanismo antiguo, fecha y garantía|Antique mechanism, date and guarantee', 3, 0],
      ['No fui a la cena: me quedé dormido|Skipped dinner: fell asleep', 'Con almohadón y todo|Complete with cushion', 4, 1],
      ['El gato se comió la invitación|The cat ate the invitation', 'Con testigos peludos|With furry witnesses', 3, 1],
      ['Se me olvidó el cumpleaños por un eclipse|Forgot the birthday due to an eclipse', 'Con mapa del eclipse|With eclipse map', 6, 1],
      ['Perdí el mensaje por una tormenta|Lost the message in a storm', 'Con pronóstico del día|With that day\'s forecast', 4, 2],
      ['Mi móvil estaba sin batería|My phone was out of battery', 'La clásica, con porcentaje exacto|The classic, with exact percentage', 2, 2],
      ['Me confundí de calle|I mixed up the street', 'Con un mapa que miente|With a map that lies', 3, 2],
      ['Se perdió el formulario en el correo|The form was lost in the mail', 'Con número de seguimiento inventado|With an invented tracking number', 5, 3],
      ['Faltó un sello|A stamp was missing', 'Con un sello en tamaño real|With a life-size stamp', 3, 3],
      ['El sistema estaba caído|The system was down', 'Con captura de pantalla creativa|With a creative screenshot', 4, 3],
    ],
    fields: [
      text('clientName', 'Nombre del cliente|Client name', { minLength: 2, maxLength: 60 }),
      sel('situation', 'Situación a justificar|Situation to justify', ['Llegada tarde|Late arrival', 'Plazo vencido|Missed deadline', 'Cita cancelada|Cancelled appointment', 'Olvido de fecha|Forgotten date']),
      num('believability', 'Nivel de credibilidad deseado (%)|Desired believability (%)', 50, 100),
      pat('caseNumber', 'Número de caso|Case number', '^EX-\\d{3}-[A-Z]$', 'EX-, tres dígitos, guion y una letra, ej. EX-482-T|EX-, three digits, a dash and a letter, e.g. EX-482-T', false),
      date('needBy', 'Fecha en que la necesitás|Date you need it', 'noPast'),
      area('context', 'Contexto de la situación|Context of the situation', 250),
    ],
    contact: ['Excusa que no funcionó|Excuse that failed', 'Verificar una coartada|Verify an alibi', 'Cambio de versión|Version change', 'Convenio empresarial|Corporate agreement'],
    faq: [
      ['¿Qué tan creíbles son las excusas?|How believable are the excuses?', 'Entre 60 y 98 por ciento, según presupuesto y complejidad.|Between 60 and 98 percent depending on budget and complexity.'],
      ['¿Qué pasa si me descubren?|What if I get caught?', 'Devolvemos el costo, pero no respondemos por consecuencias personales.|We refund the cost, but accept no responsibility for personal consequences.'],
      ['¿Aceptan casos muy graves?|Do you take serious cases?', 'No, solo asuntos leves y simpáticos.|No, only light and charming matters.'],
      ['¿Hay excusas premium?|Are there premium excuses?', 'Sí, con testigos, fotografías y cartas selladas.|Yes, with witnesses, photographs and sealed letters.'],
      ['¿Quién escribe las excusas?|Who writes them?', 'Un equipo de guionistas con experiencia en comedias de enredos.|A team of screenwriters experienced in comedies of errors.'],
    ],
    posts: [
      ['Anatomía de una excusa perfecta|Anatomy of a perfect excuse', 'Tres ingredientes: detalle, humildad y un testigo.|Three ingredients: detail, humility and a witness.', 'Guionista Esperanza Mentira'],
      ['Las diez excusas más usadas del año|The ten most-used excuses of the year', 'Un ranking con humor y datos.|A ranking with humor and data.', 'Analista Facundo Pretexto'],
      ['Cuando la verdad era mejor|When the truth was better', 'Casos en los que no valía la pena inventar.|Cases where inventing was not worth it.', 'Guionista Esperanza Mentira'],
    ],
    wiz: {
      title: 'Diseñá tu excusa|Design your excuse',
      steps: [
        ['Público|Audience', [rad('audience', 'A quién le vas a mentir|Who you will tell', ['A mi jefe|My boss', 'A mi familia|My family'])]],
        ['Fecha y credibilidad|Date and believability', [date('excuseDay', 'Día del hecho|Day of the event', 'noFuture'), num('level', 'Credibilidad deseada|Desired believability', 50, 100)]],
        ['Jefe|Boss', [text('bossName', 'Nombre de tu jefe|Your boss\'s name', { minLength: 2, maxLength: 60 })]],
        ['Detalles|Details', [area('storyBeats', 'Datos que debería incluir|Details it should include', 250)]],
      ],
      cond: ['audience', 'my-boss', ['bossName']],
    },
    dash: { cols: ['Rubro|Category', 'Excusas emitidas|Excuses issued', 'Fecha|Date', 'Facturado|Billed'], pool: ['Trabajo|Work', 'Familia|Family', 'Amistades|Friends', 'Trámites|Paperwork', 'Plazos|Deadlines', 'Citas|Appointments'], n: [3, 90], m: [5, 700] },
  },
  {
    id: 'correo-gatos-bigote-veloz',
    name: 'Correo Felino Bigote Veloz|Swift Whisker Feline Mail',
    tag: 'Entregamos cuando el gato quiere, o sea, nunca a horario|We deliver when the cat wants, which is never on time',
    style: [28, 190, 'rounded', 12, 'playful'],
    cur: ['🐟', 'ATN', 0, 'after'],
    nouns: ['envío|envíos|delivery|deliveries', 'remitente|remitentes|sender|senders', 'encargo|encargos|order|orders', 'ruta|rutas|route|routes'],
    nav: ['Ventanal soleado|Sunny window', 'Mis cartas en camino|My letters on the way', 'Despachar a un gato|Dispatch a cat', 'Tablero de siestas|Nap board', 'Diario de bigotes|Whisker diary'],
    cats: ['Cartas livianas|Light letters', 'Paquetes sin romper|Unbroken parcels', 'Entregas nocturnas|Night deliveries', 'Servicios especiales|Special services'],
    items: [
      ['Carta con gato callejero|Alley-cat letter', 'Entrega en dos tejados y una escalera|Delivery over two roofs and a ladder', 4, 0],
      ['Postal con gato naranja|Orange-cat postcard', 'Se detiene a oler cada maceta|Stops to sniff every flowerpot', 3, 0],
      ['Carta lacrada con gato negro|Sealed letter with black cat', 'Solo viaja de noche|Travels only at night', 6, 0],
      ['Paquete de cajón de cartón|Cardboard-box parcel', 'Se entrega dentro de la caja|Delivered inside the box', 9, 1],
      ['Pequeño regalo en canasta|Small gift in a basket', 'El gato duerme encima antes de entregar|The cat sleeps on top before delivering', 11, 1],
      ['Paquete de hasta 1 kg|Parcel up to 1 kg', 'El gato más fuerte del barrio|The strongest cat in the neighborhood', 14, 1],
      ['Entrega a las tres de la mañana|Three a.m. delivery', 'Cuando los gatos están más activos|When cats are most active', 8, 2],
      ['Mensaje a una ventana abierta|Message to an open window', 'Solo con ventana abierta|Open windows only', 7, 2],
      ['Entrega por el techo|Roof delivery', 'Con garra de agarre|With a gripping claw', 10, 2],
      ['Mensaje con ronroneo|Purring message', 'Un mensaje con vibración cálida|A message with warm vibration', 12, 3],
      ['Entrega con cascabel|Bell-delivery', 'El cascabel avisa la llegada|The bell announces arrival', 6, 3],
      ['Seguro contra mimos|Cuddle insurance', 'Si el gato se queda con el cariño|If the cat keeps the cuddles', 5, 3],
    ],
    fields: [
      text('senderName', 'Nombre del remitente|Sender name', { minLength: 2, maxLength: 60 }),
      sel('catColor', 'Color de gato solicitado|Requested cat color', ['Naranja|Orange', 'Negro|Black', 'Gris|Gray', 'El que esté despierto|Whichever is awake']),
      pat('catId', 'Código del gato mensajero|Courier cat code', '^MIAU-\\d{3}$', 'MIAU- y tres dígitos, ej. MIAU-207|MIAU- and three digits, e.g. MIAU-207', false),
      num('distanceBlocks', 'Distancia en cuadras|Distance in blocks', 1, 60),
      num('parcelGrams', 'Peso de la carga en gramos|Payload in grams', 1, 1000),
      chk('windowOpen', 'La ventana de destino estará abierta|The destination window will be open', true),
    ],
    contact: ['Mi gato mensajero se durmió|My courier cat fell asleep', 'Entrega equivocada|Wrong delivery', 'Quiero que mi gato trabaje|I want my cat to work', 'Pedido de mimos|Cuddle request'],
    faq: [
      ['¿Cuándo llegan las cartas?|When do the letters arrive?', 'Entre una hora y un semestre, según el humor del gato.|Between an hour and a semester depending on the cat\'s mood.'],
      ['¿Qué pasa si el gato se pierde?|What if the cat gets lost?', 'Se abre una búsqueda con atún y llamados suaves.|A search opens with tuna and soft calls.'],
      ['¿Puedo elegir al gato?|Can I choose the cat?', 'Podés pedir color, pero la decisión final es del gato.|You can request a color, but the final decision is the cat\'s.'],
      ['¿Hay seguro?|Is there insurance?', 'Cubre mimos pérdidos y pelo en la carta.|It covers lost cuddles and fur on the letter.'],
      ['¿Hacen entregas internacionales?|Do you deliver internationally?', 'Solo hasta la esquina; luego depende del vecino.|Only to the corner; after that it depends on the neighbor.'],
    ],
    posts: [
      ['Cómo motivar a un gato mensajero|How to motivate a courier cat', 'Premios, siestas y respeto.|Treats, naps and respect.', 'Jefa de bigotes Mimi Ronron'],
      ['La carta que tardó tres meses|The letter that took three months', 'Una entrega que nadie esperaba.|A delivery nobody expected.', 'Cartero Rufo Garra'],
      ['Los cinco tejados más seguros|The five safest rooftops', 'Un mapa de atajos felinos.|A map of feline shortcuts.', 'Cartógrafa Lía Cola'],
    ],
    wiz: {
      title: 'Despachar una carta con un gato|Dispatch a letter by cat',
      steps: [
        ['Carga|Cargo', [sel('cargoKind', 'Qué enviás|What you send', ['Una carta|A letter', 'Un paquete pequeño|A small parcel'])]],
        ['Distancia y fecha|Distance and date', [num('wizBlocks', 'Cuadras de distancia|Blocks of distance', 1, 60), date('sendOn', 'Envío deseado|Desired send date', 'noPast')]],
        ['Paquete|Parcel', [num('parcelWeight', 'Peso del paquete en gramos|Parcel weight in grams', 1, 1000)]],
        ['Gatos|Cats', [chk('twoCats', 'Quiero dos gatos por si uno se distrae|I want two cats in case one gets distracted')]],
      ],
      cond: ['cargoKind', 'a-small-parcel', ['parcelWeight']],
    },
    dash: { cols: ['Servicio|Service', 'Gatos despachados|Cats dispatched', 'Fecha de salida|Departure date', 'Atunes cobrados|Tuna collected'], pool: ['Carta callejera|Alley letter', 'Paquete en canasta|Basket parcel', 'Entrega nocturna|Night delivery', 'Mensaje con ronroneo|Purring message', 'Entrega por el techo|Roof delivery', 'Seguro contra mimos|Cuddle insurance'], n: [1, 40], m: [2, 220] },
  },
  {
    id: 'escuela-payasos-serios',
    name: 'Escuela de Payasos Serios|School for Serious Clowns',
    tag: 'Reír es un asunto grave|Laughter is a serious matter',
    style: [350, 55, 'serif', 4, 'ornate'],
    cur: ['🎈', 'RSA', 0, 'after'],
    nouns: ['curso|cursos|course|courses', 'aprendiz|aprendices|apprentice|apprentices', 'inscripción|inscripciones|enrollment|enrollments', 'carpa|carpas|tent|tents'],
    nav: ['Gran carpa|Big top', 'Mis ensayos|My rehearsals', 'Firmar contrato|Sign the contract', 'Dirección del circo|Circus management', 'Programa de la función|Show program'],
    cats: ['Humor sobrio|Sober humor', 'Pantomima formal|Formal pantomime', 'Globos y trucos|Balloons and tricks', 'Vestuario|Costumes'],
    items: [
      ['Tropezar con elegancia|Tripping with Elegance', 'La caída que parece accidental|The fall that seems accidental', 90, 0],
      ['Chiste de diez minutos, sin sonreír|Ten-Minute Joke Without Smiling', 'Para gente muy seria|For very serious people', 120, 0],
      ['Risas corteses de oficina|Polite Office Laughter', 'Cuándo reír sin que moleste|When to laugh without annoying anyone', 70, 0],
      ['Mimo de ascensor|Elevator Mime', 'Atrapado sin salir, sin hablar|Trapped without leaving, without speaking', 110, 1],
      ['Caminata contra el viento|Walking Against the Wind', 'El viento solo existe en tu cara|The wind exists only on your face', 95, 1],
      ['La caja invisible, nivel experto|The Invisible Box, Expert Level', 'Seis paredes y una puerta secreta|Six walls and a secret door', 130, 1],
      ['Globoflexia con voltaje|High-Voltage Balloon Twisting', 'Perros de globo, jirafas y reptiles|Balloon dogs, giraffes and reptiles', 100, 2],
      ['Malabares con tres platos y un dilema|Juggling Three Plates and a Dilemma', 'Un clásico con crisis filosófica|A classic with a philosophical crisis', 140, 2],
      ['Pastel en la cara: el arte|The Art of the Pie in the Face', 'Con trayectoria, velocidad y piedad|With trajectory, speed and mercy', 85, 2],
      ['Zapatos largos a medida|Custom Long Shoes', 'Cuero, suela de goma y mucha ambición|Leather, rubber sole and much ambition', 60, 3],
      ['Peluca arcoíris reglamentaria|Regulation Rainbow Wig', 'Aprobada por la comisión de payasos|Approved by the clown commission', 40, 3],
      ['Nariz de goma certificada|Certified Rubber Nose', 'Ajuste perfecto y una pizca de dignidad|Perfect fit and a hint of dignity', 15, 3],
    ],
    fields: [
      text('apprenticeName', 'Nombre de aprendiz|Apprentice name', { minLength: 2, maxLength: 60 }),
      text('clownName', 'Nombre artístico de payaso|Clown stage name', { minLength: 2, maxLength: 40 }),
      pat('noseSize', 'Número de nariz|Nose number', '^N-\\d{2}-[SML]$', 'N-, dos dígitos, guion y S, M o L, ej. N-07-M|N-, two digits, a dash and S, M or L, e.g. N-07-M'),
      sel('specialty', 'Especialidad|Specialty', ['Mimo|Mime', 'Malabarismo|Juggling', 'Globoflexia|Balloon twisting', 'Humor verbal|Verbal humor']),
      num('smileCount', 'Sonrisas al día (máximo permitido)|Smiles per day (maximum allowed)', 0, 50),
      chk('serious', 'Me comprometo a mantener la seriedad|I commit to remaining serious', true),
    ],
    contact: ['Reclamo por una risa descontrolada|Complaint about uncontrolled laughter', 'Audición|Audition', 'Alquiler de vestuario|Costume rental', 'Contratar un payaso serio|Hire a serious clown'],
    faq: [
      ['¿Hay que ser gracioso?|Do I need to be funny?', 'No, hay que ser serio; la gracia aparece sola.|No, you must be serious; the humor appears by itself.'],
      ['¿Cuánto dura la carrera?|How long is the program?', 'Tres años, con una función final y un examen de caída.|Three years, with a final show and a falling exam.'],
      ['¿Aceptan menores?|Do you accept minors?', 'Desde los diez años con permiso de un adulto serio.|From ten years with permission from a serious adult.'],
      ['¿Qué ropa llevo?|What should I wear?', 'Ropa cómoda y zapatos cerrados; el vestuario lo damos nosotros.|Comfortable clothes and closed shoes; we supply costumes.'],
      ['¿Dan trabajo al egresar?|Do you place graduates?', 'La bolsa de trabajo cuenta con tres circos aliados.|The job board works with three allied circuses.'],
    ],
    posts: [
      ['La caída perfecta, paso a paso|The perfect fall, step by step', 'Cinco consejos para no lastimarte.|Five tips for not hurting yourself.', 'Maestro Fulgencio Risa'],
      ['La nariz roja a través del tiempo|The red nose through time', 'Una historia de ciento veinte años.|A hundred-and-twenty-year history.', 'Archivista Carlota Trompa'],
      ['Entrevista a un payaso serio|Interview with a serious clown', 'Qué piensa de los chistes de pastel.|What he thinks of pie jokes.', 'Cronista Bruno Carcajada'],
    ],
    wiz: {
      title: 'Audición de ingreso|Entrance audition',
      steps: [
        ['Nivel|Level', [rad('experience', 'Experiencia artística|Performing experience', ['Sin experiencia|No experience', 'Con experiencia|Some experience'])]],
        ['Fecha y carga|Date and load', [date('auditionDay', 'Día de la audición|Audition day', 'noPast'), num('weeklyRehearsal', 'Horas de ensayo semanales|Weekly rehearsal hours', 1, 40)]],
        ['Antecedentes|Background', [text('troupe', 'Compañía o circo anterior|Previous troupe or circus', { minLength: 3, maxLength: 60 })]],
        ['Número|Act', [area('actIdea', 'Describí tu número en una frase|Describe your act in one sentence', 200)]],
      ],
      cond: ['experience', 'some-experience', ['troupe']],
    },
    dash: { cols: ['Curso|Course', 'Aprendices|Apprentices', 'Fecha de inicio|Start date', 'Matrículas|Tuition'], pool: ['Tropezar con elegancia|Tripping with elegance', 'Mimo de ascensor|Elevator mime', 'Globoflexia|Balloon twisting', 'Malabares|Juggling', 'Pastel en la cara|Pie in the face', 'Zapatos largos|Long shoes'], n: [2, 40], m: [60, 5200] },
  },
  {
    id: 'bolsa-de-chistes-malos',
    name: 'Bolsa de Valores de Chistes Malos|Bad Jokes Stock Exchange',
    tag: 'Cotizan a la baja pero rinden carcajadas|They trade low but yield guffaws',
    style: [45, 215, 'mono', 4, 'tech'],
    cur: ['Ha', 'JKR', 2, 'after'],
    nouns: ['chiste|chistes|joke|jokes', 'inversor|inversores|investor|investors', 'orden|órdenes|order|orders', 'mercado|mercados|market|markets'],
    nav: ['Piso de operaciones|Trading floor', 'Mi portafolio|My portfolio', 'Comprar acciones|Buy shares', 'Tablero de cotización|Ticker board', 'Boletín bursátil|Market bulletin'],
    cats: ['Chistes de papá|Dad jokes', 'Juegos de palabras|Puns', 'Humor absurdo|Absurd humor', 'Chistes de oficina|Office jokes'],
    items: [
      ['Chiste del pez en la heladera|Fish-in-the-Fridge Joke', 'Cotiza estable desde 1998|Stable since 1998', 3, 0],
      ['Acción de pun matinal|Morning Pun Share', 'Rinde más antes del café|Pays best before coffee', 4, 0],
      ['Papá y el semáforo|Dad and the Traffic Light', 'Un clásico de las vacaciones|A holiday classic', 2, 0],
      ['Doble sentido de nivel básico|Basic Double Entendre', 'Bonos con aviso previo|Bonds with prior notice', 5, 1],
      ['Metáfora de cebolla|Onion Metaphor', 'Hace llorar de risa, y de cebolla|Brings tears of laughter, and onion', 6, 1],
      ['Rima forzada|Forced Rhyme', 'Cobertura contra la inflación poética|Hedge against poetic inflation', 4, 1],
      ['Chiste sin remate|Joke Without a Punchline', 'Muy volátil, muy arriesgado|Very volatile, very risky', 7, 2],
      ['Absurdo con pingüino|Penguin Absurdity', 'Siempre sube con el calor|Always rises with the heat', 8, 2],
      ['Pregunta sin respuesta|Question Without an Answer', 'Cierra siempre en silencio|Always closes in silence', 5, 2],
      ['Chiste de reunión de las nueve|Nine A.M. Meeting Joke', 'Se vende rápido los lunes|Sells quickly on Mondays', 6, 3],
      ['Broma de impresora|Printer Joke', 'Siempre falla en el momento oportuno|Always fails at the right moment', 5, 3],
      ['Correo con todos en copia|Reply-All Joke', 'De alto riesgo y gran rendimiento|High risk, high yield', 9, 3],
    ],
    fields: [
      text('investorName', 'Nombre del inversor|Investor name', { minLength: 2, maxLength: 60 }),
      pat('tickerCode', 'Símbolo bursátil|Ticker symbol', '^[A-Z]{3,4}\\.HA$', 'Entre tres y cuatro letras y .HA, ej. PUN.HA|Three to four letters and .HA, e.g. PUN.HA'),
      sel('strategy', 'Estrategia|Strategy', ['Conservadora|Conservative', 'Riesgosa|Risky', 'Solo por diversión|Just for fun']),
      num('shares', 'Cantidad de acciones|Number of shares', 1, 100000),
      num('laughThreshold', 'Umbral de risa para vender (%)|Laugh threshold to sell (%)', 1, 100),
      chk('dividends', 'Reinvertir dividendos en risas|Reinvest dividends in laughs'),
    ],
    contact: ['Cotización injusta|Unfair quote', 'Acciones sin remate|Punchline-free shares', 'Quiero cotizar un chiste|I want to list a joke', 'Auditoría de risa|Laughter audit'],
    faq: [
      ['¿Cómo se valúa un chiste?|How is a joke valued?', 'Por el eco de la carcajada y el silencio posterior.|By the echo of the guffaw and the silence after.'],
      ['¿Hay riesgo de pérdida?|Is there risk of loss?', 'Sí, sobre todo si el chiste ya se contó.|Yes, especially if the joke has been told.'],
      ['¿Puedo vender mi chiste?|Can I sell my joke?', 'Solo si pasa la prueba de tres personas distraídas.|Only if it passes the test of three distracted people.'],
      ['¿Qué es un dividendo?|What is a dividend?', 'Una risa extra por cada acción retenida.|An extra laugh per share held.'],
      ['¿Hay regulador?|Is there a regulator?', 'Una comisión de abuelos con mucho tiempo libre.|A commission of grandparents with plenty of spare time.'],
    ],
    posts: [
      ['La caída del chiste del año|The fall of the year\'s joke', 'Un análisis técnico de una carcajada fallida.|A technical analysis of a failed guffaw.', 'Analista Gonzalo Remate'],
      ['Por qué los juegos de palabras son seguros|Why puns are safe', 'Un bono de rendimiento garantizado.|A guaranteed-yield bond.', 'Analista Gonzalo Remate'],
      ['Entrevista a un inversor en risas|Interview with a laughter investor', 'Cinco consejos para no perder la sonrisa.|Five tips for keeping the smile.', 'Cronista Elvira Mueca'],
    ],
    wiz: {
      title: 'Abrí tu cuenta bursátil|Open your trading account',
      steps: [
        ['Perfil|Profile', [rad('profile', 'Perfil de inversor|Investor profile', ['Principiante|Beginner', 'Veterano|Veteran'])]],
        ['Capital y fecha|Capital and date', [num('capital', 'Capital inicial en risas|Starting capital in laughs', 10, 100000), date('firstTrade', 'Primera operación|First trade', 'noPast')]],
        ['Veterano|Veteran', [text('lastBroker', 'Corredor anterior|Previous broker', { minLength: 3, maxLength: 60 })]],
        ['Riesgo|Risk', [chk('accept', 'Entiendo que los chistes pueden ser malos|I understand jokes may be bad', true)]],
      ],
      cond: ['profile', 'veteran', ['lastBroker']],
    },
    dash: { cols: ['Título|Listing', 'Acciones operadas|Shares traded', 'Fecha de cierre|Close date', 'Volumen en risas|Volume in laughs'], pool: ['Pez en la heladera|Fish in the fridge', 'Pun matinal|Morning pun', 'Absurdo con pingüino|Penguin absurdity', 'Rima forzada|Forced rhyme', 'Broma de impresora|Printer joke', 'Todos en copia|Reply-all'], n: [10, 9000], m: [5, 4000] },
  },
  {
    id: 'gremio-calcetines-solitarios',
    name: 'Gremio de Calcetines Solitarios y Afines|Guild of Lone Socks and Associates',
    tag: 'Siempre falta uno; nosotros lo encontramos|One is always missing; we find it',
    style: [350, 120, 'rounded', 14, 'playful'],
    cur: ['⇋', 'PAR', 0, 'after'],
    nouns: ['búsqueda|búsquedas|search|searches', 'dueño|dueños|owner|owners', 'denuncia|denuncias|report|reports', 'cajón|cajones|drawer|drawers'],
    nav: ['Cajón central|Central drawer', 'Mis solitarios|My lone ones', 'Registrar pérdida|Register a loss', 'Libro de cajones|Drawer ledger', 'Crónicas del tendedero|Clothesline chronicles'],
    cats: ['Pérdidas recientes|Recent losses', 'Pérdidas antiguas|Old losses', 'Emparejamientos|Matchmaking', 'Prevención|Prevention'],
    items: [
      ['Búsqueda en el lavarropas|Washing-machine search', 'Revisión de ropa y filtros|Garment and filter inspection', 6, 0],
      ['Rastreo en el tendedero|Clothesline trace', 'Con mirada atenta y pinzas|With a keen eye and clothespins', 5, 0],
      ['Barrido debajo de la cama|Under-the-bed sweep', 'Cuatro especialistas y una linterna|Four specialists and a flashlight', 8, 0],
      ['Caso frío: el calcetín de 2011|Cold Case: The 2011 Sock', 'Con informe de escenas|With scene report', 25, 1],
      ['Búsqueda en el cajón del abuelo|Grandfather\'s drawer search', 'Con paciencia arqueológica|With archaeological patience', 18, 1],
      ['Excavación en mudanza|Moving-day excavation', 'Cajas, bolsas y un par de sorpresas|Boxes, bags and a couple of surprises', 30, 1],
      ['Búsqueda de pareja por color|Color-based pairing', 'Entre cuarenta candidatos|Among forty candidates', 10, 2],
      ['Emparejamiento por estampa|Pattern matchmaking', 'Rayas, lunares y diseños raros|Stripes, polka dots and odd designs', 12, 2],
      ['Pareja de emergencia|Emergency pair', 'Un calcetín nuevo con parecido razonable|A new sock with a reasonable resemblance', 7, 2],
      ['Clip anticalcetín perdido|Anti-loss clip', 'Une cada par en el lavarropas|Joins each pair in the washer', 4, 3],
      ['Bolsa de lavado de malla|Mesh wash bag', 'Para que nadie escape|So nobody escapes', 6, 3],
      ['Curso de doblado y emparejamiento|Folding and Pairing Course', 'Una tarde de práctica y té|An afternoon of practice and tea', 20, 3],
    ],
    fields: [
      text('ownerName', 'Nombre del dueño|Owner name', { minLength: 2, maxLength: 60 }),
      sel('sockSide', 'Pie del calcetín perdido|Side of the lost sock', ['Izquierdo|Left', 'Derecho|Right', 'No sé|Unsure']),
      pat('sockCode', 'Código de calcetín|Sock code', '^CS-[A-Z]{2}-\\d{3}$', 'CS-, dos letras, guion y tres dígitos, ej. CS-RY-094|CS-, two letters, a dash and three digits, e.g. CS-RY-094', false),
      num('sockLength', 'Largo del calcetín en centímetros|Sock length in centimeters', 5, 60),
      date('lostDate', 'Fecha estimada de pérdida|Estimated loss date', 'noFuture'),
      area('pattern', 'Descripción del diseño|Description of the pattern', 150),
    ],
    contact: ['Encontré un calcetín ajeno|I found someone else\'s sock', 'Búsqueda sin resultado|Search with no result', 'Dar de baja un calcetín|Retire a sock', 'Adopción de solitarios|Adopt a lone sock'],
    faq: [
      ['¿Dónde están los calcetines perdidos?|Where do lost socks go?', 'Nuestras investigaciones indican que en el cajón del vecino.|Our research suggests the neighbor\'s drawer.'],
      ['¿Cuánto tarda una búsqueda?|How long does a search take?', 'Tres días para casos recientes y tres meses para los antiguos.|Three days for recent cases and three months for old ones.'],
      ['¿Qué pasa si no aparece?|What if it never turns up?', 'Se ofrece una pareja de emergencia y un acta de sentido pésame.|An emergency pair and a certificate of condolence are offered.'],
      ['¿Aceptan otras prendas?|Do you accept other garments?', 'Solo guantes, y por pedido especial.|Only gloves, by special request.'],
      ['¿Hay voluntarios?|Are there volunteers?', 'Sí, con experiencia comprobada en rincones.|Yes, with proven experience in corners.'],
    ],
    posts: [
      ['Cómo organizar un cajón de calcetines|How to organize a sock drawer', 'Una guía con orden y compasión.|A guide with order and compassion.', 'Archivista Pía Pareja'],
      ['El calcetín que volvió|The sock that came back', 'Una historia de reencuentro en el pasillo.|A reunion story in the hallway.', 'Detective Emilio Hilo'],
      ['Teoría del tendedero cuántico|Quantum clothesline theory', 'Dónde pasa lo que pasa.|Where what happens happens.', 'Dra. Zulema Ovillo'],
    ],
    wiz: {
      title: 'Registrar una pérdida|Register a loss',
      steps: [
        ['Tipo de pérdida|Type of loss', [rad('lossKind', 'Qué perdiste|What you lost', ['Un calcetín|One sock', 'Varios calcetines|Several socks'])]],
        ['Fecha y color|Date and color', [date('whenLost', 'Cuándo lo notaste|When you noticed', 'noFuture'), text('colorHint', 'Color principal|Main color', { minLength: 3, maxLength: 30 })]],
        ['Varios|Several', [num('howMany', 'Cantidad perdida|Number lost', 2, 50)]],
        ['Pistas|Clues', [area('lastSeen', 'Dónde lo viste por última vez|Where you last saw it', 250)]],
      ],
      cond: ['lossKind', 'several-socks', ['howMany']],
    },
    dash: { cols: ['Tipo de búsqueda|Search type', 'Calcetines buscados|Socks searched', 'Fecha|Date', 'Cuotas|Fees'], pool: ['Lavarropas|Washing machine', 'Tendedero|Clothesline', 'Debajo de la cama|Under the bed', 'Caso frío|Cold case', 'Mudanza|Moving day', 'Emparejamiento|Pairing'], n: [1, 60], m: [4, 600] },
  },
  {
    id: 'ministerio-de-las-esquinas',
    name: 'Ministerio de las Esquinas Redondas|Ministry of Rounded Corners',
    tag: 'Porque nadie merece un golpe en la rodilla|Because nobody deserves a knock on the knee',
    style: [190, 350, 'sans', 12, 'clean'],
    cur: ['◜', 'ESQ', 0, 'after'],
    nouns: ['trámite|trámites|procedure|procedures', 'ciudadano|ciudadanos|citizen|citizens', 'solicitud|solicitudes|request|requests', 'esquina|esquinas|corner|corners'],
    nav: ['Ventanilla redondeada|Rounded counter', 'Mis esquinas|My corners', 'Solicitar redondeo|Request rounding', 'Panel de ángulos|Angle panel', 'Boletín de geometría|Geometry bulletin'],
    cats: ['Mobiliario|Furniture', 'Calles y vereda|Streets and sidewalks', 'Edificios públicos|Public buildings', 'Objetos personales|Personal items'],
    items: [
      ['Redondeo de mesa de comedor|Dining-table rounding', 'Radio de 5 cm, lijado y barniz|5 cm radius, sanded and varnished', 40, 0],
      ['Esquineros de silicona|Silicone corner guards', 'Seis por juego, adhesivo fuerte|Six per set, strong adhesive', 8, 0],
      ['Redondeo de escritorio|Desk rounding', 'Preferido por oficinistas distraídos|Favored by absent-minded office workers', 35, 0],
      ['Esquina de vereda suavizada|Softened sidewalk corner', 'Con rampa y sin escalones|With ramp and no steps', 300, 1],
      ['Semáforo con ángulos redondos|Round-angled traffic light', 'Piloto en curva y farola protegida|Curved pilot and protected lamp', 500, 1],
      ['Bolardos esféricos|Spherical bollards', 'Para que nadie se golpee al pasar|So nobody bumps in passing', 120, 1],
      ['Escalera con curvas|Curved staircase', 'Cada escalón con borde redondeado|Each step with a rounded edge', 600, 2],
      ['Marco de puerta amable|Gentle door frame', 'Con esquinas de goma|With rubber corners', 90, 2],
      ['Mostrador de municipalidad|Town-hall counter', 'Un mostrador sin esquinas filosas|A counter with no sharp corners', 150, 2],
      ['Billetera sin ángulos|Angle-free wallet', 'Cuero suave y sin puntas|Soft leather with no points', 25, 3],
      ['Celular con marco ovalado|Oval-framed phone case', 'No pincha el bolsillo|Does not poke the pocket', 14, 3],
      ['Maleta redonda|Round suitcase', 'Resiste golpes y pasillos angostos|Resists bumps and narrow hallways', 70, 3],
    ],
    fields: [
      text('citizenName', 'Nombre del ciudadano|Citizen name', { minLength: 2, maxLength: 60 }),
      num('cornerAngle', 'Ángulo de la esquina en grados|Corner angle in degrees', 30, 150),
      num('radiusCm', 'Radio de redondeo deseado en cm|Desired rounding radius in cm', 1, 50),
      pat('cornerId', 'Código de esquina|Corner code', '^EQ-\\d{4}-[NSEO]$', 'EQ-, cuatro dígitos, guion y una letra N, S, E u O, ej. EQ-0731-N|EQ-, four digits, a dash and N, S, E or W letter, e.g. EQ-0731-N'),
      sel('material', 'Material|Material', ['Madera|Wood', 'Piedra|Stone', 'Metal|Metal', 'Plástico|Plastic']),
      chk('injured', 'Me golpeé con esa esquina antes|I have bumped into that corner before'),
    ],
    contact: ['Una esquina que me persigue|A corner that haunts me', 'Quiero que la mía sea redonda|I want mine rounded', 'Redondeo urgente|Urgent rounding', 'Ser inspector de ángulos|Become an angle inspector'],
    faq: [
      ['¿Qué es un redondeo oficial?|What is an official rounding?', 'Una esquina con certificado y sello de suavidad.|A corner with a certificate and smoothness seal.'],
      ['¿Cuánto cuesta?|How much does it cost?', 'Depende del radio y del material, con presupuesto inmediato.|It depends on radius and material, with an instant quote.'],
      ['¿Se puede deshacer?|Can it be undone?', 'No, pero se puede apreciar una esquina nueva en la misma pieza.|No, but a new corner can be enjoyed in the same piece.'],
      ['¿Atienden urgencias?|Do you handle emergencies?', 'Sí, para esquinas con antecedentes de moretones.|Yes, for corners with a history of bruises.'],
      ['¿Quién inspecciona?|Who inspects?', 'Inspectores con rodilleras y un transportador de oro.|Inspectors with kneepads and a golden protractor.'],
    ],
    posts: [
      ['La esquina más peligrosa del barrio|The neighborhood\'s most dangerous corner', 'Estadística y anécdotas de rodillas.|Statistics and knee anecdotes.', 'Inspectora Angélica Curva'],
      ['Geometría del respeto|Geometry of respect', 'Por qué un ángulo recto es menos amable.|Why a right angle is less kind.', 'Ing. Omar Radio'],
      ['Redondeamos la plaza|We rounded the square', 'Antes y después de la obra.|Before and after the works.', 'Equipo Esquinas Redondas'],
    ],
    wiz: {
      title: 'Solicitud de redondeo|Rounding request',
      steps: [
        ['Lugar|Place', [sel('place', 'Dónde está la esquina|Where the corner is', ['Mi casa|My home', 'Un espacio público|A public space', 'Mi trabajo|My workplace'])]],
        ['Tamaño y fecha|Size and date', [num('radius', 'Radio solicitado en cm|Requested radius in cm', 1, 50), date('inspectDay', 'Día de la inspección|Inspection day', 'noPast')]],
        ['Espacio público|Public space', [text('streetName', 'Calle y altura|Street and number', { minLength: 4, maxLength: 80 })]],
        ['Detalles|Details', [area('bumps', 'Historial de golpes|Bump history', 250)]],
      ],
      cond: ['place', 'a-public-space', ['streetName']],
    },
    dash: { cols: ['Tipo de esquina|Corner type', 'Esquinas redondeadas|Corners rounded', 'Fecha de obra|Work date', 'Costo|Cost'], pool: ['Mesa de comedor|Dining table', 'Escritorio|Desk', 'Vereda|Sidewalk', 'Escalera|Staircase', 'Marco de puerta|Door frame', 'Mostrador público|Public counter'], n: [1, 80], m: [8, 5000] },
  },
  {
    id: 'agencia-de-coincidencias',
    name: 'Agencia de Coincidencias Programadas|Scheduled Coincidences Agency',
    tag: 'Qué casualidad que nos encontraras|What a coincidence that you found us',
    style: [160, 300, 'sans', 8, 'playful'],
    cur: ['≈', 'AZR', 2, 'after'],
    nouns: ['coincidencia|coincidencias|coincidence|coincidences', 'cliente|clientes|client|clients', 'encargo|encargos|booking|bookings', 'escenario|escenarios|scenario|scenarios'],
    nav: ['Recepción casual|Casual reception', 'Mis casualidades|My chances', 'Programar encuentro|Schedule a meeting', 'Panel de azar|Chance panel', 'Cuaderno de sincronías|Synchronicity notebook'],
    cats: ['Encuentros|Meetings', 'Objetos que aparecen|Objects that appear', 'Fechas y números|Dates and numbers', 'Giros del destino|Twists of fate'],
    items: [
      ['Encontrarte con un amigo en el tren|Meet a friend on the train', 'Con diálogo espontáneo incluido|Spontaneous dialogue included', 25, 0],
      ['Cruce con tu ex en una librería|Run into your ex at a bookstore', 'Sin escenas incómodas, garantizado|No awkward scenes, guaranteed', 40, 0],
      ['Presentación casual a un empleador|Casual introduction to an employer', 'Un café con "sin querer" incluido|A coffee with an accidental "oops"', 90, 0],
      ['Hallazgo de una moneda en la vereda|Finding a coin on the sidewalk', 'De valor modesto y mucha alegría|Modest value and much joy', 3, 1],
      ['Llave que aparece donde buscaste|Key that shows up where you looked', 'Después de buscar en cinco lugares|After searching in five places', 6, 1],
      ['Paraguas justo antes de la lluvia|Umbrella right before the rain', 'Entregado por un vecino casual|Delivered by a casual neighbor', 8, 1],
      ['Número de la suerte en un recibo|Lucky number on a receipt', 'Coincide con tu cumpleaños|Matches your birthday', 5, 2],
      ['Fecha repetida en tres tickets|Date repeated on three tickets', 'Con sello y fotografía|With stamp and photo', 7, 2],
      ['Hora 11:11 en el reloj|11:11 on the clock', 'Con tu mirada justo ahí|With you looking right at it', 4, 2],
      ['Llamada de alguien en quien pensabas|Call from someone you were thinking of', 'Sin hacer trampa en el teléfono|Without tampering with the phone', 20, 3],
      ['Canción que suena en el momento justo|Song that plays at the right moment', 'Elegida por un DJ comprometido|Chosen by a committed DJ', 15, 3],
      ['Giro de trabajo inesperado|Unexpected job twist', 'Con carta de oferta y un cartel de felicitaciones|With an offer letter and a congratulations banner', 150, 3],
    ],
    fields: [
      text('clientName', 'Nombre del cliente|Client name', { minLength: 2, maxLength: 60 }),
      sel('coincidenceKind', 'Tipo de coincidencia|Kind of coincidence', ['Social|Social', 'Material|Material', 'Numérica|Numerical', 'Laboral|Work-related']),
      num('probability', 'Probabilidad deseada (%)|Desired probability (%)', 1, 100),
      pat('bookingNo', 'Número de reserva|Booking number', '^COI-\\d{4}-[A-Z]{2}$', 'COI-, cuatro dígitos, guion y dos letras, ej. COI-1104-AB|COI-, four digits, a dash and two letters, e.g. COI-1104-AB'),
      date('whenDate', 'Fecha de la casualidad|Date of the coincidence', 'noFuture'),
      chk('noSpoilers', 'No avisarme cuándo ocurrirá|Do not tell me when it will happen'),
    ],
    contact: ['Coincidencia fallida|Failed coincidence', 'Casualidad no deseada|Unwanted chance', 'Pedido de sincronía|Synchronicity request', 'Agencia para eventos|Event agency'],
    faq: [
      ['¿No es trampa programar casualidades?|Is it not cheating to schedule chances?', 'Es arte: el azar necesita un buen equipo de producción.|It is art: chance needs a good production crew.'],
      ['¿Cuánto tarda en cumplirse?|How long until it comes true?', 'Depende del escenario; las simples, un día, las complejas, tres meses.|Depends on the scenario; simple ones a day, complex ones three months.'],
      ['¿Puedo elegir a la otra persona?|May I choose the other person?', 'Sí, con su consentimiento previo y un buen motivo.|Yes, with prior consent and a good reason.'],
      ['¿Hay garantía?|Is there a guarantee?', 'Si no ocurre, repetimos el trabajo hasta que parezca natural.|If it fails, we repeat the job until it looks natural.'],
      ['¿Qué tan natural parece?|How natural does it look?', 'Mucho, y nadie sospecha, salvo el cliente.|Very, and nobody suspects, except the client.'],
    ],
    posts: [
      ['Cómo diseñar una buena casualidad|Designing a good coincidence', 'Cinco reglas de guion para el azar.|Five screenplay rules for chance.', 'Directora Sonia Azar'],
      ['La casualidad que cambió una vida|The coincidence that changed a life', 'Una cliente cuenta su reencuentro.|A client recounts her reunion.', 'Clienta Dolores Rey'],
      ['Los errores más comunes|The most common mistakes', 'Cuando la casualidad salió demasiado perfecta.|When the coincidence came out too perfect.', 'Directora Sonia Azar'],
    ],
    wiz: {
      title: 'Planificá una casualidad|Plan a coincidence',
      steps: [
        ['Tipo|Type', [rad('wizType', 'Qué buscás|What you seek', ['Un encuentro|A meeting', 'Un objeto o suerte|An object or luck'])]],
        ['Fecha y naturalidad|Date and naturalness', [date('plannedChance', 'Fecha deseada|Desired date', 'noPast'), num('naturalness', 'Naturalidad requerida (1 a 10)|Required naturalness (1 to 10)', 1, 10)]],
        ['Encuentro|Meeting', [text('whoMeet', 'Con quién querés encontrarte|Who you want to meet', { minLength: 2, maxLength: 60 })]],
        ['Presupuesto|Budget', [num('chanceBudget', 'Presupuesto|Budget', 3, 1000)]],
      ],
      cond: ['wizType', 'a-meeting', ['whoMeet']],
    },
    dash: { cols: ['Escenario|Scenario', 'Coincidencias ejecutadas|Coincidences executed', 'Fecha|Date', 'Facturado|Billed'], pool: ['Encuentro en tren|Train meeting', 'Moneda en la vereda|Coin on the sidewalk', 'Hora 11:11|11:11', 'Llamada oportuna|Timely call', 'Canción justa|Perfect song', 'Giro laboral|Work twist'], n: [1, 50], m: [3, 3000] },
  },
  {
    id: 'videoclub-estrella-vhs',
    name: 'Videoclub Estrella VHS|Star VHS Video Rental',
    tag: 'Rebobiná antes de devolver, como en 1995|Rewind before returning, like it\'s 1995',
    style: [280, 55, 'mono', 2, 'playful'],
    cur: ['$', 'ARS', 0],
    nouns: ['película|películas|movie|movies', 'socio|socios|member|members', 'alquiler|alquileres|rental|rentals', 'estante|estantes|shelf|shelves'],
    nav: ['Mostrador de alquiler|Rental counter', 'Mi bolsa de cintas|My tape bag', 'Alquilar ahora|Rent now', 'Libro de devoluciones|Returns ledger', 'Estrenos de la semana|This week\'s new arrivals'],
    cats: ['Acción y aventura|Action and adventure', 'Comedias|Comedies', 'Terror de medianoche|Midnight horror', 'Clásicos y cine de autor|Classics and arthouse'],
    items: [
      ['Persecución en el desierto|Desert Chase', 'Cuarenta minutos de explosiones controladas|Forty minutes of controlled explosions', 800, 0],
      ['El último tren a la frontera|Last Train to the Border', 'Thriller con un guion de ocho giros|Thriller with eight plot twists', 800, 0],
      ['Cazadores de tesoros|Treasure Hunters', 'Una aventura juvenil con mapa y loro|A teen adventure with a map and a parrot', 700, 0],
      ['Dos tipos en un auto|Two Guys in a Car', 'Comedia de carretera con un perro|A road comedy with a dog', 700, 1],
      ['Mi suegra es un robot|My Mother-in-Law Is a Robot', 'Un clásico de tardes de domingo|A Sunday afternoon classic', 700, 1],
      ['La fiesta equivocada|The Wrong Party', 'Todos creen que es otro cumpleaños|Everyone thinks it is a different birthday', 700, 1],
      ['La casa del lago negro|The Black Lake House', 'Terror clásico con pasillos largos|Classic horror with long hallways', 800, 2],
      ['Noche de espejos|Night of Mirrors', 'Cada reflejo guarda un secreto|Every reflection hides a secret', 800, 2],
      ['El cementerio de las cintas|The Tape Graveyard', 'Meta-terror en un videoclub|Meta-horror in a video store', 800, 2],
      ['Tango en Montevideo|Tango in Montevideo', 'Drama musical con bailarines reales|Musical drama with real dancers', 650, 3],
      ['La mujer del puerto|The Woman of the Harbor', 'Clásico en blanco y negro restaurado|Restored black-and-white classic', 650, 3],
      ['Cortos de la nueva ola|New Wave Shorts', 'Seis cortometrajes en una sola cinta|Six short films on a single tape', 600, 3],
    ],
    fields: [
      text('memberName', 'Nombre del socio|Member name', { minLength: 2, maxLength: 60 }),
      pat('memberCard', 'Número de carnet|Member card number', '^VHS-\\d{5}$', 'VHS- y cinco dígitos, ej. VHS-01995|VHS- and five digits, e.g. VHS-01995'),
      sel('format', 'Formato de preferencia|Preferred format', ['VHS|VHS', 'Beta|Beta tape', 'DVD|DVD']),
      num('rentalDays', 'Días de alquiler|Rental days', 1, 14),
      chk('rewind', 'Prometo rebobinar antes de devolver|I promise to rewind before returning', true),
      num('moviesPerWeek', 'Películas por semana|Movies per week', 1, 10),
    ],
    contact: ['Cinta enredada|Tangled tape', 'Multa por atraso|Late fee', 'Reservar un estreno|Reserve a new release', 'Comprar cintas usadas|Buy used tapes'],
    faq: [
      ['¿Cuánto cuesta alquilar?|What does a rental cost?', 'Entre 600 y 800 pesos por dos noches, estrenos un poco más.|Between 600 and 800 pesos for two nights, new releases a bit more.'],
      ['¿Qué pasa si no rebobino?|What if I do not rewind?', 'Pagás una multa simbólica y el próximo socio te maldice.|You pay a symbolic fine and the next member curses you.'],
      ['¿Todavía tienen reproductores en venta?|Do you still sell players?', 'Sí, reacondicionados y con garantía de tres meses.|Yes, refurbished with a three-month warranty.'],
      ['¿Aceptan socios nuevos?|Do you take new members?', 'Con carnet, foto y un título que recomiendes.|With a card, photo and one title you recommend.'],
      ['¿Se puede alquilar los domingos?|Can I rent on Sundays?', 'Sí, de 14 a 22 h, y hay pochoclo gratis para socios.|Yes, 2 to 10 pm, and members get free popcorn.'],
    ],
    posts: [
      ['Cómo rebobinar sin estirar la cinta|Rewinding without stretching the tape', 'Cuatro trucos de empleado viejo.|Four tricks from a veteran clerk.', 'Dueño Lito Cinta'],
      ['Diez clásicos que no están en ninguna plataforma|Ten classics on no streaming platform', 'Tesoros que solo se ven en tu casa.|Treasures only seen at home.', 'Empleada Daniela Beta'],
      ['El estante de terror: una guía|The horror shelf: a guide', 'Qué alquilar según tu valentía.|What to rent for your level of courage.', 'Dueño Lito Cinta'],
    ],
    wiz: {
      title: 'Armá tu maratón|Plan your marathon',
      steps: [
        ['Género|Genre', [sel('genre', 'Género de la noche|Genre of the night', ['Acción|Action', 'Comedia|Comedy', 'Terror|Horror'])]],
        ['Cantidad y fecha|Count and date', [num('count', 'Películas|Movies', 1, 8), date('night', 'Noche de maratón|Marathon night', 'noPast')]],
        ['Terror|Horror', [chk('lights', 'Prefiero ver con las luces prendidas|I prefer watching with the lights on')]],
        ['Snacks|Snacks', [chk('popcorn', 'Reservar pochoclo|Reserve popcorn')]],
      ],
      cond: ['genre', 'horror', ['lights']],
    },
    dash: { cols: ['Película|Movie', 'Alquileres|Rentals', 'Fecha de alquiler|Rental date', 'Recaudado|Takings'], pool: ['Persecución en el desierto|Desert Chase', 'Mi suegra es un robot|My Mother-in-Law Is a Robot', 'La casa del lago negro|The Black Lake House', 'Tango en Montevideo|Tango in Montevideo', 'Cortos de la nueva ola|New Wave Shorts', 'Cazadores de tesoros|Treasure Hunters'], n: [1, 40], m: [600, 32000] },
  },
  {
    id: 'cibercafe-dial-up-1999',
    name: 'Cibercafé Dial-Up Paraíso|Dial-Up Paradise Cyber Café',
    tag: 'Esperá el ruidito del módem, la magia ya llega|Wait for the modem noise, the magic is coming',
    style: [160, 300, 'mono', 0, 'tech'],
    cur: ['$', 'USD', 2],
    nouns: ['servicio|servicios|service|services', 'cliente|clientes|customer|customers', 'sesión|sesiones|session|sessions', 'puesto|puestos|station|stations'],
    nav: ['Sala de máquinas|Machine room', 'Mi sesión|My session', 'Pagar la hora|Pay by the hour', 'Panel del administrador|Admin panel', 'Foro del local|House forum'],
    cats: ['Navegación|Browsing', 'Juegos en red|Network gaming', 'Impresión y escaneo|Printing and scanning', 'Bebidas y snacks|Drinks and snacks'],
    items: [
      ['Una hora de navegación|One hour of browsing', 'Con velocidad suficiente para ver tres fotos|Fast enough to load three photos', 1.5, 0],
      ['Pase de medio día|Half-day pass', 'Cuatro horas seguidas con un descanso|Four straight hours with one break', 4.5, 0],
      ['Correo y chat sin límite|Unlimited mail and chat', 'Para escribir cartas de amor digitales|For writing digital love letters', 2, 0],
      ['Torneo de laberinto en red|Network maze tournament', 'Cuatro jugadores por sala|Four players per room', 3, 1],
      ['Clásico de naves espaciales|Classic space shooter', 'Por tiempo, con ranking local|Timed, with local ranking', 2, 1],
      ['Noche de estrategia medieval|Medieval strategy night', 'Hasta el amanecer, con pizza|Until dawn, with pizza', 8, 1],
      ['Impresión en blanco y negro|Black-and-white printing', 'Por página, tinta de impresora de matriz|Per page, dot-matrix ink', 0.2, 2],
      ['Escaneo de fotos|Photo scanning', 'Hasta 600 dpi|Up to 600 dpi', 1, 2],
      ['Quemado de CD con tus fotos|CD burning with your photos', 'Incluye carátula en blanco|Blank cover included', 3, 2],
      ['Gaseosa en lata|Canned soda', 'Fría y sin gas de módem|Cold and without modem fizz', 1.2, 3],
      ['Papas fritas de paquete|Bagged chips', 'Para teclear con las manos grasosas|For typing with greasy fingers', 1.5, 3],
      ['Café instantáneo|Instant coffee', 'Para noches de torneo|For tournament nights', 1, 3],
    ],
    fields: [
      text('nickname', 'Apodo en pantalla|Screen nickname', { minLength: 2, maxLength: 24 }),
      pat('seat', 'Puesto asignado|Assigned station', '^PC-\\d{2}$', 'PC- y dos dígitos, ej. PC-07|PC- and two digits, e.g. PC-07', false),
      sel('connection', 'Conexión preferida|Preferred connection', ['Módem 56k|56k modem', 'ADSL lento|Slow ADSL', 'No me importa|I do not mind']),
      num('hours', 'Horas a reservar|Hours to reserve', 1, 12),
      num('age', 'Edad|Age', 8, 99),
      chk('printouts', 'Voy a imprimir documentos|I will print documents'),
    ],
    contact: ['Se cortó la conexión|Connection dropped', 'Reservar el local para un torneo|Book the venue for a tournament', 'Problema con mi sesión|Session problem', 'Venta de equipos viejos|Selling old gear'],
    faq: [
      ['¿Qué velocidad tienen?|What speed do you have?', 'La de un módem que respira hondo antes de cada página.|That of a modem that takes a deep breath before every page.'],
      ['¿Hay descuentos por hora?|Are there hourly discounts?', 'Sí, de lunes a jueves antes de las cinco.|Yes, Monday to Thursday before five.'],
      ['¿Puedo traer mi disquete?|Can I bring my floppy disk?', 'Sí, aunque la mitad no pasa el verificador de virus.|Yes, though half do not pass the virus checker.'],
      ['¿Hay comida?|Is there food?', 'Papas, gaseosas y tostados en el mostrador.|Chips, sodas and toasties at the counter.'],
      ['¿Se puede jugar de noche?|Can I play at night?', 'Los sábados hasta las dos de la mañana, con permiso paterno para menores.|Saturdays until 2 am, with parental permission for minors.'],
    ],
    posts: [
      ['Cómo armar un correo en una hora|Writing an email in an hour', 'Un instructivo con muchos pasos y mucho ruido.|A tutorial with many steps and much noise.', 'Encargado Néstor Módem'],
      ['El torneo del verano|The summer tournament', 'Resultados y anécdotas de los finalistas.|Results and finalist anecdotes.', 'Cronista Tatiana Byte'],
      ['La primera foto que descargué|The first photo I ever downloaded', 'Una historia de media hora de espera.|A half-hour-wait story.', 'Cliente Gastón Pixel'],
    ],
    wiz: {
      title: 'Reservar tu puesto|Reserve your station',
      steps: [
        ['Uso|Use', [rad('use', 'Para qué lo vas a usar|What you will use it for', ['Trabajar o estudiar|Work or study', 'Jugar|Gaming'])]],
        ['Fecha y horas|Date and hours', [date('bookDay', 'Día de la reserva|Booking day', 'noPast'), num('bookHours', 'Horas reservadas|Hours booked', 1, 10)]],
        ['Juegos|Gaming', [text('gameName', 'Juego que vas a jugar|Game you will play', { minLength: 2, maxLength: 40 })]],
        ['Extras|Extras', [chk('snacks', 'Agregar combo de papas y gaseosa|Add a chips and soda combo')]],
      ],
      cond: ['use', 'gaming', ['gameName']],
    },
    dash: { cols: ['Servicio|Service', 'Sesiones|Sessions', 'Fecha|Date', 'Ingresos|Income'], pool: ['Navegación por hora|Hourly browsing', 'Pase de medio día|Half-day pass', 'Torneo en red|Network tournament', 'Impresión|Printing', 'Quemado de CD|CD burning', 'Snacks y bebidas|Snacks and drinks'], n: [3, 90], m: [4, 380] },
  },
]

export const absurd = specs.map((s) => defineTheme('absurd', s))
