// Familia "everyday": negocios e instituciones cotidianas (TASK-048). Dato puro, sin cablear al motor.
import { defineTheme, text, area, num, date, chk, sel, rad, pat } from './build.js'

const specs = [
  {
    id: 'almacen-esquina',
    name: 'Almacén La Esquina|The Corner Grocer',
    tag: 'Lo que falta para la cena, a dos cuadras|Whatever dinner is missing, two blocks away',
    style: [32, 12, 'rounded', 10, 'playful'],
    cur: ['$', 'USD', 2],
    nouns: ['producto|productos|product|products', 'vecino|vecinos|neighbor|neighbors', 'compra|compras|purchase|purchases', 'góndola|góndolas|aisle|aisles'],
    nav: ['Inicio del barrio|Neighborhood home', 'Canasta|Basket', 'Pagar en caja|Pay at the till', 'Panel del encargado|Manager board', 'Novedades de la cuadra|Block news'],
    cats: ['Almacén seco|Dry goods', 'Frescos|Fresh produce', 'Lácteos y fiambres|Dairy and deli', 'Limpieza|Cleaning'],
    items: [
      ['Fideos moñitos 500 g|Bow-tie pasta 500 g', 'Trigo candeal, cocción en nueve minutos|Durum wheat, ready in nine minutes', 1.8, 0],
      ['Yerba mate con palo|Stemmed mate tea', 'Molienda gruesa para cebar largo|Coarse grind for long brewing', 4.5, 0],
      ['Lentejas turcas 1 kg|Turkish lentils 1 kg', 'No necesitan remojo previo|No pre-soaking needed', 3.2, 0],
      ['Tomates perita|Plum tomatoes', 'Maduros en planta, por kilo|Vine ripened, sold by the kilo', 2.4, 1],
      ['Zapallo anco|Butternut squash', 'Dulce y firme para el horno|Sweet and firm for roasting', 1.6, 1],
      ['Manzanas rojas|Red apples', 'Crocantes, de chacra cercana|Crisp, from a nearby farm', 2.9, 1],
      ['Queso cremoso 400 g|Creamy cheese 400 g', 'Se derrite sin llorar|Melts without weeping', 5.1, 2],
      ['Jamón cocido natural|Plain cooked ham', 'Feteado a pedido, sin humo líquido|Sliced to order, no liquid smoke', 6.7, 2],
      ['Leche entera 1 l|Whole milk 1 l', 'Pasteurizada ese mismo día|Pasteurized the same day', 1.3, 2],
      ['Lavandina concentrada|Concentrated bleach', 'Un chorrito rinde un balde|A splash fills a bucket', 1.9, 3],
      ['Esponja doble faz|Two-sided sponge', 'Lado suave para vasos, lado duro para ollas|Soft side for glasses, tough side for pots', 0.9, 3],
      ['Detergente de limón|Lemon dish soap', 'Espuma corta y aroma largo|Short suds, long scent', 2.2, 3],
    ],
    fields: [
      text('fullName', 'Nombre y apellido|Full name', { minLength: 3, maxLength: 60 }),
      text('street', 'Calle y altura|Street and number', { minLength: 4, maxLength: 80 }),
      num('household', 'Personas en el hogar|People in the household', 1, 15),
      sel('delivery', 'Franja de reparto|Delivery window', ['Mañana|Morning', 'Tarde|Afternoon', 'Noche|Evening']),
      pat('cardCode', 'Código de tarjeta del almacén|Shop loyalty card code', '^ALM-\\d{5}$', 'Cinco dígitos tras ALM-, ej. ALM-04821|Five digits after ALM-, e.g. ALM-04821', false),
    ],
    contact: ['Pedido que no llegó|Order never arrived', 'Producto en mal estado|Spoiled product', 'Sugerir un producto|Suggest a product', 'Fiado y cuenta corriente|Store credit and tabs'],
    faq: [
      ['¿Hasta qué hora reparten?|How late do you deliver?', 'Hasta las nueve de la noche, y los domingos solo a la mañana.|Until nine at night, and Sundays only in the morning.'],
      ['¿Puedo pedir la verdura por unidad?|Can I order produce by the piece?', 'Sí, aunque el kilo siempre sale más barato.|Yes, though the kilo is always cheaper.'],
      ['¿Aceptan vales de comida?|Do you take meal vouchers?', 'Aceptamos los dos vales del barrio, no los de otras provincias.|We take the two neighborhood vouchers, not out-of-province ones.'],
      ['¿Qué pasa si falta un artículo?|What if an item is missing?', 'Te escribimos antes de armar la bolsa para ofrecerte un reemplazo.|We write to you before packing to offer a substitute.'],
      ['¿Hay bolsas reutilizables?|Are there reusable bags?', 'Hay bolsas de tela con el dibujo del gato del local, a precio de costo.|There are cloth bags with the shop cat on them, sold at cost.'],
    ],
    posts: [
      ['El tomate de febrero no miente|February tomatoes do not lie', 'Por qué la perita sale mejor al final del verano y cómo elegirla.|Why plum tomatoes shine at summer end and how to pick them.', 'Don Anselmo'],
      ['Cuatro usos del zapallo anco|Four uses for butternut squash', 'Sopa, puré, tarta y un postre que no pensabas.|Soup, mash, tart and a dessert you did not expect.', 'Rita Baigorria'],
      ['Mate sin amargor|Mate without the bitter', 'Temperatura del agua y orden de la yerba, paso a paso.|Water temperature and herb layering, step by step.', 'Tomás del Valle'],
    ],
    wiz: {
      title: 'Armá tu canasta semanal|Build your weekly basket',
      steps: [
        ['Tipo de hogar|Household type', [rad('hogar', 'Tipo de hogar|Household type', ['Soltero o pareja|Single or couple', 'Familia con chicos|Family with kids'])]],
        ['Cantidad y fecha|Amount and date', [num('mealsPerWeek', 'Cenas en casa por semana|Dinners at home per week', 1, 7), date('startDate', 'Primera entrega|First delivery', 'noPast')]],
        ['Detalles para chicos|Details for kids', [area('kidsNotes', 'Alergias o gustos de los chicos|Kids allergies or tastes', 200)]],
        ['Confirmación|Confirmation', [chk('substitutions', 'Acepto reemplazos de productos|I accept product substitutions', true)]],
      ],
      cond: ['hogar', 'family-with-kids', ['kidsNotes']],
    },
    dash: { cols: ['Producto|Product', 'Unidades vendidas|Units sold', 'Día de venta|Sale day', 'Recaudado|Takings'], pool: ['Fideos moñitos|Bow-tie pasta', 'Yerba con palo|Stemmed mate', 'Tomate perita|Plum tomato', 'Queso cremoso|Creamy cheese', 'Leche entera|Whole milk', 'Esponja doble faz|Two-sided sponge'], n: [3, 90], m: [8, 260] },
  },
  {
    id: 'clinica-ribera',
    name: 'Clínica Ribera Norte|Ribera Norte Clinic',
    tag: 'Turnos que respetan tu tiempo|Appointments that respect your time',
    style: [196, 160, 'sans', 6, 'clean'],
    cur: ['€', 'EUR', 2],
    nouns: ['consulta|consultas|consultation|consultations', 'paciente|pacientes|patient|patients', 'turno|turnos|appointment|appointments', 'especialidad|especialidades|specialty|specialties'],
    nav: ['Sala de espera|Waiting room', 'Mis turnos|My appointments', 'Confirmar turno|Confirm appointment', 'Tablero de guardia|On-call board', 'Salud al día|Health digest'],
    cats: ['Medicina general|General medicine', 'Cardiología|Cardiology', 'Pediatría|Pediatrics', 'Estudios y laboratorio|Tests and lab work'],
    items: [
      ['Consulta de clínica médica|General practice visit', 'Control anual con historia clínica completa|Annual check-up with full clinical history', 45, 0],
      ['Certificado de aptitud física|Fitness certificate', 'Para deporte, trabajo o viajes|For sports, work or travel', 30, 0],
      ['Vacunación antigripal|Flu vaccination', 'Dosis de temporada, sin turno previo|Seasonal dose, walk-in', 18, 0],
      ['Electrocardiograma|Electrocardiogram', 'Informe en el día con cardiólogo|Same-day report by a cardiologist', 55, 1],
      ['Holter de 24 horas|24-hour Holter monitor', 'Se retira al día siguiente|Returned the next day', 90, 1],
      ['Prueba de esfuerzo|Stress test', 'En cinta, con supervisión médica|On a treadmill, medically supervised', 110, 1],
      ['Control del niño sano|Well-child check', 'Peso, talla y calendario de vacunas|Weight, height and vaccine schedule', 38, 2],
      ['Consulta por fiebre infantil|Pediatric fever visit', 'Atención el mismo día hasta las 20 h|Same-day care until 8 pm', 42, 2],
      ['Test de visión escolar|School vision screening', 'Detecta miopía antes del primer grado|Catches myopia before first grade', 25, 2],
      ['Hemograma completo|Complete blood count', 'Ayuno de ocho horas, resultados en 24 h|Eight-hour fast, results in 24 h', 22, 3],
      ['Perfil lipídico|Lipid panel', 'Colesterol total, LDL, HDL y triglicéridos|Total cholesterol, LDL, HDL and triglycerides', 28, 3],
      ['Ecografía abdominal|Abdominal ultrasound', 'Se informa antes de salir del consultorio|Reported before you leave the room', 70, 3],
    ],
    fields: [
      text('fullName', 'Nombre completo|Full name', { minLength: 3, maxLength: 70 }),
      pat('chartNumber', 'Número de historia clínica|Medical chart number', '^HC-\\d{6}$', 'Seis dígitos tras HC-, ej. HC-120457|Six digits after HC-, e.g. HC-120457', false),
      date('birthDate', 'Fecha de nacimiento|Date of birth', 'noFuture'),
      sel('coverage', 'Cobertura médica|Insurance coverage', ['Obra social|Public plan', 'Prepaga|Private plan', 'Particular|Self-pay']),
      num('weightKg', 'Peso en kilos|Weight in kilograms', 2, 250, false),
    ],
    contact: ['Cambiar un turno|Reschedule an appointment', 'Pedir resultados|Request lab results', 'Facturación|Billing', 'Reclamo de atención|Care complaint'],
    faq: [
      ['¿Con cuánta anticipación debo llegar?|How early should I arrive?', 'Diez minutos antes, con documento y credencial de cobertura.|Ten minutes early, with ID and your coverage card.'],
      ['¿Cómo recibo los resultados?|How do I get my results?', 'Los subimos a tu cuenta apenas el profesional los firma.|We post them to your account once the doctor signs off.'],
      ['¿Atienden urgencias?|Do you see emergencies?', 'Solo urgencias menores; ante dolor de pecho llamá al servicio de emergencias.|Minor urgencies only; for chest pain call emergency services.'],
      ['¿Puedo llevar a un acompañante?|May I bring a companion?', 'Sí, una persona por paciente en consultorio.|Yes, one person per patient in the exam room.'],
      ['¿Cuánto dura un turno?|How long is an appointment?', 'Veinte minutos de consulta y treinta si es primera vez.|Twenty minutes, thirty for a first visit.'],
    ],
    posts: [
      ['Chequeo anual: qué pedir y qué no|The annual check-up: what to ask for', 'Una guía para no hacerte estudios de más.|A guide to avoiding unnecessary tests.', 'Dra. Inés Calderón'],
      ['Fiebre en niños: cuándo consultar|Fever in children: when to call', 'Señales que justifican una visita y señales que no.|Signs that justify a visit and signs that do not.', 'Dr. Marcos Ventura'],
      ['Leer un colesterol sin asustarse|Reading a cholesterol result calmly', 'Qué significan los números y qué cambia con la dieta.|What the numbers mean and what diet changes.', 'Lic. Paula Argüello'],
    ],
    wiz: {
      title: 'Reservá tu turno|Book your appointment',
      steps: [
        ['Motivo|Reason', [sel('reason', 'Motivo de consulta|Reason for visit', ['Control de rutina|Routine check', 'Un síntoma nuevo|A new symptom', 'Estudio indicado|Prescribed test'])]],
        ['Fecha y duración|Date and length', [date('preferredDay', 'Día preferido|Preferred day', 'noPast'), num('daysSymptom', 'Días con síntomas|Days with symptoms', 0, 90)]],
        ['Síntoma|Symptom', [area('symptomNotes', 'Describí el síntoma|Describe the symptom', 250)]],
        ['Confirmación|Confirmation', [chk('reminder', 'Enviarme un recordatorio por correo|Send me an email reminder')]],
      ],
      cond: ['reason', 'a-new-symptom', ['symptomNotes', 'daysSymptom']],
    },
    dash: { cols: ['Especialidad|Specialty', 'Turnos del día|Appointments today', 'Fecha|Date', 'Facturado|Billed'], pool: ['Clínica médica|General medicine', 'Cardiología|Cardiology', 'Pediatría|Pediatrics', 'Laboratorio|Laboratory', 'Ecografía|Ultrasound', 'Vacunatorio|Vaccination'], n: [2, 40], m: [90, 3200] },
  },
  {
    id: 'gimnasio-forja',
    name: 'Gimnasio Forja 24|Forja 24 Gym',
    tag: 'Hierro, sudor y agua tibia en las duchas|Iron, sweat and warm shower water',
    style: [8, 40, 'sans', 2, 'tech'],
    cur: ['$', 'MXN', 0],
    nouns: ['pase|pases|pass|passes', 'socio|socios|member|members', 'inscripción|inscripciones|enrollment|enrollments', 'disciplina|disciplinas|discipline|disciplines'],
    nav: ['Sala principal|Main floor', 'Mi plan|My plan', 'Alta de membresía|Membership checkout', 'Ocupación en vivo|Live occupancy', 'Bitácora del entrenador|Coach log'],
    cats: ['Membresías|Memberships', 'Clases grupales|Group classes', 'Entrenamiento personal|Personal training', 'Tienda|Pro shop'],
    items: [
      ['Pase mensual libre|Unlimited monthly pass', 'Acceso a toda la sala, 24 horas|Full floor access, 24 hours', 650, 0],
      ['Pase de diez entradas|Ten-visit pass', 'Para quien entrena cuando puede|For those who train when they can', 380, 0],
      ['Pase anual con casillero|Annual pass with locker', 'Incluye candado y toalla de bienvenida|Includes padlock and welcome towel', 6200, 0],
      ['Clase de spinning|Spinning class', 'Cuarenta y cinco minutos con ritmo y luces bajas|Forty-five minutes of rhythm and dim lights', 90, 1],
      ['Clase de movilidad|Mobility class', 'Para hombros, cadera y espalda baja|For shoulders, hips and lower back', 80, 1],
      ['Funcional de madrugada|Dawn functional training', 'A las 6:00, grupos de ocho personas|At 6:00 a.m., groups of eight', 85, 1],
      ['Sesión con entrenador|Coach session', 'Una hora con plan armado a medida|One hour with a tailor-made plan', 450, 2],
      ['Evaluación corporal|Body assessment', 'Medidas, flexibilidad y objetivo realista|Measurements, flexibility and a realistic goal', 300, 2],
      ['Plan de ocho semanas|Eight-week program', 'Rutinas con seguimiento semanal por mensaje|Routines with weekly check-ins by message', 1400, 2],
      ['Botella térmica 750 ml|Insulated bottle 750 ml', 'Mantiene el agua fría diez horas|Keeps water cold for ten hours', 280, 3],
      ['Cinturón de levantamiento|Lifting belt', 'Cuero curtido, cierre de palanca|Tanned leather, lever clasp', 1150, 3],
      ['Cuerda de saltar con rulemanes|Ball-bearing jump rope', 'Cable de acero y mangos de aluminio|Steel cable and aluminum grips', 190, 3],
    ],
    fields: [
      text('fullName', 'Nombre y apellido|Full name', { minLength: 3, maxLength: 60 }),
      num('age', 'Edad en años|Age in years', 14, 90),
      sel('goal', 'Objetivo principal|Main goal', ['Ganar fuerza|Build strength', 'Bajar de peso|Lose weight', 'Resistencia|Endurance', 'Salud general|General health']),
      pat('lockerCode', 'Código de casillero|Locker code', '^C-[0-9]{3}$', 'Una C, guion y tres dígitos, ej. C-042|A C, a dash and three digits, e.g. C-042', false),
      chk('parq', 'Declaro aptitud física (PAR-Q)|I declare physical fitness (PAR-Q)', true),
    ],
    contact: ['Congelar mi membresía|Freeze my membership', 'Problema con el torniquete|Turnstile problem', 'Cambiar de plan|Change plan', 'Felicitaciones o quejas|Praise or complaints'],
    faq: [
      ['¿Realmente abre las 24 horas?|Is it really open 24 hours?', 'Sí, con tarjeta magnética entre las 22 y las 6; hay cámaras y un botón de ayuda.|Yes, by key card between 10 pm and 6 am; there are cameras and a help button.'],
      ['¿Puedo traer a un amigo?|Can I bring a friend?', 'Dos veces por mes con pase de invitado gratuito.|Twice a month with a free guest pass.'],
      ['¿Hay duchas calientes?|Are there hot showers?', 'Seis duchas con agua caliente continua y secadores.|Six showers with continuous hot water and hairdryers.'],
      ['¿Qué pasa si me lesiono?|What if I get injured?', 'Congelamos el plan sin costo con un certificado médico.|We freeze your plan at no cost with a medical note.'],
      ['¿Cuándo vence la clase suelta?|When does a single class expire?', 'A los treinta días de la compra, sin excepciones.|Thirty days after purchase, no exceptions.'],
    ],
    posts: [
      ['Sentadilla: errores de cadera|Squat: hip mistakes', 'Tres señales de que tu profundidad no es la que creés.|Three signs your depth is not what you think.', 'Coach Lalo Ibarra'],
      ['Dormir para rendir|Sleeping to perform', 'Lo que pasa en el músculo mientras descansás.|What happens in the muscle while you rest.', 'Dra. Ximena Roel'],
      ['Mi primer mes en la sala|My first month on the floor', 'Una socia cuenta cómo empezó sin saber usar una máquina.|A member tells how she started without knowing a single machine.', 'Brenda Ochoa'],
    ],
    wiz: {
      title: 'Diseñá tu rutina inicial|Design your starter routine',
      steps: [
        ['Experiencia|Experience', [rad('level', 'Experiencia previa|Previous experience', ['Primera vez|First time', 'Ya entrené antes|Trained before'])]],
        ['Frecuencia y arranque|Frequency and start', [num('daysPerWeek', 'Días por semana|Days per week', 1, 7), date('startOn', 'Fecha de inicio|Start date', 'noPast')]],
        ['Lesiones|Injuries', [area('injuryNotes', 'Lesiones o molestias previas|Previous injuries or aches', 250)]],
        ['Confirmación|Confirmation', [chk('newsletter', 'Quiero recibir consejos semanales|I want weekly tips')]],
      ],
      cond: ['level', 'trained-before', ['injuryNotes']],
    },
    dash: { cols: ['Disciplina|Discipline', 'Asistentes|Attendees', 'Día|Day', 'Ingresos|Revenue'], pool: ['Spinning|Spinning', 'Movilidad|Mobility', 'Funcional|Functional', 'Pesas libres|Free weights', 'Boxeo técnico|Technical boxing', 'Yoga dinámico|Dynamic yoga'], n: [4, 48], m: [300, 9000] },
  },
  {
    id: 'agencia-viajes-brujula',
    name: 'Viajes Brújula Sur|Compass South Travel',
    tag: 'Itinerarios con margen para perderse|Itineraries with room to get lost',
    style: [210, 28, 'serif', 8, 'ornate'],
    cur: ['$', 'CLP', 0],
    nouns: ['paquete|paquetes|package|packages', 'viajero|viajeros|traveler|travelers', 'reserva|reservas|booking|bookings', 'destino|destinos|destination|destinations'],
    nav: ['Mapa de salida|Departures map', 'Mi maleta|My suitcase', 'Confirmar reserva|Confirm booking', 'Panel de agentes|Agents desk', 'Cuaderno de ruta|Route notebook'],
    cats: ['Patagonia y sur|Patagonia and the south', 'Norte andino|Andean north', 'Costa y playas|Coast and beaches', 'Escapadas urbanas|City getaways'],
    items: [
      ['Glaciares en cinco días|Glaciers in five days', 'Lago, trekking suave y un barco entre témpanos|Lake, gentle trekking and a boat among icebergs', 780000, 0],
      ['Ruta de los lagos|Lake district route', 'Auto de alquiler y cabañas de madera|Rental car and timber cabins', 520000, 0],
      ['Fin del mundo en tren|End of the world by train', 'Ushuaia y el canal en tres noches|Ushuaia and the channel in three nights', 610000, 0],
      ['Salar y lagunas de colores|Salt flat and colored lagoons', 'Cuatro días en 4x4 con guía local|Four days by 4x4 with a local guide', 690000, 1],
      ['Quebradas y viñedos|Canyons and vineyards', 'Tres bodegas pequeñas y pernocte en pueblo|Three small wineries and a night in a village', 430000, 1],
      ['Cielos limpios del desierto|Clear desert skies', 'Observación astronómica en altura|High-altitude stargazing', 350000, 1],
      ['Isla sin autos|Car-free island', 'Seis noches entre dunas y bicicleta|Six nights between dunes and bicycles', 480000, 2],
      ['Buceo en arrecife templado|Temperate reef diving', 'Curso básico y dos inmersiones guiadas|Basic course and two guided dives', 330000, 2],
      ['Cabotaje entre caletas|Cove-hopping by boat', 'Pesca, empanadas de mar y fogón|Fishing, seafood pastries and a campfire', 290000, 2],
      ['Ciudad vieja en fin de semana|Old town long weekend', 'Hotel boutique y recorrido de mercados|Boutique hotel and market tour', 260000, 3],
      ['Capital gastronómica|Culinary capital', 'Cinco cenas reservadas de antemano|Five dinners booked in advance', 540000, 3],
      ['Teatro y jazz de invierno|Winter theater and jazz', 'Entradas y noches en el barrio de las salas|Tickets and nights in the theater district', 310000, 3],
    ],
    fields: [
      text('fullName', 'Nombre como figura en el pasaporte|Name as on passport', { minLength: 3, maxLength: 70 }),
      pat('passport', 'Número de pasaporte|Passport number', '^[A-Z]{2}\\d{7}$', 'Dos letras mayúsculas y siete dígitos, ej. PA1234567|Two capital letters and seven digits, e.g. PA1234567'),
      date('passportExpiry', 'Vencimiento del pasaporte|Passport expiry', 'noPast'),
      sel('seat', 'Preferencia de asiento|Seat preference', ['Ventanilla|Window', 'Pasillo|Aisle', 'Me da igual|No preference']),
      num('travelers', 'Cantidad de viajeros|Number of travelers', 1, 12),
    ],
    contact: ['Cambiar fechas|Change dates', 'Seguro de viaje|Travel insurance', 'Documentación|Documents', 'Reclamo por un servicio|Complaint about a service'],
    faq: [
      ['¿Necesito visa?|Do I need a visa?', 'Depende de tu nacionalidad; te avisamos al confirmar el destino.|It depends on your nationality; we tell you when the destination is confirmed.'],
      ['¿Puedo pagar en cuotas?|Can I pay in installments?', 'Hasta en doce cuotas con tarjetas locales, sin recargo hasta seis.|Up to twelve installments on local cards, interest-free up to six.'],
      ['¿Qué incluye el paquete?|What does the package include?', 'Alojamiento, traslados y las actividades de la ficha; los almuerzos no.|Lodging, transfers and the listed activities; lunches are not included.'],
      ['¿Y si se cancela por clima?|What if weather cancels it?', 'Reprogramamos sin costo o devolvemos lo no ejecutado.|We reschedule at no cost or refund what was not delivered.'],
      ['¿Viajo seguro solo?|Is solo travel safe?', 'Armamos salidas con grupos pequeños y contacto local permanente.|We run small-group departures with a permanent local contact.'],
    ],
    posts: [
      ['Qué llevar al sur en octubre|What to pack for the south in October', 'Capas, cortaviento y un buen par de medias.|Layers, a windbreaker and a good pair of socks.', 'Ema Quintanilla'],
      ['El tren más lento de la costa|The slowest train on the coast', 'Un recorrido de siete horas que vale cada estación.|A seven-hour ride worth every station.', 'Gaspar Orellana'],
      ['Desierto: cómo cuidar la altura|The desert: coping with altitude', 'Hidratación, té de coca y calma en el primer día.|Hydration, coca tea and calm on day one.', 'Dr. Néstor Pizarro'],
    ],
    wiz: {
      title: 'Armá tu viaje a medida|Shape your tailor-made trip',
      steps: [
        ['Tipo de viaje|Trip type', [rad('tripKind', 'Con quién viajás|Who you travel with', ['Solo o en pareja|Solo or as a couple', 'Con niños|With children'])]],
        ['Fechas y presupuesto|Dates and budget', [date('leaveOn', 'Fecha de salida|Departure date', 'noPast'), num('budget', 'Presupuesto por persona|Budget per person', 100000, 3000000)]],
        ['Niños|Children', [num('kidsAge', 'Edad del menor|Age of the youngest', 0, 17)]],
        ['Notas|Notes', [area('wishes', 'Algo que no te podés perder|Something you cannot miss', 300)]],
      ],
      cond: ['tripKind', 'with-children', ['kidsAge']],
    },
    dash: { cols: ['Destino|Destination', 'Pasajeros|Passengers', 'Salida|Departure', 'Monto reservado|Booked amount'], pool: ['Glaciares|Glaciers', 'Ruta de los lagos|Lake route', 'Salar andino|Andean salt flat', 'Isla sin autos|Car-free island', 'Capital gastronómica|Culinary capital', 'Cabotaje|Cove-hopping'], n: [1, 14], m: [260000, 5200000] },
  },
  {
    id: 'restaurante-brasa-sal',
    name: 'Brasa y Sal Parrilla|Brasa y Sal Grill House',
    tag: 'Fuego lento, mesa larga|Slow fire, long table',
    style: [14, 38, 'serif', 4, 'ornate'],
    cur: ['$', 'ARS', 0],
    nouns: ['plato|platos|dish|dishes', 'comensal|comensales|diner|diners', 'comanda|comandas|order|orders', 'sección|secciones|section|sections'],
    nav: ['La mesa|The table', 'Mi comanda|My order', 'Pedir ahora|Order now', 'Tablero de cocina|Kitchen board', 'Notas del parrillero|Grillmaster notes'],
    cats: ['Entradas|Starters', 'De la parrilla|From the grill', 'Guarniciones|Sides', 'Postres|Desserts'],
    items: [
      ['Provoleta con orégano|Oregano provolone', 'Queso a la plancha con tomate asado|Griddled cheese with roasted tomato', 9800, 0],
      ['Empanada de carne cortada a cuchillo|Knife-cut beef empanada', 'Jugosa, con aceituna y huevo|Juicy, with olive and egg', 3200, 0],
      ['Molleja crocante|Crispy sweetbreads', 'Limón y sal gruesa al final|Lemon and coarse salt at the end', 14500, 0],
      ['Bife de chorizo 400 g|Sirloin steak 400 g', 'Punto a elección, madurado catorce días|Cooked your way, aged fourteen days', 24800, 1],
      ['Entraña del día|Skirt steak of the day', 'Corte fino, fuego fuerte|Thin cut, hot fire', 21900, 1],
      ['Vacío a las brasas|Embered flank', 'Cocción lenta durante cuatro horas|Four hours of slow cooking', 23400, 1],
      ['Papas rústicas|Rustic potatoes', 'Con piel, romero y ajo|Skin on, with rosemary and garlic', 6200, 2],
      ['Ensalada de rúcula y parmesano|Arugula and parmesan salad', 'Aceto balsámico y nueces|Balsamic and walnuts', 6900, 2],
      ['Provenzal de verduras asadas|Charred vegetable platter', 'Berenjena, pimiento y calabacín|Eggplant, pepper and zucchini', 7400, 2],
      ['Flan casero con dulce de leche|Homemade flan with caramel milk', 'Con crema batida a mano|With hand-whipped cream', 6500, 3],
      ['Vigilante|Cheese and quince plate', 'Queso fresco y dulce de membrillo|Fresh cheese and quince paste', 5800, 3],
      ['Panqueque flameado|Flambéed crêpe', 'Se prende en la mesa, con licor de naranja|Lit at the table, with orange liqueur', 7900, 3],
    ],
    fields: [
      text('fullName', 'Nombre para la reserva|Name for the booking', { minLength: 2, maxLength: 50 }),
      num('guests', 'Cantidad de comensales|Number of diners', 1, 14),
      sel('seating', 'Ubicación|Seating', ['Salón|Dining room', 'Patio|Courtyard', 'Barra|Bar counter']),
      rad('meat', 'Punto de cocción habitual|Usual doneness', ['Jugoso|Rare', 'A punto|Medium', 'Bien cocido|Well done']),
      pat('phone', 'Teléfono de contacto|Contact phone', '^\\+?\\d[\\d ]{7,14}$', 'Entre 8 y 15 dígitos, con o sin +|Between 8 and 15 digits, with or without +'),
    ],
    contact: ['Reserva para grupos|Group booking', 'Opciones sin gluten|Gluten-free options', 'Salón para eventos|Event hall', 'Objeto olvidado|Lost item'],
    faq: [
      ['¿Hay opciones vegetarianas?|Are there vegetarian options?', 'Sí, la provoleta, las verduras asadas y una milanesa de berenjena.|Yes: the provolone, the charred vegetables and an eggplant cutlet.'],
      ['¿Cuánto se demora una mesa?|How long is the wait for a table?', 'Los sábados de noche, cuarenta minutos sin reserva.|On Saturday nights, forty minutes without a reservation.'],
      ['¿Se puede pedir el corte para llevar?|Can I get steaks to go?', 'Sí, lo envolvemos en papel manteca y recomendamos comerlo en veinte minutos.|Yes, wrapped in butcher paper; we suggest eating it within twenty minutes.'],
      ['¿Aceptan perros en el patio?|Are dogs allowed in the courtyard?', 'Sí, con correa y un bowl de agua de cortesía.|Yes, on a leash with a complimentary water bowl.'],
      ['¿Cobran cubierto?|Is there a cover charge?', 'No, el pan de campo y los chimichurris son de la casa.|No, the country bread and chimichurris are on the house.'],
    ],
    posts: [
      ['Por qué descansar el corte|Why the steak must rest', 'Cinco minutos que cambian todo el jugo.|Five minutes that change all the juice.', 'Chef Aurelio Sabatini'],
      ['Leña de quebracho vs. carbón|Quebracho wood versus charcoal', 'Cómo manejamos la brasa en invierno.|How we manage the embers in winter.', 'Marta Lencina'],
      ['Chimichurri de la casa|The house chimichurri', 'Una receta con diez ingredientes y mucha paciencia.|A ten-ingredient recipe and plenty of patience.', 'Chef Aurelio Sabatini'],
    ],
    wiz: {
      title: 'Organizá tu cena|Plan your dinner',
      steps: [
        ['Ocasión|Occasion', [sel('occasion', 'Ocasión|Occasion', ['Cena común|Regular dinner', 'Cumpleaños|Birthday', 'Reunión de trabajo|Business meeting'])]],
        ['Fecha y grupo|Date and party', [date('dinnerDate', 'Día de la cena|Dinner date', 'noPast'), num('partySize', 'Personas|People', 2, 40)]],
        ['Torta y velas|Cake and candles', [text('birthdayName', 'Nombre del cumpleañero|Birthday guest name', { maxLength: 40 })]],
        ['Restricciones|Restrictions', [chk('glutenFree', 'Hay celíacos en el grupo|Celiacs in the group')]],
      ],
      cond: ['occasion', 'birthday', ['birthdayName']],
    },
    dash: { cols: ['Plato|Dish', 'Servidos|Served', 'Servicio|Service date', 'Venta|Sales'], pool: ['Bife de chorizo|Sirloin', 'Entraña|Skirt steak', 'Vacío|Flank', 'Provoleta|Provolone', 'Papas rústicas|Rustic potatoes', 'Flan casero|Homemade flan'], n: [5, 110], m: [16000, 2600000] },
  },
  {
    id: 'biblioteca-hilo-tinta',
    name: 'Biblioteca Municipal Hilo y Tinta|Hilo y Tinta Public Library',
    tag: 'Un carnet, tres mil historias|One card, three thousand stories',
    style: [28, 200, 'serif', 4, 'ornate'],
    cur: ['$', 'COP', 0],
    nouns: ['libro|libros|book|books', 'lector|lectores|reader|readers', 'préstamo|préstamos|loan|loans', 'colección|colecciones|collection|collections'],
    nav: ['Vestíbulo|Lobby', 'Mis préstamos|My loans', 'Confirmar préstamo|Confirm loan', 'Mesa del bibliotecario|Librarian desk', 'Boletín de lectura|Reading bulletin'],
    cats: ['Novela|Fiction', 'Infantil y juvenil|Children and young adult', 'Ciencia y técnica|Science and technology', 'Historia local|Local history'],
    items: [
      ['Cien noches en el río|A Hundred Nights on the River', 'Novela coral sobre un pueblo de balseros|An ensemble novel about a village of ferrymen', 4000, 0],
      ['La cartógrafa de sal|The Salt Cartographer', 'Una mujer dibuja los mapas de un desierto en retroceso|A woman charts a retreating desert', 4000, 0],
      ['Cuentos de la última tranvía|Last Tram Stories', 'Doce relatos que ocurren después de medianoche|Twelve tales set after midnight', 3500, 0],
      ['El gato que contaba nubes|The Cat Who Counted Clouds', 'Álbum ilustrado para primeros lectores|Picture book for first readers', 3000, 1],
      ['Diario de un huerto escolar|A School Garden Diary', 'Un curso entero cuida tomates durante un año|A whole class tends tomatoes for a year', 3000, 1],
      ['Misterio en la torre del reloj|Mystery in the Clock Tower', 'Novela juvenil con pistas escondidas en las páginas|Young adult novel with clues hidden in the pages', 3500, 1],
      ['Cómo funciona un puente|How a Bridge Works', 'Del arco romano a los cables de acero|From Roman arch to steel cable', 4500, 2],
      ['Atlas de los insectos polinizadores|Atlas of Pollinating Insects', 'Cuatrocientas láminas con claves de campo|Four hundred plates with field keys', 5000, 2],
      ['Electricidad sin miedo|Electricity Without Fear', 'Circuitos domésticos explicados con dibujos|Household circuits explained with drawings', 4000, 2],
      ['Crónicas del mercado viejo|Chronicles of the Old Market', 'Cien años de puestos, voces y precios|A hundred years of stalls, voices and prices', 4500, 3],
      ['Cuando se inundó la plaza|When the Square Flooded', 'Testimonios de la crecida de 1958|Accounts of the 1958 flood', 4000, 3],
      ['Calles con nombre de oficio|Streets Named After Trades', 'Por qué hay una calle de los Curtidores|Why there is a Tanners Street', 3500, 3],
    ],
    fields: [
      text('fullName', 'Nombre y apellido|Full name', { minLength: 3, maxLength: 60 }),
      pat('cardNumber', 'Número de carnet|Library card number', '^LB-\\d{6}$', 'Seis dígitos tras LB-, ej. LB-004512|Six digits after LB-, e.g. LB-004512'),
      num('age', 'Edad|Age', 4, 110),
      sel('favoriteShelf', 'Estante preferido|Favorite shelf', ['Novela|Fiction', 'Ciencia|Science', 'Historia|History', 'Infantil|Children']),
      chk('audioLoans', 'Quiero préstamos de audiolibros|I want audiobook loans'),
    ],
    contact: ['Devolver fuera de horario|Late return', 'Libro dañado|Damaged book', 'Sugerir una compra|Suggest a purchase', 'Visita de escuelas|School visits'],
    faq: [
      ['¿Cuántos libros puedo llevar?|How many books can I borrow?', 'Cuatro por quince días, renovables una vez desde tu cuenta.|Four for fifteen days, renewable once from your account.'],
      ['¿Hay multas por atraso?|Are there late fines?', 'No cobramos multa: suspendemos el préstamo tantos días como el atraso.|No fines: we suspend loans for as many days as you were late.'],
      ['¿Puedo reservar un libro prestado?|Can I reserve a borrowed book?', 'Sí, te avisamos por correo apenas vuelve al estante.|Yes, we email you as soon as it is back on the shelf.'],
      ['¿Tienen sala de estudio?|Is there a study room?', 'Dos salas silenciosas con enchufes, sin reserva previa.|Two silent rooms with outlets, no booking needed.'],
      ['¿Quién puede asociarse?|Who may get a library card?', 'Cualquier persona con documento y un comprobante de domicilio.|Anyone with ID and proof of address.'],
    ],
    posts: [
      ['Los cinco libros más pedidos del invierno|Winter\'s five most requested books', 'Ranking con comentarios de las lectoras.|A ranking with readers\' comments.', 'Alicia Montenegro'],
      ['Una tarde de cuentos para madrugadores|A story afternoon for early risers', 'Ciclo de lectura en voz alta los sábados a las 10.|A read-aloud series on Saturdays at 10.', 'Teo Rueda'],
      ['Restaurar un libro de 1902|Restoring a book from 1902', 'El taller de encuadernación cuenta cómo se hizo.|The bindery workshop explains how it was done.', 'Berta Villalobos'],
    ],
    wiz: {
      title: 'Pedí una compra para la colección|Request a collection purchase',
      steps: [
        ['Tipo de pedido|Request type', [rad('requestKind', 'Qué querés sugerir|What you want to suggest', ['Un libro|A book', 'Una revista|A magazine'])]],
        ['Datos básicos|Basics', [text('title', 'Título|Title', { minLength: 2, maxLength: 100 }), num('year', 'Año de edición|Publication year', 1800, 2026)]],
        ['Revista|Magazine', [text('issn', 'ISSN de la revista|Magazine ISSN', { pattern: '^\\d{4}-\\d{3}[\\dX]$', patternHint: { es: 'Formato 1234-567X', en: 'Format 1234-567X' } })]],
        ['Motivo|Reason', [area('why', 'Por qué debería estar en la biblioteca|Why it belongs in the library', 250)]],
      ],
      cond: ['requestKind', 'a-magazine', ['issn']],
    },
    dash: { cols: ['Colección|Collection', 'Préstamos|Loans', 'Fecha|Date', 'Multas condonadas|Waived fees'], pool: ['Novela|Fiction', 'Infantil|Children', 'Ciencia y técnica|Science and technology', 'Historia local|Local history', 'Audiolibros|Audiobooks', 'Revistas|Magazines'], n: [3, 160], m: [0, 40000] },
  },
  {
    id: 'banco-cooperativo-trigal',
    name: 'Banco Cooperativo Trigal|Trigal Cooperative Bank',
    tag: 'Ahorro con cara y apellido|Savings with a face and a surname',
    style: [150, 48, 'sans', 6, 'clean'],
    cur: ['$', 'MXN', 2],
    nouns: ['producto|productos|product|products', 'asociado|asociados|member|members', 'operación|operaciones|transaction|transactions', 'línea|líneas|line|lines'],
    nav: ['Ventanilla|Teller window', 'Mis operaciones|My transactions', 'Autorizar operación|Authorize transaction', 'Tablero de sucursal|Branch board', 'Educación financiera|Financial education'],
    cats: ['Cuentas|Accounts', 'Ahorro a plazo|Term savings', 'Préstamos|Loans', 'Seguros|Insurance'],
    items: [
      ['Cuenta de ahorro básica|Basic savings account', 'Sin costo de mantenimiento y con tarjeta de débito|No maintenance fee, with debit card', 0.01, 0],
      ['Cuenta joven|Youth account', 'Para menores de 25, con tope de gasto diario|For under-25s, with a daily spending cap', 0.01, 0],
      ['Cuenta de nómina|Payroll account', 'Retiros sin comisión en cajeros asociados|Free withdrawals at partner ATMs', 0.01, 0],
      ['Plazo fijo a 90 días|90-day term deposit', 'Tasa fija desde 500 pesos|Fixed rate from 500 pesos', 500, 1],
      ['Plazo fijo a un año|One-year term deposit', 'Renovación automática opcional|Optional automatic renewal', 1000, 1],
      ['Ahorro programado|Scheduled savings', 'Un descuento mensual hacia tu meta|A monthly deduction toward your goal', 200, 1],
      ['Préstamo para taller|Workshop loan', 'Para maquinaria y herramientas de oficio|For machinery and trade tools', 15000, 2],
      ['Crédito de estudios|Study loan', 'Cuotas que arrancan al egresar|Payments that start after graduation', 8000, 2],
      ['Adelanto de cosecha|Harvest advance', 'Capital de trabajo para productores|Working capital for farmers', 25000, 2],
      ['Seguro de hogar|Home insurance', 'Incendio, robo y daños por agua|Fire, theft and water damage', 180, 3],
      ['Seguro de vida simple|Basic life insurance', 'Cobertura mensual sin examen médico|Monthly cover without a medical exam', 95, 3],
      ['Seguro de bici y moto|Bike and scooter insurance', 'Robo total y responsabilidad civil|Total theft and civil liability', 70, 3],
    ],
    fields: [
      text('fullName', 'Nombre y apellido|Full name', { minLength: 3, maxLength: 70 }),
      pat('taxId', 'Clave de identificación fiscal|Tax ID', '^[A-Z]{4}\\d{6}[A-Z0-9]{3}$', 'Cuatro letras, seis dígitos y tres caracteres, ej. LOPA850412H7K|Four letters, six digits and three characters, e.g. LOPA850412H7K'),
      date('birthDate', 'Fecha de nacimiento|Date of birth', 'noFuture'),
      num('monthlyIncome', 'Ingreso mensual aproximado|Approximate monthly income', 0, 500000),
      sel('purpose', 'Para qué querés la cuenta|What the account is for', ['Ahorro personal|Personal savings', 'Cobro de sueldo|Salary deposit', 'Pequeño negocio|Small business']),
    ],
    contact: ['Bloquear una tarjeta|Block a card', 'Disputar un cargo|Dispute a charge', 'Solicitar un préstamo|Apply for a loan', 'Denuncia de fraude|Report fraud'],
    faq: [
      ['¿Cómo me asocio?|How do I become a member?', 'Con identificación, comprobante de domicilio y una aportación inicial simbólica.|With ID, proof of address and a symbolic initial contribution.'],
      ['¿Quién es dueño del banco?|Who owns the bank?', 'Los asociados: cada persona tiene un voto en la asamblea anual.|The members: each person gets one vote at the annual assembly.'],
      ['¿Está garantizado mi dinero?|Is my money insured?', 'Los depósitos están cubiertos por el fondo de protección hasta el tope vigente.|Deposits are covered by the protection fund up to the current cap.'],
      ['¿Cobran por transferir?|Do you charge for transfers?', 'Las transferencias entre asociados son gratuitas; a otros bancos, un cargo fijo.|Transfers between members are free; to other banks, a flat fee.'],
      ['¿Qué hago si pierdo la tarjeta?|What if I lose my card?', 'Bloqueala desde tu cuenta o por teléfono; la reposición llega en cinco días.|Block it from your account or by phone; the replacement arrives in five days.'],
    ],
    posts: [
      ['Fondo de emergencia en tres pasos|An emergency fund in three steps', 'Cuánto guardar y dónde, sin complicaciones.|How much to save and where, without the fuss.', 'Lic. Evelia Cordero'],
      ['Reconocer un correo trampa|Spotting a phishing email', 'Cinco señales que nunca fallan.|Five signs that never fail.', 'Ing. Rubén Sarmiento'],
      ['Asamblea anual: lo que se votó|Annual assembly: what was voted', 'Resumen de las cuatro decisiones del año.|A summary of the year\'s four decisions.', 'Consejo de vigilancia'],
    ],
    wiz: {
      title: 'Simulá tu préstamo|Simulate your loan',
      steps: [
        ['Destino|Purpose', [sel('loanUse', 'Para qué es el préstamo|What the loan is for', ['Taller o negocio|Workshop or business', 'Estudios|Studies', 'Cosecha|Harvest'])]],
        ['Monto y plazo|Amount and term', [num('amount', 'Monto solicitado|Amount requested', 1000, 150000), num('months', 'Plazo en meses|Term in months', 3, 60)]],
        ['Cosecha|Harvest', [text('crop', 'Cultivo principal|Main crop', { minLength: 3, maxLength: 40 })]],
        ['Garantías|Guarantees', [chk('guarantor', 'Cuento con un aval|I have a guarantor')]],
      ],
      cond: ['loanUse', 'harvest', ['crop']],
    },
    dash: { cols: ['Producto|Product', 'Operaciones|Transactions', 'Fecha de cierre|Closing date', 'Volumen|Volume'], pool: ['Cuenta básica|Basic account', 'Plazo fijo|Term deposit', 'Ahorro programado|Scheduled savings', 'Préstamo de taller|Workshop loan', 'Seguro de hogar|Home insurance', 'Adelanto de cosecha|Harvest advance'], n: [5, 300], m: [2000, 900000] },
  },
  {
    id: 'escuela-arroyo-claro',
    name: 'Escuela Primaria Arroyo Claro|Arroyo Claro Elementary School',
    tag: 'Aprender donde el patio es el aula|Learning where the playground is the classroom',
    style: [48, 200, 'rounded', 12, 'playful'],
    cur: ['$', 'UYU', 0],
    nouns: ['taller|talleres|workshop|workshops', 'familia|familias|family|families', 'inscripción|inscripciones|enrollment|enrollments', 'ciclo|ciclos|stage|stages'],
    nav: ['Portón|School gate', 'Mis talleres|My workshops', 'Confirmar inscripción|Confirm enrollment', 'Tablero de dirección|Principal board', 'Cuaderno de comunicados|Notice notebook'],
    cats: ['Arte y música|Art and music', 'Ciencias|Science', 'Deportes|Sports', 'Apoyo escolar|Tutoring'],
    items: [
      ['Taller de murga infantil|Children\'s street-band workshop', 'Percusión, coro y vestuario con material reciclado|Percussion, chorus and costumes from recycled material', 700, 0],
      ['Taller de cerámica|Pottery workshop', 'Pellizco, rollos y una pieza para llevar a casa|Pinch pots, coils and a piece to take home', 650, 0],
      ['Coro de la escuela|School choir', 'Ensayo los martes, función en diciembre|Tuesday rehearsals, a show in December', 400, 0],
      ['Huerta y compost|Garden and compost', 'Sembrar, regar y medir el crecimiento|Sow, water and measure growth', 500, 1],
      ['Robótica con cartón|Cardboard robotics', 'Motores simples, pilas y mucha cinta|Simple motors, batteries and lots of tape', 800, 1],
      ['Astronomía de patio|Playground astronomy', 'Una noche con telescopios prestados|A night with borrowed telescopes', 450, 1],
      ['Handball mixto|Mixed handball', 'Equipos por edad, sin eliminaciones|Teams by age, no knockouts', 500, 2],
      ['Natación en el club vecino|Swimming at the neighbor club', 'Traslado en minibús y vestuario cuidado|Minibus transfer and supervised changing rooms', 900, 2],
      ['Ajedrez de recreo|Recess chess', 'Torneo relámpago cada viernes|A blitz tournament every Friday', 300, 2],
      ['Apoyo en lectura|Reading support', 'Grupos de cuatro con una maestra|Groups of four with a teacher', 600, 3],
      ['Apoyo en matemática|Math support', 'Juegos y problemas con material concreto|Games and problems with hands-on material', 600, 3],
      ['Escuela de familias|Family school', 'Charlas mensuales sobre rutinas y pantallas|Monthly talks on routines and screens', 0.5, 3],
    ],
    fields: [
      text('studentName', 'Nombre del alumno|Student name', { minLength: 2, maxLength: 60 }),
      num('grade', 'Grado|Grade', 1, 6),
      pat('studentId', 'Matrícula del alumno|Student ID', '^ESC-\\d{4}-[A-C]$', 'Formato ESC-2024-B: año y sección A, B o C|Format ESC-2024-B: year and section A, B or C'),
      sel('shift', 'Turno|Shift', ['Mañana|Morning', 'Tarde|Afternoon']),
      text('guardianName', 'Nombre del adulto responsable|Guardian name', { minLength: 3, maxLength: 60 }),
      chk('photoConsent', 'Autorizo el uso de fotos en el blog escolar|I allow photos on the school blog'),
    ],
    contact: ['Inasistencia de un alumno|Student absence', 'Pedir una entrevista|Request a meeting', 'Becas y comedor|Scholarships and lunch', 'Sugerencias a la dirección|Suggestions for the principal'],
    faq: [
      ['¿Cuál es el horario de entrada?|What is the start time?', 'A las 8:00 en el turno mañana y a las 13:00 en el turno tarde.|At 8:00 in the morning shift and 13:00 in the afternoon shift.'],
      ['¿Hay comedor?|Is there a lunchroom?', 'Sí, con menú del día y opción vegetariana, con cupos para beca.|Yes, with a daily menu and a vegetarian option, with scholarship places.'],
      ['¿Cómo aviso una ausencia?|How do I report an absence?', 'Desde el formulario de contacto antes de las 8:30.|Through the contact form before 8:30.'],
      ['¿Qué pasa si llueve en el recreo?|What if it rains at recess?', 'Los chicos juegan en el salón de usos múltiples con juegos de mesa.|Children play in the multipurpose hall with board games.'],
      ['¿Los talleres se pagan aparte?|Are workshops paid separately?', 'Tienen un aporte simbólico, y nadie queda afuera por no poder pagarlo.|They have a symbolic fee, and nobody is left out for not paying.'],
    ],
    posts: [
      ['Murga en el patio|Street band in the schoolyard', 'Los ensayos que hicieron temblar los vidrios.|The rehearsals that rattled the windows.', 'Maestra Luciana Prieto'],
      ['Nuestra primera cosecha de lechugas|Our first lettuce harvest', 'Cuarto grado cuenta cómo cuidó la huerta.|Fourth grade tells how they tended the garden.', 'Cuarto B'],
      ['Pantallas: un acuerdo en casa|Screens: a household agreement', 'Cuatro reglas que familias de la escuela probaron.|Four rules tried by school families.', 'Psic. Valentina Rey'],
    ],
    wiz: {
      title: 'Inscribí a un alumno|Enroll a student',
      steps: [
        ['Tipo de ingreso|Entry type', [rad('entry', 'Tipo de ingreso|Entry type', ['Alumno nuevo|New student', 'Pase de otra escuela|Transfer from another school'])]],
        ['Edad y fecha|Age and date', [num('childAge', 'Edad en años|Age in years', 5, 13), date('startDate', 'Fecha de ingreso|Start date', 'noPast')]],
        ['Escuela anterior|Previous school', [text('previousSchool', 'Escuela de procedencia|Previous school', { minLength: 3, maxLength: 80 })]],
        ['Salud|Health', [area('health', 'Alergias o cuidados especiales|Allergies or special care', 250)]],
      ],
      cond: ['entry', 'transfer-from-another-school', ['previousSchool']],
    },
    dash: { cols: ['Taller|Workshop', 'Inscriptos|Enrolled', 'Fecha de inicio|Start date', 'Aportes cobrados|Fees collected'], pool: ['Murga infantil|Children\'s street band', 'Cerámica|Pottery', 'Huerta|Garden', 'Robótica con cartón|Cardboard robotics', 'Balonmano|Handball', 'Apoyo en lectura|Reading support'], n: [4, 32], m: [0, 20000] },
  },
  {
    id: 'veterinaria-cola-feliz',
    name: 'Veterinaria Cola Feliz|Happy Tail Vet',
    tag: 'Cuidamos a quien te espera en la puerta|We look after whoever waits for you at the door',
    style: [168, 36, 'rounded', 14, 'playful'],
    cur: ['$', 'USD', 2],
    nouns: ['servicio|servicios|service|services', 'tutor|tutores|owner|owners', 'consulta|consultas|visit|visits', 'área|áreas|area|areas'],
    nav: ['Recepción|Front desk', 'Mi lista de visitas|My visit list', 'Confirmar visita|Confirm visit', 'Tablero de consultorios|Exam room board', 'Diario de mascotas|Pet diary'],
    cats: ['Consultas|Check-ups', 'Vacunas y prevención|Vaccines and prevention', 'Peluquería|Grooming', 'Alimentos y accesorios|Food and gear'],
    items: [
      ['Consulta clínica|Clinical visit', 'Revisión general con balanza y otoscopio|General exam with scale and otoscope', 25, 0],
      ['Control de cachorro|Puppy check', 'Desparasitación y primeras pautas de crianza|Deworming and first training guidance', 30, 0],
      ['Chequeo senior|Senior check', 'Sangre, corazón y articulaciones desde los siete años|Blood, heart and joints from age seven', 55, 0],
      ['Vacuna quíntuple|Five-in-one vaccine', 'Moquillo, parvovirus y tres más|Distemper, parvovirus and three more', 18, 1],
      ['Antirrábica anual|Annual rabies shot', 'Libreta sanitaria al día|Health booklet kept current', 12, 1],
      ['Pipeta antipulgas|Flea spot-on', 'Un mes de protección, por peso del animal|One month of protection, by animal weight', 14, 1],
      ['Baño y corte de raza|Breed bath and cut', 'Secado sin estrés y corte según raza|Stress-free drying and a breed-appropriate cut', 28, 2],
      ['Baño para gatos|Cat bath', 'Con dos personas y toalla tibia|With two handlers and a warm towel', 24, 2],
      ['Corte de uñas|Nail trim', 'Sin turno, en cinco minutos|Walk-in, five minutes', 6, 2],
      ['Alimento hipoalergénico 3 kg|Hypoallergenic food 3 kg', 'Proteína hidrolizada para pieles sensibles|Hydrolyzed protein for sensitive skin', 32, 3],
      ['Rascador de sisal|Sisal scratching post', 'Altura de 80 cm con base ancha|80 cm tall with a wide base', 38, 3],
      ['Arnés antitirones|No-pull harness', 'Talles XS a XL, ajuste en cuatro puntos|Sizes XS to XL, four-point fit', 21, 3],
    ],
    fields: [
      text('ownerName', 'Nombre del tutor|Owner name', { minLength: 3, maxLength: 60 }),
      text('petName', 'Nombre de la mascota|Pet name', { minLength: 1, maxLength: 30 }),
      sel('species', 'Especie|Species', ['Perro|Dog', 'Gato|Cat', 'Ave|Bird', 'Conejo|Rabbit']),
      num('petAge', 'Edad de la mascota en años|Pet age in years', 0, 30),
      pat('microchip', 'Número de microchip|Microchip number', '^\\d{15}$', 'Quince dígitos sin espacios|Fifteen digits with no spaces', false),
    ],
    contact: ['Urgencia fuera de horario|After-hours emergency', 'Resultados de laboratorio|Lab results', 'Adopciones|Adoptions', 'Facturación|Billing'],
    faq: [
      ['¿Atienden urgencias de noche?|Do you handle night emergencies?', 'Tenemos guardia telefónica y derivamos a un hospital de 24 horas aliado.|We have a phone on-call service and refer to an allied 24-hour hospital.'],
      ['¿Atienden animales exóticos?|Do you treat exotic animals?', 'Aves y conejos sí; reptiles los derivamos a una colega.|Birds and rabbits yes; reptiles we refer to a colleague.'],
      ['¿Qué vacunas necesita un cachorro?|Which vaccines does a puppy need?', 'Tres dosis desde las seis semanas, y la antirrábica a los cuatro meses.|Three doses from six weeks, and rabies at four months.'],
      ['¿Puedo esperar con mi gato?|Can I wait with my cat?', 'Hay una sala felina separada, sin perros a la vista.|There is a separate feline room with no dogs in sight.'],
      ['¿Hacen visitas a domicilio?|Do you make home visits?', 'Sí, dentro de diez kilómetros y con turno previo.|Yes, within ten kilometers and by appointment.'],
    ],
    posts: [
      ['Pulgas: el ciclo completo|Fleas: the full cycle', 'Por qué tratar solo al animal no alcanza.|Why treating only the animal is not enough.', 'Dra. Lucía Barrientos'],
      ['Gatos que esconden el dolor|Cats that hide pain', 'Cambios chicos que avisan que algo anda mal.|Small changes that signal something is wrong.', 'Dr. Iván Cuevas'],
      ['Primer día con un cachorro|A puppy\'s first day home', 'Qué comprar y qué dejar para después.|What to buy and what can wait.', 'Dra. Lucía Barrientos'],
    ],
    wiz: {
      title: 'Prepará la primera visita|Prepare the first visit',
      steps: [
        ['Mascota|Pet', [rad('petKind', 'Tipo de mascota|Pet type', ['Cachorro o gatito|Puppy or kitten', 'Adulto o senior|Adult or senior'])]],
        ['Fecha y peso|Date and weight', [date('visitDate', 'Día de la visita|Visit date', 'noPast'), num('petWeight', 'Peso aproximado en kilos|Approximate weight in kilos', 1, 80)]],
        ['Antecedentes|History', [area('medicalHistory', 'Enfermedades o medicación actual|Illnesses or current medication', 300)]],
        ['Confirmación|Confirmation', [chk('reminder', 'Recordarme las vacunas por correo|Remind me of vaccines by email')]],
      ],
      cond: ['petKind', 'adult-or-senior', ['medicalHistory']],
    },
    dash: { cols: ['Servicio|Service', 'Animales atendidos|Animals seen', 'Fecha|Date', 'Facturado|Billed'], pool: ['Consulta clínica|Clinical visit', 'Vacunación|Vaccination', 'Peluquería|Grooming', 'Cirugía menor|Minor surgery', 'Control de cachorro|Puppy check', 'Venta de alimento|Food sales'], n: [2, 35], m: [60, 1800] },
  },
  {
    id: 'inmobiliaria-umbral',
    name: 'Inmobiliaria Umbral|Threshold Realty',
    tag: 'La puerta correcta, sin apuro|The right door, without the rush',
    style: [222, 44, 'sans', 8, 'clean'],
    cur: ['$', 'USD', 0],
    nouns: ['propiedad|propiedades|property|properties', 'cliente|clientes|client|clients', 'visita|visitas|viewing|viewings', 'zona|zonas|area|areas'],
    nav: ['Escaparate|Showcase', 'Mis favoritas|My favorites', 'Coordinar visita|Schedule viewing', 'Tablero de agentes|Agent dashboard', 'Guía del barrio|Neighborhood guide'],
    cats: ['Departamentos|Apartments', 'Casas|Houses', 'Locales y oficinas|Shops and offices', 'Terrenos|Land plots'],
    items: [
      ['Monoambiente con balcón|Studio with balcony', 'Cuarto piso al frente, 32 m²|Fourth floor, front-facing, 32 m²', 74000, 0],
      ['Dos ambientes luminoso|Bright one-bedroom', 'Cocina separada y ventanas al este|Separate kitchen and east-facing windows', 98000, 0],
      ['Tres ambientes con cochera|Two-bedroom with garage', 'Edificio de 2008 con amenities|2008 building with amenities', 145000, 0],
      ['Casa con jardín|House with garden', 'Tres dormitorios y parrilla de ladrillo|Three bedrooms and a brick barbecue', 190000, 1],
      ['Casa tipo PH|Ground-floor townhouse', 'Patio propio y sin expensas|Private patio and no fees', 125000, 1],
      ['Casa de chacra|Farmhouse', 'Media hectárea con galpón y pozo|Half a hectare with a shed and well', 210000, 1],
      ['Local sobre avenida|Avenue storefront', 'Vidriera de 6 metros y depósito|Six-meter window and storage room', 160000, 2],
      ['Oficina en piso alto|High-floor office', 'Dos baños, aire frío y calor|Two bathrooms, heating and cooling', 88000, 2],
      ['Galpón con oficina|Warehouse with office', 'Portón alto para camiones|High door for trucks', 240000, 2],
      ['Lote en barrio cerrado|Lot in a gated community', '600 m² con servicios en la puerta|600 m² with utilities at the gate', 54000, 3],
      ['Terreno esquina|Corner plot', 'Escritura lista y frente a plaza|Deed ready and facing a square', 67000, 3],
      ['Fracción rural|Rural parcel', 'Cinco hectáreas con camino consorciado|Five hectares with a shared road', 38000, 3],
    ],
    fields: [
      text('fullName', 'Nombre y apellido|Full name', { minLength: 3, maxLength: 70 }),
      pat('phone', 'Teléfono|Phone', '^\\+?\\d[\\d ]{7,14}$', 'Entre 8 y 15 dígitos, con o sin +|Between 8 and 15 digits, with or without +'),
      sel('operation', 'Operación|Operation', ['Comprar|Buy', 'Alquilar|Rent', 'Vender|Sell']),
      num('budgetMax', 'Presupuesto máximo en dólares|Maximum budget in dollars', 1000, 1000000),
      sel('rooms', 'Ambientes mínimos|Minimum rooms', ['Uno|One', 'Dos|Two', 'Tres o más|Three or more'], false),
    ],
    contact: ['Tasar mi propiedad|Appraise my property', 'Documentación para alquilar|Rental paperwork', 'Reclamo por expensas|Fee dispute', 'Trabajar con nosotros|Work with us'],
    faq: [
      ['¿Cuál es la comisión?|What is your commission?', 'Cuatro por ciento por lado en ventas y un mes de alquiler en locaciones.|Four percent per side on sales and one month\'s rent on rentals.'],
      ['¿Qué garantía piden para alquilar?|What guarantee do you ask for rentals?', 'Un seguro de caución o un garante con propiedad.|A surety bond or a guarantor with property.'],
      ['¿Hacen visitas de fin de semana?|Do you show on weekends?', 'Sí, los sábados de 10 a 14 con turno previo.|Yes, Saturdays 10 to 2 by appointment.'],
      ['¿Cuánto tarda una escritura?|How long does a deed take?', 'Entre treinta y sesenta días desde la reserva.|Thirty to sixty days from the deposit.'],
      ['¿Puedo ver planos?|Can I see floor plans?', 'Cada ficha trae el plano y las medidas reales relevadas.|Each listing includes the plan and the surveyed measurements.'],
    ],
    posts: [
      ['Qué mirar en una visita|What to look at in a viewing', 'Diez cosas que las fotos no muestran.|Ten things photos do not show.', 'Agente Flavia Nogueira'],
      ['Alquilar con mascotas|Renting with pets', 'Cómo negociar sin perder el departamento ideal.|How to negotiate without losing the ideal apartment.', 'Agente Sergio Maldonado'],
      ['El barrio de la semana|Neighborhood of the week', 'Plazas, ferias y el café que abre a las seis.|Squares, markets and the café that opens at six.', 'Agente Flavia Nogueira'],
    ],
    wiz: {
      title: 'Contanos qué buscás|Tell us what you are looking for',
      steps: [
        ['Operación|Operation', [rad('wantTo', 'Qué querés hacer|What you want to do', ['Comprar|Buy', 'Alquilar|Rent'])]],
        ['Presupuesto y fecha|Budget and date', [num('maxPrice', 'Presupuesto máximo|Maximum budget', 300, 600000), date('moveBy', 'Mudanza antes de|Move before', 'noPast')]],
        ['Alquiler|Rental', [num('rentMonths', 'Meses de contrato deseados|Desired lease months', 6, 60)]],
        ['Preferencias|Preferences', [area('musts', 'Lo que no puede faltar|Must-haves', 250)]],
      ],
      cond: ['wantTo', 'rent', ['rentMonths']],
    },
    dash: { cols: ['Propiedad|Property', 'Visitas|Viewings', 'Fecha de publicación|Listing date', 'Precio de lista|List price'], pool: ['Monoambiente|Studio', 'Dos ambientes|One-bedroom', 'Casa con jardín|House with garden', 'Local sobre avenida|Avenue storefront', 'Lote en barrio cerrado|Gated lot', 'Fracción rural|Rural parcel'], n: [0, 25], m: [38000, 240000] },
  },
  {
    id: 'panaderia-masa-madre',
    name: 'Panadería Masa Madre y Hermanos|Mother Dough & Brothers Bakery',
    tag: 'Fermentación larga, mañanas cortas|Long fermentation, short mornings',
    style: [36, 20, 'rounded', 12, 'playful'],
    cur: ['€', 'EUR', 2],
    nouns: ['pan|panes|loaf|loaves', 'cliente|clientes|customer|customers', 'encargo|encargos|order|orders', 'horneada|horneadas|bake|bakes'],
    nav: ['Mostrador|Counter', 'Mi bolsa de pan|My bread bag', 'Reservar horneada|Reserve a bake', 'Libreta del maestro panadero|Head baker\'s ledger', 'Diario de fermentos|Starter journal'],
    cats: ['Panes de masa madre|Sourdough loaves', 'Facturas y bollería|Pastries and buns', 'Salados|Savory bakes', 'Tortas y celebraciones|Cakes and celebrations'],
    items: [
      ['Pan de campo 1 kg|Country loaf 1 kg', 'Corteza gruesa y miga abierta|Thick crust and open crumb', 5.2, 0],
      ['Pan de centeno y semillas|Rye and seed loaf', 'Dieciocho horas de fermentación|Eighteen hours of fermentation', 5.8, 0],
      ['Baguette de molde largo|Long-mold baguette', 'Se vende hasta que se acaba|On sale until it runs out', 1.8, 0],
      ['Medialunas de manteca|Butter croissants', 'Veinte capas y almíbar tibio|Twenty layers and warm syrup', 1.2, 1],
      ['Palmeras|Palmiers', 'Crocantes y caramelizadas|Crisp and caramelized', 1.4, 1],
      ['Rol de canela|Cinnamon roll', 'Glaseado de queso crema|Cream-cheese glaze', 2.5, 1],
      ['Fugazzeta rellena|Stuffed onion focaccia', 'Cebolla dulce y queso a la plancha|Sweet onion and griddled cheese', 4.4, 2],
      ['Empanada gallega de atún|Galician tuna pie', 'Masa de aceite de oliva|Olive-oil dough', 3.9, 2],
      ['Pan de queso|Cheese bread', 'Sin gluten, de almidón de mandioca|Gluten-free, made with cassava starch', 2.2, 2],
      ['Torta de chocolate y naranja|Chocolate orange cake', 'Seis porciones, sin crema|Six slices, no frosting', 18, 3],
      ['Rosca de Pascua|Easter bread ring', 'Trenzada con huevo y azahar|Braided with egg and orange blossom', 12, 3],
      ['Caja de mini tartas|Mini tart box', 'Doce piezas de frutas de estación|Twelve pieces with seasonal fruit', 14, 3],
    ],
    fields: [
      text('fullName', 'Nombre para el encargo|Name for the order', { minLength: 2, maxLength: 50 }),
      sel('pickup', 'Franja de retiro|Pick-up window', ['7 a 9 h|7 to 9 am', '9 a 12 h|9 am to noon', '16 a 19 h|4 to 7 pm']),
      num('loaves', 'Panes por semana|Loaves per week', 1, 30),
      chk('glutenFree', 'Necesito opciones sin gluten|I need gluten-free options'),
      pat('subscription', 'Código de suscripción|Subscription code', '^PAN-[A-Z]{2}\\d{3}$', 'PAN-, dos letras y tres dígitos, ej. PAN-MR042|PAN-, two letters and three digits, e.g. PAN-MR042', false),
    ],
    contact: ['Encargo para evento|Event order', 'Alergias e ingredientes|Allergens and ingredients', 'Cursos de panificación|Baking classes', 'Reclamo de un pedido|Order complaint'],
    faq: [
      ['¿A qué hora sale el pan?|When does the bread come out?', 'Las primeras hogazas están a las 7:30 y las últimas a las 17.|The first loaves are out at 7:30 and the last at 5 pm.'],
      ['¿Cómo conservo la masa madre?|How do I keep the sourdough?', 'Fuera de la heladera, envuelto en tela; se congela rebanado.|Out of the fridge, wrapped in cloth; freeze it sliced.'],
      ['¿Venden masa madre?|Do you sell starter?', 'Regalamos un frasquito a quien lo pida, con una hoja de cuidados.|We give a small jar to whoever asks, with a care sheet.'],
      ['¿Hacen tortas por encargo?|Do you do custom cakes?', 'Con tres días de anticipación y seña del treinta por ciento.|With three days\' notice and a thirty-percent deposit.'],
      ['¿Hay productos veganos?|Are there vegan products?', 'El pan de campo, el centeno y el pan de aceitunas lo son.|The country loaf, the rye and the olive bread are.'],
    ],
    posts: [
      ['Cómo despertar un fermento|How to wake up a starter', 'Siete días de agua, harina y paciencia.|Seven days of water, flour and patience.', 'Santiago Roca'],
      ['El secreto de la miga abierta|The secret of an open crumb', 'Hidratación, pliegues y horno muy caliente.|Hydration, folds and a very hot oven.', 'Santiago Roca'],
      ['Domingos de medialunas|Croissant Sundays', 'Una crónica de la fila de las ocho de la mañana.|A chronicle of the eight a.m. line.', 'Julia Roca'],
    ],
    wiz: {
      title: 'Reservá tu horneada|Reserve your bake',
      steps: [
        ['Ocasión|Occasion', [rad('forWhat', 'Para qué es el encargo|What the order is for', ['Uso diario|Everyday use', 'Una celebración|A celebration'])]],
        ['Cantidad y día|Amount and day', [num('portions', 'Porciones|Portions', 2, 100), date('needDate', 'Día de retiro|Pick-up day', 'noPast')]],
        ['Celebración|Celebration', [text('message', 'Mensaje para la torta|Cake message', { maxLength: 40 })]],
        ['Sabores|Flavors', [chk('noNuts', 'Sin frutos secos|No nuts')]],
      ],
      cond: ['forWhat', 'a-celebration', ['message']],
    },
    dash: { cols: ['Producto|Product', 'Unidades horneadas|Units baked', 'Horneada|Bake date', 'Ventas|Sales'], pool: ['Pan de campo|Country loaf', 'Centeno y semillas|Rye and seeds', 'Medialunas|Croissants', 'Fugazzeta|Focaccia', 'Rosca de Pascua|Easter ring', 'Mini tartas|Mini tarts'], n: [12, 260], m: [20, 900] },
  },
  {
    id: 'taller-mecanico-cuarta-marcha',
    name: 'Taller Cuarta Marcha|Fourth Gear Garage',
    tag: 'Diagnóstico honesto antes del presupuesto|Honest diagnosis before the quote',
    style: [0, 55, 'mono', 3, 'tech'],
    cur: ['$', 'USD', 2],
    nouns: ['servicio|servicios|service|services', 'conductor|conductores|driver|drivers', 'orden de trabajo|órdenes de trabajo|work order|work orders', 'sistema|sistemas|system|systems'],
    nav: ['Fosa|Pit bay', 'Mi orden|My work order', 'Aprobar presupuesto|Approve quote', 'Tablero de boxes|Bay board', 'Bitácora del mecánico|Mechanic\'s log'],
    cats: ['Mantenimiento|Maintenance', 'Frenos y suspensión|Brakes and suspension', 'Motor y encendido|Engine and ignition', 'Cubiertas y alineación|Tires and alignment'],
    items: [
      ['Cambio de aceite y filtro|Oil and filter change', 'Aceite sintético y revisión de niveles|Synthetic oil and fluid check', 65, 0],
      ['Service de 10.000 km|10,000 km service', 'Veinte puntos de control con informe|Twenty check points with a report', 120, 0],
      ['Cambio de filtro de aire|Air filter change', 'Se muestra el viejo antes de tirarlo|The old one is shown before it is thrown away', 28, 0],
      ['Pastillas de freno delanteras|Front brake pads', 'Incluye rectificado de discos|Includes disc resurfacing', 95, 1],
      ['Amortiguadores x2|Shock absorbers x2', 'Par delantero con garantía de un año|Front pair with one-year warranty', 210, 1],
      ['Cambio de líquido de frenos|Brake fluid flush', 'Purgado completo de las cuatro ruedas|Full bleed of all four wheels', 55, 1],
      ['Diagnóstico por escáner|Scanner diagnosis', 'Lectura de códigos de falla del tablero|Reading of dashboard fault codes', 40, 2],
      ['Cambio de bujías|Spark plug change', 'Juego de cuatro, con apriete calibrado|Set of four with calibrated torque', 80, 2],
      ['Correa de distribución|Timing belt', 'Kit completo con tensor y bomba|Full kit with tensioner and pump', 340, 2],
      ['Alineación y balanceo|Alignment and balancing', 'Láser en cuatro ruedas|Four-wheel laser', 60, 3],
      ['Rotación de cubiertas|Tire rotation', 'Para un desgaste parejo|For even wear', 25, 3],
      ['Reparación de pinchazo|Puncture repair', 'Parche vulcanizado, sin cambio de cubierta|Vulcanized patch, tire not replaced', 14, 3],
    ],
    fields: [
      text('driverName', 'Nombre del conductor|Driver name', { minLength: 3, maxLength: 60 }),
      pat('plate', 'Patente del vehículo|License plate', '^[A-Z]{2}\\d{3}[A-Z]{2}$', 'Formato AB123CD: dos letras, tres dígitos, dos letras|Format AB123CD: two letters, three digits, two letters'),
      num('mileage', 'Kilometraje actual|Current mileage', 0, 600000),
      sel('fuel', 'Combustible|Fuel', ['Nafta|Gasoline', 'Gasoil|Diesel', 'GNC|CNG', 'Eléctrico|Electric']),
      num('modelYear', 'Año del vehículo|Model year', 1985, 2026),
    ],
    contact: ['Presupuesto por foto|Quote from a photo', 'Garantía de un trabajo|Work warranty', 'Retirar mi vehículo|Collect my vehicle', 'Reclamo|Complaint'],
    faq: [
      ['¿Cuánto cuesta el diagnóstico?|How much is a diagnosis?', 'Quince dólares, que se descuentan si hacés la reparación con nosotros.|Fifteen dollars, deducted if you do the repair with us.'],
      ['¿Me devuelven las piezas cambiadas?|Do I get the replaced parts back?', 'Siempre, en una bolsa rotulada con tu patente.|Always, in a bag labeled with your plate.'],
      ['¿Trabajan con vehículos eléctricos?|Do you work on electric vehicles?', 'Solo frenos, suspensión y cubiertas; la batería la derivamos.|Only brakes, suspension and tires; we refer out the battery.'],
      ['¿Hay auto de cortesía?|Is there a courtesy car?', 'Una unidad, para trabajos de más de un día.|One unit, for jobs lasting more than a day.'],
      ['¿Qué garantía dan?|What warranty do you offer?', 'Noventa días en mano de obra y la del fabricante en repuestos.|Ninety days on labor and the maker\'s warranty on parts.'],
    ],
    posts: [
      ['Luces del tablero: cuáles asustan|Dashboard lights: which ones matter', 'Un semáforo para decidir si seguís o frenás.|A traffic light for deciding whether to go on or stop.', 'Mecánico Nelson Duarte'],
      ['Frenos que chillan|Squealing brakes', 'Cuatro causas, de la inocente a la grave.|Four causes, from harmless to serious.', 'Mecánico Nelson Duarte'],
      ['Cuándo cambiar el aceite de verdad|When to really change the oil', 'El kilometraje del manual y el uso que vos le das.|The manual\'s mileage versus how you actually drive.', 'Ing. Carla Beltrán'],
    ],
    wiz: {
      title: 'Pedí tu presupuesto|Request your quote',
      steps: [
        ['Tipo de problema|Problem type', [sel('problem', 'Qué le pasa al vehículo|What is wrong with the vehicle', ['Ruido extraño|Strange noise', 'Luz en el tablero|Dashboard light', 'Service de rutina|Routine service'])]],
        ['Fecha y uso|Date and use', [date('dropOff', 'Día para dejarlo|Drop-off day', 'noPast'), num('dailyKm', 'Kilómetros por día|Kilometers per day', 0, 500)]],
        ['Ruido|Noise', [area('noiseWhen', 'Cuándo se escucha el ruido|When the noise happens', 250)]],
        ['Contacto|Contact', [chk('callBack', 'Llamarme antes de cualquier trabajo extra|Call me before any extra work', true)]],
      ],
      cond: ['problem', 'strange-noise', ['noiseWhen']],
    },
    dash: { cols: ['Servicio|Service', 'Vehículos ingresados|Vehicles in', 'Ingreso|Check-in date', 'Facturado|Billed'], pool: ['Cambio de aceite|Oil change', 'Pastillas de freno|Brake pads', 'Correa de distribución|Timing belt', 'Alineación|Alignment', 'Diagnóstico escáner|Scanner diagnosis', 'Amortiguadores|Shock absorbers'], n: [1, 18], m: [30, 2400] },
  },
  {
    id: 'floreria-petalo-azul',
    name: 'Floristería Pétalo Azul|Blue Petal Florist',
    tag: 'Flores cortadas esta mañana|Flowers cut this morning',
    style: [320, 140, 'rounded', 14, 'playful'],
    cur: ['£', 'GBP', 2],
    nouns: ['arreglo|arreglos|bouquet|bouquets', 'cliente|clientes|customer|customers', 'encargo|encargos|order|orders', 'ocasión|ocasiones|occasion|occasions'],
    nav: ['Vidriera|Shop window', 'Mi ramo|My bouquet', 'Pedir y enviar|Order and deliver', 'Tablero del invernadero|Greenhouse board', 'Diario de estación|Seasonal diary'],
    cats: ['Ramos|Bouquets', 'Plantas de interior|Houseplants', 'Eventos y bodas|Events and weddings', 'Duelo y recuerdo|Remembrance'],
    items: [
      ['Ramo de peonías|Peony bouquet', 'Solo en primavera, con hojas del jardín|Spring only, with garden foliage', 38, 0],
      ['Girasoles rústicos|Rustic sunflowers', 'Siete tallos largos en papel kraft|Seven long stems in kraft paper', 24, 0],
      ['Tulipanes en maceta de barro|Tulips in a clay pot', 'Bulbos para ver abrirse en la mesa|Bulbs to watch opening on the table', 22, 0],
      ['Monstera joven|Young monstera', 'Maceta de 17 cm, luz indirecta|17 cm pot, indirect light', 26, 1],
      ['Suculentas en terrario|Succulent terrarium', 'Cinco especies y grava volcánica|Five species and volcanic gravel', 29, 1],
      ['Helecho colgante|Hanging fern', 'Le gusta la humedad del baño|Loves bathroom humidity', 18, 1],
      ['Ramo de novia silvestre|Wildflower bridal bouquet', 'Prueba previa de una semana|One-week trial beforehand', 95, 2],
      ['Centro de mesa bajo|Low table centerpiece', 'Para mesas de ocho personas|For tables of eight', 42, 2],
      ['Arco floral por metro|Floral arch per meter', 'Estructura y flores incluidas|Structure and flowers included', 70, 2],
      ['Corona de olivo y rosas blancas|Olive and white rose wreath', 'Con cinta y tarjeta personalizada|With ribbon and personal card', 85, 3],
      ['Planta de recuerdo|Memorial plant', 'Un arce joven para plantar en el jardín|A young maple to plant in the garden', 48, 3],
      ['Ramo discreto de lirios|Quiet lily bouquet', 'Sin fragancia fuerte|Lightly scented', 32, 3],
    ],
    fields: [
      text('fullName', 'Tu nombre|Your name', { minLength: 2, maxLength: 50 }),
      text('recipient', 'Nombre de quien recibe|Recipient name', { minLength: 2, maxLength: 50 }),
      pat('postcode', 'Código postal de entrega|Delivery postcode', '^[A-Z]{1,2}\\d[A-Z\\d]? ?\\d[A-Z]{2}$', 'Formato británico, ej. SW1A 1AA|UK format, e.g. SW1A 1AA'),
      sel('occasion', 'Ocasión|Occasion', ['Cumpleaños|Birthday', 'Aniversario|Anniversary', 'Pésame|Condolence', 'Sin motivo|Just because']),
      area('cardMessage', 'Mensaje de la tarjeta|Card message', 160),
    ],
    contact: ['Cambiar la dirección de entrega|Change delivery address', 'Flor marchita al llegar|Wilted on arrival', 'Presupuesto de boda|Wedding quote', 'Suscripción de flores|Flower subscription'],
    faq: [
      ['¿Entregan el mismo día?|Do you deliver the same day?', 'Sí, para pedidos hechos antes de las 13 en un radio de ocho kilómetros.|Yes, for orders before 1 pm within eight kilometers.'],
      ['¿Cuánto dura un ramo?|How long does a bouquet last?', 'Entre siete y diez días con agua fresca y un corte diagonal.|Seven to ten days with fresh water and a diagonal cut.'],
      ['¿Qué incluye la suscripción?|What does the subscription include?', 'Un ramo de estación cada dos semanas, con pausa cuando viajás.|A seasonal bouquet every two weeks, with a pause when you travel.'],
      ['¿Puedo elegir los colores?|May I choose the colors?', 'Sí, con una paleta de tres tonos; las variedades las decide la estación.|Yes, from a three-tone palette; the season decides the varieties.'],
      ['¿Las plantas vienen con maceta?|Do plants come potted?', 'Siempre, más una tarjeta con riego y luz.|Always, plus a card with watering and light notes.'],
    ],
    posts: [
      ['Peonías: una temporada de tres semanas|Peonies: a three-week season', 'Por qué valen la espera y cómo abrirlas en casa.|Why they are worth the wait and how to open them at home.', 'Olivia Prentiss'],
      ['Hojas que no se marchitan|Foliage that never wilts', 'Lo mejor para ramos que duran.|The best picks for long-lasting bouquets.', 'Hugo Marlowe'],
      ['Una boda con flores de la zona|A wedding with local flowers', 'Qué se puede conseguir sin viajes ni aviones.|What you can source without trips or planes.', 'Olivia Prentiss'],
    ],
    wiz: {
      title: 'Diseñá un ramo a tu gusto|Design a bouquet to your taste',
      steps: [
        ['Ocasión|Occasion', [rad('forWhom', 'Para quién es|Who it is for', ['Para mí|For myself', 'Para regalar|As a gift'])]],
        ['Presupuesto y fecha|Budget and date', [num('spend', 'Presupuesto|Budget', 15, 200), date('onDay', 'Día de entrega|Delivery day', 'noPast')]],
        ['Regalo|Gift', [text('giftName', 'Nombre de quien recibe|Recipient name', { minLength: 2, maxLength: 50 })]],
        ['Paleta|Palette', [sel('palette', 'Paleta|Palette', ['Pasteles|Pastels', 'Colores vivos|Bright colors', 'Blanco y verde|White and green'])]],
      ],
      cond: ['forWhom', 'as-a-gift', ['giftName']],
    },
    dash: { cols: ['Arreglo|Bouquet', 'Cantidad|Quantity', 'Fecha de entrega|Delivery date', 'Ventas|Sales'], pool: ['Peonías|Peonies', 'Girasoles rústicos|Rustic sunflowers', 'Monstera joven|Young monstera', 'Terrario de suculentas|Succulent terrarium', 'Centro de mesa|Centerpiece', 'Corona de olivo|Olive wreath'], n: [1, 30], m: [18, 780] },
  },
  {
    id: 'hotel-balcon-del-lago',
    name: 'Hotel Balcón del Lago|Lakeside Balcony Hotel',
    tag: 'Desayuno con vista y sin apuro|Breakfast with a view and no hurry',
    style: [200, 18, 'serif', 8, 'ornate'],
    cur: ['Fr.', 'CHF', 2, 'before'],
    nouns: ['habitación|habitaciones|room|rooms', 'huésped|huéspedes|guest|guests', 'reserva|reservas|booking|bookings', 'categoría|categorías|category|categories'],
    nav: ['Recepción|Reception', 'Mi estadía|My stay', 'Confirmar reserva|Confirm booking', 'Tablero de recepción|Front desk board', 'Crónicas del lago|Lake chronicles'],
    cats: ['Habitaciones|Rooms', 'Suites|Suites', 'Experiencias|Experiences', 'Salones|Function rooms'],
    items: [
      ['Doble estándar|Standard double', 'Cama queen y vista al jardín|Queen bed and garden view', 140, 0],
      ['Doble con balcón|Double with balcony', 'Dos sillones y amanecer sobre el agua|Two armchairs and sunrise over the water', 185, 0],
      ['Individual silenciosa|Quiet single', 'Orientada al patio interior|Facing the inner courtyard', 95, 0],
      ['Suite del faro|Lighthouse suite', 'Dormitorio, sala y bañera con vista|Bedroom, living room and a bathtub with a view', 340, 1],
      ['Suite familiar|Family suite', 'Dos dormitorios conectados|Two connecting bedrooms', 290, 1],
      ['Suite de luna de miel|Honeymoon suite', 'Desayuno en la habitación todos los días|Daily breakfast in bed', 390, 1],
      ['Paseo en velero|Sailing trip', 'Tres horas con capitán local|Three hours with a local skipper', 120, 2],
      ['Cena en el muelle|Dock dinner', 'Cuatro pasos y pescado del lago|Four courses and lake fish', 95, 2],
      ['Masaje frente al agua|Waterfront massage', 'Cincuenta minutos de relajación|Fifty minutes of relaxation', 85, 2],
      ['Salón Cormorán|Cormorant room', 'Capacidad de 60 personas en banquete|Seats 60 for a banquet', 900, 3],
      ['Sala de directorio|Boardroom', 'Mesa para catorce y pantalla|Table for fourteen and a screen', 350, 3],
      ['Terraza para ceremonias|Ceremony terrace', 'Cinco horas, con servicio de mozos|Five hours with serving staff', 1200, 3],
    ],
    fields: [
      text('fullName', 'Nombre del huésped|Guest name', { minLength: 3, maxLength: 70 }),
      date('checkIn', 'Llegada|Check-in date', 'noPast'),
      num('nights', 'Noches|Nights', 1, 30),
      num('adults', 'Adultos|Adults', 1, 6),
      sel('bed', 'Tipo de cama|Bed type', ['Una cama grande|One large bed', 'Dos camas simples|Two single beds']),
      pat('promo', 'Código promocional|Promo code', '^LAGO-[A-Z]{3}\\d{2}$', 'LAGO-, tres letras y dos dígitos, ej. LAGO-OTO24|LAGO-, three letters and two digits, e.g. LAGO-OTO24', false),
    ],
    contact: ['Llegada tardía|Late arrival', 'Pedido especial|Special request', 'Evento privado|Private event', 'Factura|Invoice'],
    faq: [
      ['¿A qué hora es el check-in?|What time is check-in?', 'A partir de las 15 h; guardamos el equipaje desde las 10.|From 3 pm; we store luggage from 10 am.'],
      ['¿Se admiten mascotas?|Are pets allowed?', 'Perros pequeños en dos habitaciones del primer piso.|Small dogs in two first-floor rooms.'],
      ['¿El desayuno está incluido?|Is breakfast included?', 'Sí, de 7 a 10:30 con panes del día y huevos a pedido.|Yes, 7 to 10:30 with daily breads and eggs to order.'],
      ['¿Hay estacionamiento?|Is there parking?', 'Cochera cubierta para veinte autos, gratuita.|Covered garage for twenty cars, free of charge.'],
      ['¿Cómo llego desde la estación?|How do I get here from the station?', 'Un servicio de traslado sale cada hora, o veinte minutos a pie.|A shuttle leaves hourly, or it is a twenty-minute walk.'],
    ],
    posts: [
      ['Amaneceres sobre el lago|Dawns over the lake', 'Los tres mejores miradores a cinco minutos.|The three best viewpoints within five minutes.', 'Conserje Erika Walder'],
      ['Receta del pan de huéspedes|The house breakfast bread recipe', 'Harina, nueces y mucho tiempo.|Flour, walnuts and plenty of time.', 'Chef Matthias Ruf'],
      ['Caminatas de otoño|Autumn walks', 'Seis senderos con distancia y desnivel.|Six trails with distance and elevation.', 'Conserje Erika Walder'],
    ],
    wiz: {
      title: 'Planificá tu estadía|Plan your stay',
      steps: [
        ['Motivo del viaje|Purpose of the trip', [rad('trip', 'Motivo del viaje|Purpose of the trip', ['Descanso|Leisure', 'Trabajo|Business'])]],
        ['Fechas y huéspedes|Dates and guests', [date('arrival', 'Fecha de llegada|Arrival date', 'noPast'), num('party', 'Huéspedes|Guests', 1, 8)]],
        ['Factura|Invoice', [text('company', 'Razón social para la factura|Company name for the invoice', { minLength: 3, maxLength: 80 })]],
        ['Extras|Extras', [chk('airportPickup', 'Quiero traslado desde la estación|I want a station pickup')]],
      ],
      cond: ['trip', 'business', ['company']],
    },
    dash: { cols: ['Habitación|Room', 'Noches ocupadas|Nights occupied', 'Fecha de llegada|Arrival date', 'Ingresos|Revenue'], pool: ['Doble estándar|Standard double', 'Doble con balcón|Double with balcony', 'Suite del faro|Lighthouse suite', 'Suite familiar|Family suite', 'Paseo en velero|Sailing trip', 'Salón Cormorán|Cormorant room'], n: [1, 21], m: [95, 4800] },
  },
  {
    id: 'cine-barrio-la-lupa',
    name: 'Cine de Barrio La Lupa|La Lupa Neighborhood Cinema',
    tag: 'Una sala, una película, mucha charla después|One screen, one film, lots of talk afterward',
    style: [350, 45, 'serif', 4, 'ornate'],
    cur: ['$', 'ARS', 0],
    nouns: ['entrada|entradas|ticket|tickets', 'espectador|espectadores|moviegoer|moviegoers', 'reserva|reservas|reservation|reservations', 'ciclo|ciclos|season|seasons'],
    nav: ['Cartelera|Now showing', 'Mis butacas|My seats', 'Comprar entradas|Buy tickets', 'Tablero del proyeccionista|Projectionist board', 'Programa de mano|Program notes'],
    cats: ['Estrenos|New releases', 'Cine de autor|Art house', 'Funciones infantiles|Kids screenings', 'Eventos especiales|Special events'],
    items: [
      ['La última función|The Last Screening', 'Drama sobre un proyeccionista que se resiste a jubilarse|Drama about a projectionist who refuses to retire', 6500, 0],
      ['Mar de fondo|Undertow', 'Thriller en un pueblo pesquero de invierno|Thriller in a fishing village in winter', 6500, 0],
      ['Dos veranos|Two Summers', 'Comedia romántica entre dos temporadas|Romantic comedy across two seasons', 6500, 0],
      ['Hijos del viento|Children of the Wind', 'Documental sobre una escuela rural|Documentary about a rural school', 5000, 1],
      ['La mujer del tranvía|The Tram Woman', 'Película muda con música en vivo|Silent film with live music', 5500, 1],
      ['Cartas desde el desierto|Letters from the Desert', 'Ciclo de cine iraní contemporáneo|Contemporary Iranian film season', 5000, 1],
      ['Matiné de títeres|Puppet matinee', 'Domingos a las 15, para todas las edades|Sundays at 3 pm for all ages', 3500, 2],
      ['El osito que quería volar|The Little Bear Who Wanted to Fly', 'Animación artesanal en stop motion|Handmade stop-motion animation', 4000, 2],
      ['Cuentos de linterna|Flashlight Tales', 'Funciones con linternas de colores|Screenings with colored flashlights', 4000, 2],
      ['Noche de cortos locales|Local shorts night', 'Quince cortos con sus directores en sala|Fifteen shorts with their directors present', 3000, 3],
      ['Maratón de clásicos de terror|Classic horror marathon', 'Tres películas hasta el amanecer|Three films until dawn', 7000, 3],
      ['Pochoclo y debate|Popcorn and debate', 'Charla con un crítico después de la función|A talk with a critic after the film', 5500, 3],
    ],
    fields: [
      text('fullName', 'Nombre y apellido|Full name', { minLength: 3, maxLength: 60 }),
      num('seats', 'Cantidad de butacas|Number of seats', 1, 10),
      sel('row', 'Ubicación en sala|Seating area', ['Fila delantera|Front rows', 'Centro|Center', 'Fondo|Back rows']),
      pat('clubCard', 'Carnet del cineclub|Cine club card', '^CC-\\d{4}$', 'CC- y cuatro dígitos, ej. CC-0418|CC- and four digits, e.g. CC-0418', false),
      chk('accessible', 'Necesito ubicación accesible|I need accessible seating'),
    ],
    contact: ['Alquilar la sala|Rent the hall', 'Proponer una película|Propose a film', 'Devolución de entradas|Ticket refunds', 'Voluntariado|Volunteering'],
    faq: [
      ['¿La sala tiene rampa?|Does the hall have a ramp?', 'Sí, entrada accesible por el pasaje lateral y dos lugares reservados.|Yes, accessible entry via the side passage and two reserved places.'],
      ['¿Puedo entrar con bebida?|Can I bring a drink in?', 'Vendemos vino y gaseosa en el hall y se puede entrar con ellos.|We sell wine and soda in the lobby and you may take them in.'],
      ['¿Cuántas funciones hay por día?|How many screenings per day?', 'Tres: 16, 19 y 21:30, y una función extra los sábados.|Three: 4, 7 and 9:30 pm, plus an extra on Saturdays.'],
      ['¿Hay descuento para jubilados?|Is there a senior discount?', 'Los martes todas las entradas valen la mitad para mayores de 65.|On Tuesdays all tickets are half price for over-65s.'],
      ['¿Subtitulan en inglés?|Are there English subtitles?', 'Las películas extranjeras se pasan con subtítulos en español; algunas con inglés los jueves.|Foreign films have Spanish subtitles; some Thursdays have English.'],
    ],
    posts: [
      ['Proyectar en 35 mm hoy|Projecting on 35 mm today', 'Un día en la cabina con el proyeccionista.|A day in the booth with the projectionist.', 'Ramiro Baldovino'],
      ['Seis películas que no conocías|Six films you had not heard of', 'Recomendaciones del equipo para el invierno.|The team\'s winter recommendations.', 'Equipo La Lupa'],
      ['Música en vivo para cine mudo|Live music for silent film', 'Cómo se ensaya una partitura sin diálogos.|How a score is rehearsed without dialogue.', 'Trío Cuerda y Luz'],
    ],
    wiz: {
      title: 'Organizá una función privada|Organize a private screening',
      steps: [
        ['Tipo de grupo|Group type', [rad('groupKind', 'Tipo de grupo|Group type', ['Una escuela|A school', 'Amigos o empresa|Friends or company'])]],
        ['Fecha y tamaño|Date and size', [date('screeningDate', 'Día deseado|Desired day', 'noPast'), num('headcount', 'Cantidad de personas|Number of people', 10, 120)]],
        ['Escuela|School', [text('schoolName', 'Nombre de la escuela|School name', { minLength: 3, maxLength: 80 })]],
        ['Película|Film', [text('filmWish', 'Película que quieren ver|Film they want to see', { minLength: 2, maxLength: 80 })]],
      ],
      cond: ['groupKind', 'a-school', ['schoolName']],
    },
    dash: { cols: ['Película|Film', 'Entradas vendidas|Tickets sold', 'Función|Showing date', 'Recaudación|Box office'], pool: ['La última función|The Last Screening', 'Mar de fondo|Undertow', 'Dos veranos|Two Summers', 'Hijos del viento|Children of the Wind', 'Matiné de títeres|Puppet matinee', 'Noche de cortos|Shorts night'], n: [8, 120], m: [30000, 780000] },
  },
]

export const everyday = specs.map((s) => defineTheme('everyday', s))
