// Familia "fantasy": magia, gremios, dragones y reinos inventados (TASK-048). Nombres 100% originales.
import { defineTheme, text, area, num, date, chk, sel, rad, pat } from './build.js'

const specs = [
  {
    id: 'academia-magia-cuervo-plata',
    name: 'Academia de Artes Arcanas del Cuervo de Plata|Silver Raven Academy of Arcane Arts',
    tag: 'Siete torres, un solo juramento: no quemar la biblioteca|Seven towers, one oath: do not burn the library',
    style: [262, 48, 'serif', 6, 'ornate'],
    cur: ['◈', 'RUN', 0, 'after'],
    nouns: ['curso|cursos|course|courses', 'aprendiz|aprendices|apprentice|apprentices', 'matrícula|matrículas|enrollment|enrollments', 'escuela|escuelas|school|schools'],
    nav: ['Gran vestíbulo|Great hall', 'Mi horario arcano|My arcane timetable', 'Sellar matrícula|Seal enrollment', 'Tablero del claustro|Faculty board', 'Gaceta de la torre|Tower gazette'],
    cats: ['Piromancia y fuerzas|Pyromancy and forces', 'Herbología encantada|Enchanted herbalism', 'Adivinación|Divination', 'Defensa y contrahechizos|Defense and counterspells'],
    items: [
      ['Chispas y llamas menores|Sparks and Minor Flames', 'Encender una vela sin chamuscar la manga|Lighting a candle without scorching a sleeve', 120, 0],
      ['Levitación de objetos pequeños|Levitating Small Objects', 'Plumas, llaves y tazas medio vacías|Feathers, keys and half-empty cups', 140, 0],
      ['Campos de fuerza de bolsillo|Pocket Force Fields', 'Un escudo del tamaño de una bandeja|A shield the size of a tray', 180, 0],
      ['Raíces que escuchan|Roots That Listen', 'Cultivo de mandrágoras sin gritos|Growing mandrakes without screams', 110, 1],
      ['Invernadero de lunaria|Moonwort Greenhouse', 'Flores que solo abren de noche|Flowers that only open at night', 130, 1],
      ['Tés y tisanas curativas|Healing Teas and Tisanes', 'Mezclas para resfríos de fantasma|Blends for ghostly colds', 100, 1],
      ['Lectura de posos|Reading Tea Leaves', 'Introducción a símbolos de cuenco y taza|Introduction to bowl and cup symbols', 90, 2],
      ['Cartas del cuervo|Raven Cards', 'Un mazo de veintidós arcanos heredados|A heirloom deck of twenty-two arcana', 150, 2],
      ['Predicciones y azar|Prophecy and Chance', 'Por qué un destino puede cambiar de tarde|Why a destiny can change by afternoon', 160, 2],
      ['Contrahechizos de salón|Parlor Counterspells', 'Cómo deshacer una broma de pasillo|How to undo a corridor prank', 170, 3],
      ['Guardias y sellos de puerta|Door Wards and Seals', 'Cerraduras que reconocen a su dueño|Locks that recognize their owner', 190, 3],
      ['Duelo de cortesía|Courtesy Duel', 'Un combate de reverencias y chispas|A combat of bows and sparks', 210, 3],
    ],
    fields: [
      text('apprenticeName', 'Nombre de aprendiz|Apprentice name', { minLength: 3, maxLength: 60 }),
      num('lunarAge', 'Edad en ciclos lunares|Age in lunar cycles', 156, 1200),
      sel('tower', 'Torre de preferencia|Preferred tower', ['Torre del Fuego|Fire Tower', 'Torre del Musgo|Moss Tower', 'Torre del Eco|Echo Tower', 'Torre del Cuervo|Raven Tower']),
      num('manaLevel', 'Nivel de maná medido|Measured mana level', 1, 100),
      pat('wandSerial', 'Serial de varita|Wand serial', '^VR-[A-Z]{2}-\\d{3}$', 'VR-, dos letras, guion y tres dígitos, ej. VR-OL-218|VR-, two letters, a dash and three digits, e.g. VR-OL-218', false),
      chk('familiar', 'Traigo un familiar (animal)|I am bringing a familiar (animal)'),
    ],
    contact: ['Beca de matrícula|Tuition bursary', 'Hechizo que salió mal|Spell that went wrong', 'Visita de familiares|Family visit', 'Biblioteca restringida|Restricted library'],
    faq: [
      ['¿Hace falta tener un don natural?|Do I need a natural gift?', 'No: se enseña desde cero, aunque la práctica diaria es obligatoria.|No, it is taught from scratch, though daily practice is mandatory.'],
      ['¿Cuántos años dura la formación?|How many years does training last?', 'Siete años, divididos en una torre por año.|Seven years, one tower per year.'],
      ['¿Puedo traer mi propio familiar?|May I bring my own familiar?', 'Gatos, cuervos y sapos sí; dragones, nunca.|Cats, ravens and toads yes; dragons, never.'],
      ['¿Hay vacaciones?|Are there holidays?', 'Dos solsticios libres y una semana de finales en otoño.|Two free solstices and an exam week in autumn.'],
      ['¿Qué pasa con la magia fuera de clase?|What about magic outside class?', 'Se permite en los patios; en los dormitorios, solo con permiso del prefecto.|Allowed in the courtyards; in dormitories, only with a prefect\'s leave.'],
    ],
    posts: [
      ['Cómo elegir una varita|How to choose a wand', 'La madera que te elige y no la que te gusta.|The wood that chooses you, not the one you like.', 'Maestra Odalys Vren'],
      ['El eco de la Torre Norte|The Echo of the North Tower', 'Por qué no se debe responder cuando te llama.|Why you must never answer when it calls.', 'Archivista Belén Torvald'],
      ['Primera semana: errores comunes|First week: common mistakes', 'Un prefecto repasa los diez más graciosos.|A prefect reviews the ten funniest ones.', 'Prefecto Mirko Alde'],
    ],
    wiz: {
      title: 'Prueba de admisión|Admission test',
      steps: [
        ['Afinidad|Affinity', [rad('affinity', 'Con qué te sentís más cómodo|What you feel most at ease with', ['Fuego y chispas|Fire and sparks', 'Plantas y raíces|Plants and roots'])]],
        ['Nivel y fecha|Level and date', [num('manaGuess', 'Nivel de maná estimado|Estimated mana level', 1, 100), date('trialDate', 'Día de la prueba|Trial day', 'noPast')]],
        ['Raíces|Roots', [text('favoritePlant', 'Planta con la que te llevás bien|A plant you get along with', { minLength: 3, maxLength: 40 })]],
        ['Ensayo|Essay', [area('essay', 'Por qué querés aprender magia|Why you want to learn magic', 300, true)]],
      ],
      cond: ['affinity', 'plants-and-roots', ['favoritePlant']],
    },
    dash: { cols: ['Curso|Course', 'Aprendices|Apprentices', 'Fecha de inicio|Start date', 'Matrículas|Tuition'], pool: ['Chispas y llamas|Sparks and flames', 'Raíces que escuchan|Roots that listen', 'Lectura de posos|Reading tea leaves', 'Guardias de puerta|Door wards', 'Levitación|Levitation', 'Duelo de cortesía|Courtesy duel'], n: [3, 40], m: [900, 8400] },
  },
  {
    id: 'gremio-aventureros-roble-hondo',
    name: 'Gremio de Aventureros de Roble Hondo|Deep Oak Adventurers\' Guild',
    tag: 'Contratos honestos, cicatrices opcionales|Honest contracts, optional scars',
    style: [30, 8, 'serif', 3, 'ornate'],
    cur: ['mo', 'GLD', 0, 'after'],
    nouns: ['contrato|contratos|contract|contracts', 'aventurero|aventureros|adventurer|adventurers', 'misión|misiones|quest|quests', 'rango|rangos|rank|ranks'],
    nav: ['Tablón de misiones|Quest board', 'Mi mochila|My pack', 'Aceptar contrato|Accept contract', 'Registro del maestro de gremio|Guildmaster ledger', 'Crónicas de taberna|Tavern chronicles'],
    cats: ['Caza menor|Small game hunts', 'Escolta y rutas|Escort and roads', 'Exploración de ruinas|Ruin delving', 'Recados singulares|Odd errands'],
    items: [
      ['Plaga de ratas gigantes|Giant rat infestation', 'Sótano de la panadería de la calle Mojada|The bakery cellar on Wet Street', 40, 0],
      ['Lobo en el vado|Wolf at the ford', 'Una manada rondando las carretas de leche|A pack stalking the milk carts', 90, 0],
      ['Zorro de tres colas|Three-tailed fox', 'Roba pollos y tiene muy buena memoria|Steals hens and has an excellent memory', 120, 0],
      ['Escolta de mercaderes|Merchant escort', 'Tres días hasta el puerto de Calma|Three days to Port Calma', 150, 1],
      ['Cartero de la nieve|Snow mail carrier', 'Entregar sacas antes del deshielo|Deliver sacks before the thaw', 110, 1],
      ['Vigilancia del puente|Bridge watch', 'Una noche sin dormir cobrando doble|One sleepless night at double pay', 80, 1],
      ['Cripta bajo el molino|Crypt beneath the mill', 'Recuperar un anillo familiar|Retrieve a family ring', 260, 2],
      ['Túnel del minero perdido|Lost miner\'s tunnel', 'Mapear antes de que se derrumbe|Map it before it collapses', 300, 2],
      ['Torre inclinada|The leaning tower', 'Registrar los símbolos de la cámara superior|Record the symbols in the upper chamber', 340, 2],
      ['Encontrar un gato mágico|Find a magical cat', 'Atiende por tres nombres distintos|Answers to three different names', 55, 3],
      ['Cambiar un nombre en un monumento|Change a name on a monument', 'Con discreción y escalera larga|With discretion and a long ladder', 70, 3],
      ['Entregar flores en una torre|Deliver flowers to a tower', 'Hay que lograr que el dragón no se ofenda|The dragon must not take offense', 95, 3],
    ],
    fields: [
      text('adventurerName', 'Nombre de aventurero|Adventurer name', { minLength: 3, maxLength: 50 }),
      sel('adventurerClass', 'Clase|Class', ['Guerrero|Warrior', 'Pícaro|Rogue', 'Sanador|Healer', 'Arquero|Archer']),
      num('level', 'Nivel|Level', 1, 20),
      pat('guildCard', 'Número de licencia del gremio|Guild license number', '^GRH-\\d{5}$', 'GRH- y cinco dígitos, ej. GRH-04711|GRH- and five digits, e.g. GRH-04711'),
      sel('rank', 'Rango actual|Current rank', ['Bronce|Bronze', 'Plata|Silver', 'Oro|Gold']),
      area('scars', 'Cicatrices y heridas conocidas|Known scars and wounds', 200),
    ],
    contact: ['Disputa por un pago|Payment dispute', 'Misión peligrosa|Dangerous quest', 'Buscar compañeros de grupo|Find party members', 'Reportar un monstruo|Report a monster'],
    faq: [
      ['¿Quién puede unirse?|Who can join?', 'Cualquier persona mayor de dieciséis con una referencia de otro gremio.|Anyone over sixteen with a reference from another guild.'],
      ['¿Cuánto cuesta la licencia?|How much is the license?', 'Diez monedas de oro al año, con seguro de resurrección optativo.|Ten gold a year, with optional resurrection coverage.'],
      ['¿Cómo se cobra una misión?|How is a quest paid?', 'El gremio retiene la mitad hasta que el cliente firma el cierre.|The guild holds half until the client signs the closing.'],
      ['¿Qué pasa si el contrato falla?|What if a contract fails?', 'Se abre una revisión y se pierde el rango solo si hubo negligencia.|A review opens and rank is lost only for negligence.'],
      ['¿Puedo llevar un animal?|May I bring an animal?', 'Sí, registrado en la libreta del grupo; los caballos deben estar herrados.|Yes, entered in the party book; horses must be shod.'],
    ],
    posts: [
      ['Guía del novato: el primer lobo|Rookie guide: your first wolf', 'Dónde pararte y cuándo no hacerlo.|Where to stand and when not to.', 'Maestra Ysolde Karn'],
      ['Mapa de posadas confiables|A map of trustworthy inns', 'Camas limpias y sopas sin sorpresas.|Clean beds and soups without surprises.', 'Rastreador Bosco Faine'],
      ['Entrevista a la aventurera del año|Interview with the adventurer of the year', 'Doce misiones, ningún rasguño. Por qué dice que fue suerte.|Twelve quests, not a scratch. Why she says it was luck.', 'Cronista Dalmiro Vess'],
    ],
    wiz: {
      title: 'Prueba de ingreso al gremio|Guild entrance trial',
      steps: [
        ['Experiencia|Experience', [rad('background', 'Cómo llegaste a esto|How you got here', ['Soy novato|I am a rookie', 'Vengo de otro gremio|I come from another guild'])]],
        ['Fecha y dificultad|Date and difficulty', [date('trialDay', 'Fecha de la prueba|Trial date', 'noPast'), num('difficulty', 'Dificultad deseada (1-10)|Desired difficulty (1-10)', 1, 10)]],
        ['Gremio anterior|Previous guild', [text('oldGuild', 'Nombre del gremio anterior|Previous guild name', { minLength: 3, maxLength: 60 })]],
        ['Juramento|Oath', [chk('oath', 'Juro no abandonar a mi grupo|I swear not to abandon my party', true)]],
      ],
      cond: ['background', 'i-come-from-another-guild', ['oldGuild']],
    },
    dash: { cols: ['Misión|Quest', 'Aventureros asignados|Adventurers assigned', 'Fecha de cierre|Closing date', 'Recompensa|Reward'], pool: ['Plaga de ratas|Rat infestation', 'Lobo en el vado|Wolf at the ford', 'Escolta de mercaderes|Merchant escort', 'Cripta del molino|Mill crypt', 'Gato mágico|Magical cat', 'Flores a la torre|Flowers to the tower'], n: [1, 8], m: [40, 420] },
  },
  {
    id: 'registro-dragones-valle-ceniza',
    name: 'Registro Oficial de Dragones del Valle de Ceniza|Official Dragon Registry of Ash Valley',
    tag: 'Si tiene alas y escupe fuego, tiene que estar inscrito|If it has wings and breathes fire, it must be registered',
    style: [14, 38, 'serif', 2, 'ornate'],
    cur: ['◆', 'ESC', 0, 'after'],
    nouns: ['licencia|licencias|license|licenses', 'dueño|dueños|keeper|keepers', 'inscripción|inscripciones|registration|registrations', 'especie|especies|species|species'],
    nav: ['Despacho del escriba|Scribe\'s office', 'Mi dragón|My dragon', 'Firmar inscripción|Sign registration', 'Libro mayor del registro|Registry ledger', 'Bestiario público|Public bestiary'],
    cats: ['Licencias de dragón|Dragon licenses', 'Trámites de cría|Breeding paperwork', 'Seguros y daños|Insurance and damage', 'Permisos de vuelo|Flight permits'],
    items: [
      ['Licencia de dragón menor|Lesser dragon license', 'Hasta tres metros de envergadura|Up to three meters of wingspan', 30, 0],
      ['Licencia de dragón mayor|Greater dragon license', 'Requiere inspección anual de las garras|Requires annual claw inspection', 90, 0],
      ['Licencia de pichón|Hatchling license', 'Válida hasta que le salgan las alas|Valid until the wings grow in', 15, 0],
      ['Registro de nido|Nest registration', 'Con plano de la cueva y vías de escape|With cave map and escape routes', 40, 1],
      ['Permiso de cría|Breeding permit', 'Máximo un huevo por década|Maximum one egg per decade', 120, 1],
      ['Certificado de linaje|Lineage certificate', 'Abuelos hasta la tercera generación|Grandparents back to the third generation', 55, 1],
      ['Seguro contra incendio de aldea|Village fire insurance', 'Cubre daños accidentales por aliento|Covers accidental breath damage', 70, 2],
      ['Seguro de rebaños vecinos|Neighboring flock insurance', 'Indemniza ovejas desaparecidas|Compensates missing sheep', 45, 2],
      ['Responsabilidad por estornudos|Sneeze liability', 'Los resfríos de dragón cuentan como siniestro|Dragon colds count as claims', 35, 2],
      ['Corredor aéreo del norte|Northern air corridor', 'Altura máxima 800 varas|Maximum height 800 rods', 25, 3],
      ['Permiso de vuelo nocturno|Night flight permit', 'Con farol en la cola obligatorio|Tail lantern mandatory', 45, 3],
      ['Aterrizaje en plazas|Square landing permit', 'Solo en días de feria y con aviso previo|Market days only, with prior notice', 60, 3],
    ],
    fields: [
      text('keeperName', 'Nombre del dueño|Keeper name', { minLength: 3, maxLength: 60 }),
      text('dragonName', 'Nombre del dragón|Dragon name', { minLength: 2, maxLength: 40 }),
      pat('licenseCode', 'Código de licencia de dragón|Dragon license code', '^DR-\\d{4}$', 'DR- seguido de cuatro dígitos, ej. DR-0731|DR- followed by four digits, e.g. DR-0731'),
      sel('species', 'Especie|Species', ['Verde de bosque|Forest green', 'Rojo de volcán|Volcano red', 'Azul de escarcha|Frost blue', 'Dorado de sabana|Savanna gold']),
      num('wingspan', 'Envergadura en varas|Wingspan in rods', 1, 60),
      num('dragonAge', 'Edad del dragón en estaciones|Dragon age in seasons', 0, 2000),
      chk('fireproof', 'Mi cueva es ignífuga|My cave is fireproof', true),
    ],
    contact: ['Daño por aliento|Breath damage', 'Dragón extraviado|Lost dragon', 'Duplicado de licencia|License duplicate', 'Vecinos molestos|Disgruntled neighbors'],
    faq: [
      ['¿Todos los dragones deben registrarse?|Must every dragon be registered?', 'Sí, desde que rompen el cascarón; el plazo es de treinta días.|Yes, from hatching; the deadline is thirty days.'],
      ['¿Qué pasa si se escapa?|What if it escapes?', 'Se avisa al registro dentro de las seis horas y se abre una búsqueda comunal.|Notify the registry within six hours and a communal search opens.'],
      ['¿Puedo cambiar el nombre?|Can I change the name?', 'Una vez en la vida, con testigo y una moneda de plata.|Once in a lifetime, with a witness and a silver coin.'],
      ['¿Quién inspecciona las cuevas?|Who inspects the caves?', 'Los guardas de roca, una vez al año, avisando con tres días.|The rock wardens, once a year, with three days\' notice.'],
      ['¿Hay seguro obligatorio?|Is insurance mandatory?', 'Para dragones mayores sí, para los menores es recomendable.|For greater dragons yes, for lesser ones it is advised.'],
    ],
    posts: [
      ['Cómo reconocer un dragón enfermo|How to recognize a sick dragon', 'Escamas opacas, aliento tibio y mal humor excesivo.|Dull scales, lukewarm breath and excessive grumpiness.', 'Escriba Hartwin Osk'],
      ['Mapa de corredores aéreos|Air corridor map', 'Cuáles se abren en invierno y cuáles se cierran.|Which open in winter and which close.', 'Guarda Lisbeth Moor'],
      ['Récord de longevidad|Longevity record', 'Un dragón de mil ochocientas estaciones y su dieta de nueces.|An eighteen-hundred-season-old dragon and its walnut diet.', 'Escriba Hartwin Osk'],
    ],
    wiz: {
      title: 'Alta de un dragón recién nacido|Registering a newborn dragon',
      steps: [
        ['Origen|Origin', [rad('origin', 'Cómo llegó a tu cueva|How it reached your cave', ['Nació de un huevo propio|Hatched from my own egg', 'Lo encontré o adopté|Found or adopted'])]],
        ['Fecha y tamaño|Date and size', [date('hatchDate', 'Día del nacimiento (o hallazgo)|Hatch (or finding) date', 'noFuture'), num('lengthRods', 'Largo en varas|Length in rods', 1, 30)]],
        ['Hallazgo|Finding', [area('findingStory', 'Dónde y cómo lo encontraste|Where and how you found it', 300)]],
        ['Cuevas|Cave', [chk('fireproofCave', 'La cueva es ignífuga|The cave is fireproof', true)]],
      ],
      cond: ['origin', 'found-or-adopted', ['findingStory']],
    },
    dash: { cols: ['Especie|Species', 'Dragones inscritos|Registered dragons', 'Fecha de inscripción|Registration date', 'Tasas cobradas|Fees collected'], pool: ['Verde de bosque|Forest green', 'Rojo de volcán|Volcano red', 'Azul de escarcha|Frost blue', 'Dorado de sabana|Savanna gold', 'Gris de ceniza|Ash gray', 'Negro de caverna|Cavern black'], n: [1, 18], m: [30, 1600] },
  },
  {
    id: 'mercado-pociones-luna-roja',
    name: 'Mercado de Pociones Luna Roja|Red Moon Potion Market',
    tag: 'Frascos sellados, efectos garantizados (más o menos)|Sealed vials, effects guaranteed (more or less)',
    style: [310, 140, 'serif', 12, 'ornate'],
    cur: ['⚗', 'LPL', 0, 'after'],
    nouns: ['poción|pociones|potion|potions', 'cliente|clientes|customer|customers', 'pedido|pedidos|order|orders', 'tipo|tipos|kind|kinds'],
    nav: ['Puesto central|Central stall', 'Mi canasto de frascos|My vial basket', 'Pagar y sellar|Pay and seal', 'Cuaderno del boticario|Apothecary ledger', 'Gaceta de remedios|Remedy gazette'],
    cats: ['Salud y cuidado|Health and care', 'Fuerza y valor|Strength and courage', 'Amor y amistad|Love and friendship', 'Curiosidades|Curiosities'],
    items: [
      ['Poción de pies firmes|Steady-feet potion', 'Evita resbalar en hielo durante una hora|Prevents slipping on ice for one hour', 22, 0],
      ['Tónico contra el mal de ojo|Evil-eye tonic', 'Un sorbo antes de salir de casa|A sip before leaving the house', 18, 0],
      ['Jarabe de sueño sin sueños|Dreamless sleep syrup', 'Descanso profundo hasta el alba|Deep rest until dawn', 25, 0],
      ['Elixir de valor tibio|Lukewarm courage elixir', 'Alcanza para hablar en público|Enough to speak in public', 40, 1],
      ['Extracto de fuerza de oso|Bear-strength extract', 'Doce horas de bíceps; no usar con puertas|Twelve hours of biceps; do not use near doors', 55, 1],
      ['Gotas de reflejos de gato|Cat-reflex drops', 'Para atrapar lo que se cae|For catching whatever falls', 36, 1],
      ['Perfume de buena suerte|Good-luck perfume', 'Aroma de trébol y canela|Clover and cinnamon scent', 60, 2],
      ['Poción de amistad duradera|Lasting-friendship potion', 'Dos frascos: uno por persona|Two vials, one per person', 48, 2],
      ['Aliento de rosa|Rose breath', 'Aliento fresco durante un día entero|Fresh breath for a whole day', 20, 2],
      ['Poción para hablar con las plantas|Plant-talking potion', 'Los resultados varían según la planta|Results vary depending on the plant', 65, 3],
      ['Polvo de invisibilidad parcial|Partial invisibility powder', 'Solo desaparecen los pies|Only the feet vanish', 30, 3],
      ['Gotas de color de pelo cambiante|Hair-color-changing drops', 'Cambia con el humor, sin control fino|Shifts with your mood, no fine control', 28, 3],
    ],
    fields: [
      text('customerName', 'Nombre del cliente|Customer name', { minLength: 3, maxLength: 60 }),
      num('bodyWeight', 'Peso corporal en kilos|Body weight in kilos', 20, 250),
      sel('allergy', 'Alergia conocida|Known allergy', ['Ninguna|None', 'Polen de luna|Moon pollen', 'Veneno de araña|Spider venom', 'Hierbas amargas|Bitter herbs']),
      pat('vialSerial', 'Serial del frasco|Vial serial', '^LR-\\d{3}-[A-Z]$', 'LR-, tres dígitos, guion y una letra, ej. LR-482-C|LR-, three digits, a dash and a letter, e.g. LR-482-C', false),
      num('dose', 'Dosis deseada en gotas|Desired dose in drops', 1, 30),
      chk('adult', 'Soy mayor de edad en mi reino|I am of legal age in my realm', true),
    ],
    contact: ['Efecto secundario|Side effect', 'Poción vencida|Expired potion', 'Fórmula personalizada|Custom formula', 'Venta mayorista|Wholesale'],
    faq: [
      ['¿Las pociones están probadas?|Are the potions tested?', 'Cada lote pasa por tres catadores y un gato testigo.|Every batch is tasted by three testers and a witness cat.'],
      ['¿Cuánto duran los efectos?|How long do effects last?', 'Entre una hora y una jornada completa, según la etiqueta.|Between an hour and a full day, as the label says.'],
      ['¿Se pueden mezclar?|Can they be mixed?', 'Nunca dos de fuerza; amor con amistad es seguro.|Never two strength ones; love with friendship is safe.'],
      ['¿Hay devolución?|Are refunds possible?', 'Con el frasco cerrado y dentro de siete noches.|With the vial sealed and within seven nights.'],
      ['¿Hacen envíos a otros reinos?|Do you ship to other realms?', 'Por palomas mensajeras hasta cinco jornadas de distancia.|By carrier pigeon up to five days away.'],
    ],
    posts: [
      ['Las tres hierbas del invierno|The three winter herbs', 'Cuáles recoger al amanecer y cuáles dejar crecer.|Which to pick at dawn and which to leave growing.', 'Boticaria Marigold Teneb'],
      ['Cómo leer una etiqueta de frasco|How to read a vial label', 'Concentración, advertencias y símbolos de luna.|Strength, warnings and moon symbols.', 'Boticaria Marigold Teneb'],
      ['Casos insólitos del mes|Odd cases of the month', 'Un cliente que habló con una zanahoria durante tres días.|A customer who spoke with a carrot for three days.', 'Aprendiz Pip Corvelle'],
    ],
    wiz: {
      title: 'Receta personalizada|Custom recipe',
      steps: [
        ['Para qué sirve|Purpose', [rad('wish', 'Qué querés lograr|What you want to achieve', ['Dormir mejor|Sleep better', 'Un efecto especial|A special effect'])]],
        ['Dosis y entrega|Dose and delivery', [num('batch', 'Frascos por lote|Vials per batch', 1, 24), date('needBy', 'Necesito antes de|Needed by', 'noPast')]],
        ['Efecto|Effect', [area('effectDesc', 'Describí el efecto que buscás|Describe the effect you want', 300)]],
        ['Aviso|Warning', [chk('waiver', 'Acepto que los resultados pueden variar|I accept that results may vary', true)]],
      ],
      cond: ['wish', 'a-special-effect', ['effectDesc']],
    },
    dash: { cols: ['Poción|Potion', 'Frascos vendidos|Vials sold', 'Fecha de venta|Sale date', 'Ingresos|Income'], pool: ['Pies firmes|Steady feet', 'Valor tibio|Lukewarm courage', 'Fuerza de oso|Bear strength', 'Buena suerte|Good luck', 'Hablar con plantas|Plant talk', 'Sueño sin sueños|Dreamless sleep'], n: [2, 80], m: [60, 3600] },
  },
  {
    id: 'herreria-elfica-hojaluz',
    name: 'Herrería Élfica Hojaluz|Leaflight Elven Smithy',
    tag: 'Filos que cantan al ser desenvainados|Blades that sing when drawn',
    style: [140, 50, 'serif', 2, 'ornate'],
    cur: ['❦', 'HJL', 0, 'after'],
    nouns: ['pieza|piezas|piece|pieces', 'cliente|clientes|client|clients', 'encargo|encargos|commission|commissions', 'taller|talleres|workshop|workshops'],
    nav: ['Fragua|Forge', 'Mis piezas|My pieces', 'Encargar pieza|Commission a piece', 'Libro de la fragua|Forge ledger', 'Canciones del yunque|Songs of the anvil'],
    cats: ['Espadas y dagas|Swords and daggers', 'Arcos y flechas|Bows and arrows', 'Armaduras ligeras|Light armor', 'Joyas y sellos|Jewelry and seals'],
    items: [
      ['Espada larga de hoja de sauce|Willow-leaf longsword', 'Doblada treinta veces y templada con rocío|Folded thirty times and quenched in dew', 340, 0],
      ['Daga de las corrientes|Dagger of currents', 'Empuñadura de cuerno y filo ondulado|Horn hilt and wavy edge', 180, 0],
      ['Cuchilla de poda|Pruning blade', 'Para jardineros que se toman en serio la rama|For gardeners who take branches seriously', 90, 0],
      ['Arco de tejo plateado|Silvered yew bow', 'Cuerda de seda de araña|Spider-silk string', 260, 1],
      ['Flechas de plumas de búho|Owl-feather arrows', 'Vuelo silencioso, docena|Silent flight, per dozen', 70, 1],
      ['Carcaj de corteza|Bark quiver', 'Impermeable y ligero|Waterproof and light', 55, 1],
      ['Coraza de escamas verdes|Green scale cuirass', 'Pesa lo que una manta|Weighs about as much as a blanket', 420, 2],
      ['Capa de hojas tejidas|Woven-leaf cloak', 'Se camufla en bosques de hayas|Blends into beech forests', 210, 2],
      ['Guantes de cazador|Hunter\'s gloves', 'Cuero de ciervo sin costuras|Seamless deerskin', 85, 2],
      ['Anillo de luz mínima|Ring of faint light', 'Brilla apenas en la oscuridad|Glows faintly in the dark', 150, 3],
      ['Broche de familia|Family brooch', 'Grabado con el árbol de tu linaje|Engraved with your lineage tree', 120, 3],
      ['Sello de cartas|Letter seal', 'Imprime una hoja de roble en cera|Stamps an oak leaf in wax', 60, 3],
    ],
    fields: [
      text('clientName', 'Nombre del cliente|Client name', { minLength: 3, maxLength: 60 }),
      sel('race', 'Pueblo|People', ['Humano|Human', 'Elfo|Elf', 'Enano|Dwarf', 'Mediano|Halfling']),
      num('armLength', 'Largo del brazo en palmos|Arm length in spans', 4, 14),
      sel('hand', 'Mano hábil|Dominant hand', ['Derecha|Right', 'Izquierda|Left', 'Ambidiestro|Ambidextrous']),
      pat('commissionCode', 'Código de encargo|Commission code', '^HJ\\d{2}-[A-Z]{3}$', 'HJ, dos dígitos, guion y tres letras, ej. HJ07-ARC|HJ, two digits, a dash and three letters, e.g. HJ07-ARC', false),
      area('engraving', 'Inscripción para grabar|Engraving text', 80),
    ],
    contact: ['Reparar una pieza|Repair a piece', 'Pedido urgente|Rush commission', 'Aprendizaje en la fragua|Forge apprenticeship', 'Tasación de herencia|Heirloom appraisal'],
    faq: [
      ['¿Cuánto tarda un encargo?|How long does a commission take?', 'De dos a diez lunas, según el temple y el grabado.|Two to ten moons, depending on temper and engraving.'],
      ['¿Qué metal usan?|What metal do you use?', 'Acero de montaña con una veta de plata en piezas mayores.|Mountain steel with a silver vein in major pieces.'],
      ['¿Hacen piezas para niños?|Do you make children\'s pieces?', 'Hacemos espadas de madera con herrajes de verdad.|We make wooden swords with genuine fittings.'],
      ['¿Se garantizan los filos?|Are edges guaranteed?', 'Un afilado gratuito por año, de por vida.|One free sharpening a year, for life.'],
      ['¿Puedo visitar la fragua?|Can I visit the forge?', 'Los segundos domingos, en silencio y sin sombrero.|On second Sundays, silently and hatless.'],
    ],
    posts: [
      ['El temple de rocío|Dew quenching', 'Por qué la madrugada cambia el color del filo.|Why dawn changes the color of an edge.', 'Maestra Ilvarë Tolen'],
      ['Cómo cuidar un arco|How to care for a bow', 'Cera, tensión y la humedad de la bodega.|Wax, tension and cellar humidity.', 'Arquero Faelan Quill'],
      ['Seis generaciones de anillos|Six generations of rings', 'La historia de una familia y su sello de roble.|The story of a family and its oak seal.', 'Maestra Ilvarë Tolen'],
    ],
    wiz: {
      title: 'Encargá una pieza a medida|Commission a bespoke piece',
      steps: [
        ['Tipo de pieza|Piece type', [sel('pieceKind', 'Qué querés encargar|What you want to commission', ['Un arma|A weapon', 'Una joya|A jewel', 'Una armadura|Armor'])]],
        ['Fecha y presupuesto|Date and budget', [date('wantedBy', 'Plazo deseado|Desired deadline', 'noPast'), num('coins', 'Presupuesto en hojas|Budget in leaves', 50, 2000)]],
        ['Arma|Weapon', [num('bladeLength', 'Largo de hoja en palmos|Blade length in spans', 2, 12)]],
        ['Detalles|Details', [area('storyBehind', 'Historia que debe contar la pieza|Story the piece should tell', 300)]],
      ],
      cond: ['pieceKind', 'a-weapon', ['bladeLength']],
    },
    dash: { cols: ['Pieza|Piece', 'Unidades forjadas|Units forged', 'Fecha de entrega|Delivery date', 'Pago recibido|Payment received'], pool: ['Espada de sauce|Willow sword', 'Daga de corrientes|Current dagger', 'Arco de tejo|Yew bow', 'Coraza de escamas|Scale cuirass', 'Anillo de luz|Ring of light', 'Capa de hojas|Leaf cloak'], n: [1, 9], m: [60, 1400] },
  },
  {
    id: 'oraculo-gruta-dorada',
    name: 'El Oráculo de la Gruta Dorada|The Golden Grotto Oracle',
    tag: 'Respuestas verdaderas, preguntas bien formuladas|True answers, well-phrased questions',
    style: [48, 280, 'serif', 10, 'ornate'],
    cur: ['☉', 'ORO', 0, 'after'],
    nouns: ['profecía|profecías|prophecy|prophecies', 'consultante|consultantes|seeker|seekers', 'audiencia|audiencias|audience|audiences', 'don|dones|gift|gifts'],
    nav: ['Atrio|Forecourt', 'Mis consultas|My consultations', 'Reservar audiencia|Book an audience', 'Anales de la gruta|Grotto annals', 'Sentencias oscuras|Dark sayings'],
    cats: ['Preguntas personales|Personal questions', 'Asuntos de reino|Realm affairs', 'Cosechas y clima|Harvests and weather', 'Interpretaciones|Interpretations'],
    items: [
      ['Una pregunta sobre el amor|One question about love', 'Respuesta breve y ligeramente ambigua|A short and slightly ambiguous answer', 12, 0],
      ['Camino de vida en tres señales|Life path in three signs', 'Tres imágenes y un consejo|Three images and a piece of advice', 30, 0],
      ['Revisión de una decisión|Decision review', 'Qué pasaría si elegís la otra puerta|What would happen if you chose the other door', 20, 0],
      ['Presagio para un viaje|Omen for a journey', 'Fechas favorables y caminos a evitar|Favorable dates and roads to avoid', 25, 0],
      ['Alianza matrimonial|Marriage alliance', 'Sesión con las dos familias presentes|Session with both families present', 150, 1],
      ['Sucesión del trono|Throne succession', 'Respuesta lacrada, firmada por tres sacerdotes|A sealed answer signed by three priests', 600, 1],
      ['Guerra o tratado|War or treaty', 'Consulta urgente fuera de horario|Urgent after-hours consultation', 450, 1],
      ['Pronóstico de lluvias|Rainfall forecast', 'Para la siembra de primavera|For spring sowing', 35, 2],
      ['Predicción de cosecha|Harvest prediction', 'Por tipo de grano y valle|By grain type and valley', 40, 2],
      ['Aviso de tormentas|Storm notice', 'Alerta con ocho días de anticipación|Alert eight days in advance', 55, 2],
      ['Traducción de un sueño|Dream translation', 'Con símbolos del bestiario de la gruta|With symbols from the grotto bestiary', 18, 3],
      ['Descifrar una profecía antigua|Decoding an ancient prophecy', 'Para cuando la anterior fue demasiado vaga|For when the previous one was too vague', 90, 3],
    ],
    fields: [
      text('seekerName', 'Nombre del consultante|Seeker name', { minLength: 2, maxLength: 60 }),
      sel('topic', 'Tema principal|Main topic', ['Amor|Love', 'Trabajo|Work', 'Salud|Health', 'Viaje|Travel', 'Reino|Realm']),
      num('lunarAge', 'Edad en ciclos lunares|Age in lunar cycles', 156, 1500),
      pat('questionCode', 'Código de pregunta|Question code', '^PQ-[A-Z]{3}-\\d{2}$', 'PQ-, tres letras, guion y dos dígitos, ej. PQ-AMO-07|PQ-, three letters, a dash and two digits, e.g. PQ-AMO-07', false),
      area('question', 'Tu pregunta, en una frase|Your question, in one sentence', 140, true),
      chk('accepts', 'Acepto que la respuesta pueda no gustarme|I accept that I may dislike the answer', true),
    ],
    contact: ['Respuesta confusa|Confusing answer', 'Cancelar una audiencia|Cancel an audience', 'Ofrendas y donaciones|Offerings and donations', 'Ser sacerdote|Become a priest'],
    faq: [
      ['¿Las profecías siempre se cumplen?|Do prophecies always come true?', 'Se cumplen casi siempre, aunque no de la manera esperada.|Almost always, though not in the way you expected.'],
      ['¿Qué pasa si no entiendo la respuesta?|What if I do not understand the answer?', 'Una segunda lectura gratuita dentro del mismo ciclo lunar.|A free second reading within the same lunar cycle.'],
      ['¿Puedo hacer varias preguntas?|May I ask several questions?', 'Una por visita; las demás se anotan en la lista de espera.|One per visit; others go on the waiting list.'],
      ['¿Hace falta ofrenda?|Is an offering required?', 'No obligatoria, pero la miel y el aceite de oliva se agradecen.|Not required, but honey and olive oil are appreciated.'],
      ['¿La gruta es segura?|Is the grotto safe?', 'Hay guías con antorchas y un pasamanos de cuerda hasta la sala.|There are torch-bearing guides and a rope handrail to the chamber.'],
    ],
    posts: [
      ['Cómo formular una buena pregunta|How to phrase a good question', 'Evitá los "o" y los "nunca".|Avoid "or" and "never".', 'Sacerdotisa Ariadna Lumen'],
      ['Profecías que se cumplieron al revés|Prophecies that came true backward', 'Cinco casos comentados por los archivistas.|Five cases annotated by the archivists.', 'Archivista Tobías Kell'],
      ['Un día en la gruta|A day in the grotto', 'Desde el amanecer hasta que el humo toma forma.|From dawn until the smoke takes shape.', 'Sacerdotisa Ariadna Lumen'],
    ],
    wiz: {
      title: 'Preparar tu audiencia|Prepare your audience',
      steps: [
        ['Naturaleza|Nature', [rad('seekerKind', 'Quién consulta|Who is asking', ['Una persona|One person', 'Un reino|A realm'])]],
        ['Fecha y urgencia|Date and urgency', [date('audienceDay', 'Día de la audiencia|Audience day', 'noPast'), num('urgency', 'Urgencia (1 a 5)|Urgency (1 to 5)', 1, 5)]],
        ['Reino|Realm', [text('realmName', 'Nombre del reino|Realm name', { minLength: 3, maxLength: 60 })]],
        ['Pregunta|Question', [area('mainQuestion', 'Tu pregunta principal|Your main question', 200, true)]],
      ],
      cond: ['seekerKind', 'a-realm', ['realmName']],
    },
    dash: { cols: ['Tipo de consulta|Consultation type', 'Audiencias|Audiences', 'Fecha|Date', 'Ofrendas|Offerings'], pool: ['Amor|Love', 'Viaje|Travel', 'Cosecha|Harvest', 'Sucesión|Succession', 'Sueños|Dreams', 'Guerra o tratado|War or treaty'], n: [1, 25], m: [12, 1200] },
  },
  {
    id: 'torre-alquimia-mercurio-verde',
    name: 'Torre de Alquimia Mercurio Verde|Green Mercury Alchemy Tower',
    tag: 'Transmutamos casi todo, menos tu mala suerte|We transmute nearly everything, except your bad luck',
    style: [120, 40, 'mono', 4, 'tech'],
    cur: ['ʘ', 'MCV', 0, 'after'],
    nouns: ['reactivo|reactivos|reagent|reagents', 'alquimista|alquimistas|alchemist|alchemists', 'solicitud|solicitudes|request|requests', 'elemento|elementos|element|elements'],
    nav: ['Laboratorio|Laboratory', 'Mi matraz|My flask', 'Autorizar síntesis|Authorize synthesis', 'Panel del crisol|Crucible panel', 'Cuaderno de experimentos|Experiment notebook'],
    cats: ['Metales y transmutación|Metals and transmutation', 'Sales y ácidos|Salts and acids', 'Instrumental de vidrio|Glassware', 'Libros y fórmulas|Books and formulas'],
    items: [
      ['Plomo refinado, un lingote|Refined lead, one ingot', 'Base de partida para una transmutación|Starting stock for a transmutation', 20, 0],
      ['Piedra filosofal de aprendiz|Apprentice philosopher\'s stone', 'Funciona al treinta por ciento|Works at thirty percent', 400, 0],
      ['Polvo de cobre vivo|Quick copper dust', 'Reacciona al contacto con vinagre|Reacts on contact with vinegar', 35, 0],
      ['Sal de sosa|Soda salt', 'Pureza de laboratorio, tarro de 500 g|Lab purity, 500 g jar', 15, 1],
      ['Ácido de hormiga|Ant acid', 'Para limpiar óxidos de bronce|For cleaning bronze oxide', 22, 1],
      ['Vitriolo azul|Blue vitriol', 'Cristales que se disuelven en agua tibia|Crystals that dissolve in warm water', 30, 1],
      ['Matraz de fondo redondo|Round-bottom flask', 'Vidrio de borosilicato, 500 ml|Borosilicate glass, 500 ml', 18, 2],
      ['Alambique de cobre|Copper still', 'Con serpentín y tapa hermética|With coil and airtight lid', 260, 2],
      ['Probeta con escala dorada|Gold-scale test tube', 'Marcas de 5 en 5 mililitros|Marks every five milliliters', 8, 2],
      ['Tratado de la tinta verde|Treatise on Green Ink', 'Cien fórmulas escritas a mano|One hundred handwritten formulas', 80, 3],
      ['Bestiario de metales|Metal bestiary', 'Qué hace cada metal con la luna|What each metal does under the moon', 55, 3],
      ['Cuaderno de lab encerado|Waxed lab notebook', 'Resiste salpicaduras de ácido|Resists acid splashes', 12, 3],
    ],
    fields: [
      text('alchemistName', 'Nombre del alquimista|Alchemist name', { minLength: 3, maxLength: 60 }),
      pat('labPermit', 'Permiso de laboratorio|Lab permit', '^AL-\\d{4}-[VR]$', 'AL-, cuatro dígitos, guion y V o R, ej. AL-0231-V|AL-, four digits, a dash and V or R, e.g. AL-0231-V'),
      sel('discipline', 'Disciplina|Discipline', ['Transmutación|Transmutation', 'Destilación|Distillation', 'Cristalización|Crystallization']),
      num('yearsExperience', 'Años de experiencia|Years of experience', 0, 60),
      chk('ventilated', 'Mi laboratorio tiene ventilación|My lab is ventilated', true),
      area('purpose', 'Para qué usarás los reactivos|What you will use the reagents for', 200),
    ],
    contact: ['Accidente de laboratorio|Lab accident', 'Reactivo agotado|Reagent out of stock', 'Pedir una fórmula|Request a formula', 'Reciclaje de residuos|Waste recycling'],
    faq: [
      ['¿Es legal comprar estos reactivos?|Is it legal to buy these reagents?', 'Con permiso de laboratorio vigente, sí; sin él, no.|With a valid lab permit, yes; without it, no.'],
      ['¿La piedra filosofal convierte oro?|Does the philosopher\'s stone make gold?', 'En pequeñas cantidades y con poca eficiencia: sale más barato comprar oro.|In small amounts and poor efficiency; buying gold is cheaper.'],
      ['¿Cómo se envían los ácidos?|How are acids shipped?', 'En frascos de vidrio ámbar dentro de cajas de arcilla.|In amber glass bottles inside clay boxes.'],
      ['¿Dan clases?|Do you teach?', 'Cursos de seguridad cada primer lunes, obligatorios para nuevos.|Safety courses every first Monday, mandatory for newcomers.'],
      ['¿Hay devolución de instrumental?|Do you take back glassware?', 'Sí, si no tiene residuos ni fisuras.|Yes, if free of residue and cracks.'],
    ],
    posts: [
      ['Por qué no mezclar vitriolo con aguardiente|Why not to mix vitriol with brandy', 'Una crónica de un laboratorio sin techo.|A chronicle of a lab that lost its roof.', 'Maestro Cornelio Vask'],
      ['Destilar bien: tres reglas|Distilling well: three rules', 'Temperatura constante y paciencia.|Steady heat and patience.', 'Dra. Ottilie Merrow'],
      ['El oro que no era oro|The gold that was not gold', 'Cómo distinguir una aleación de una promesa.|How to tell an alloy from a promise.', 'Maestro Cornelio Vask'],
    ],
    wiz: {
      title: 'Solicitud de síntesis|Synthesis request',
      steps: [
        ['Objetivo|Goal', [sel('goal', 'Qué querés lograr|What you want to achieve', ['Transmutar metal|Transmute metal', 'Purificar una sal|Purify a salt', 'Probar una fórmula nueva|Test a new formula'])]],
        ['Cantidad y fecha|Amount and date', [num('grams', 'Cantidad en gramos|Amount in grams', 10, 5000), date('startAt', 'Inicio del proceso|Process start', 'noPast')]],
        ['Fórmula|Formula', [area('formulaText', 'Escribí la fórmula completa|Write the full formula', 300, true)]],
        ['Seguridad|Safety', [chk('gloves', 'Cuento con guantes y mascarilla|I have gloves and a mask', true)]],
      ],
      cond: ['goal', 'test-a-new-formula', ['formulaText']],
    },
    dash: { cols: ['Reactivo|Reagent', 'Frascos despachados|Flasks shipped', 'Fecha de despacho|Shipping date', 'Facturado|Billed'], pool: ['Plomo refinado|Refined lead', 'Sal de sosa|Soda salt', 'Vitriolo azul|Blue vitriol', 'Ácido de hormiga|Ant acid', 'Alambique de cobre|Copper still', 'Tratado de la tinta verde|Green Ink treatise'], n: [1, 60], m: [15, 2400] },
  },
  {
    id: 'taberna-grifo-dormido',
    name: 'Taberna del Grifo Dormido|The Sleeping Griffin Tavern',
    tag: 'Cerveza de cebada, pan caliente y ningún dragón|Barley beer, hot bread and no dragons',
    style: [24, 8, 'serif', 6, 'ornate'],
    cur: ['pc', 'COB', 0, 'after'],
    nouns: ['plato|platos|dish|dishes', 'parroquiano|parroquianos|patron|patrons', 'cuenta|cuentas|tab|tabs', 'sección|secciones|section|sections'],
    nav: ['Salón común|Common room', 'Mi mesa|My table', 'Pagar la cuenta|Pay the tab', 'Libro de cuentas del tabernero|Innkeeper\'s ledger', 'Rumores de la barra|Rumors from the bar'],
    cats: ['Bebidas|Drinks', 'Platos de olla|Stews', 'Pan y quesos|Bread and cheese', 'Cuartos y establo|Rooms and stable'],
    items: [
      ['Cerveza negra de la casa|House dark ale', 'Cebada tostada y un toque de miel|Roasted barley with a touch of honey', 4, 0],
      ['Hidromiel de bellota|Acorn mead', 'Dulce y espesa, sirve en cuerno|Sweet and thick, served in a horn', 6, 0],
      ['Sidra de la montaña|Mountain cider', 'Manzanas agrias y burbuja fina|Tart apples and a fine fizz', 4, 0],
      ['Estofado del cazador|Hunter\'s stew', 'Venado, setas y vino tinto|Venison, mushrooms and red wine', 9, 1],
      ['Sopa de cebolla ahumada|Smoked onion soup', 'Con crouton gratinado|With a gratinéed crouton', 6, 1],
      ['Cordero con ciruelas|Lamb with plums', 'Cocido seis horas en horno de leña|Six hours in a wood oven', 12, 1],
      ['Hogaza con mantequilla de ajo|Loaf with garlic butter', 'Al centro de la mesa, para compartir|Center of the table, to share', 3, 2],
      ['Tabla de quesos viejos|Aged cheese board', 'Tres quesos de pastores de la sierra|Three cheeses from mountain shepherds', 8, 2],
      ['Tarta de nueces|Walnut tart', 'Con una cucharada de crema espesa|With a spoonful of thick cream', 5, 2],
      ['Cama compartida|Shared bed', 'Un jergón limpio en el dormitorio común|A clean pallet in the common dorm', 5, 3],
      ['Cuarto privado con chimenea|Private room with fireplace', 'Cerradura de llave y mantas dobles|Key lock and double blankets', 18, 3],
      ['Establo para caballos|Horse stable', 'Heno fresco y un cubo de avena|Fresh hay and a bucket of oats', 4, 3],
    ],
    fields: [
      text('patronName', 'Nombre o apodo|Name or nickname', { minLength: 2, maxLength: 40 }),
      num('party', 'Compañeros de mesa|Party size', 1, 12),
      sel('seat', 'Lugar preferido|Preferred spot', ['Junto al fuego|By the fire', 'Barra|Bar counter', 'Rincón oscuro|Dark corner']),
      pat('tabCode', 'Código de cuenta abierta|Open tab code', '^GD-[A-Z]\\d{3}$', 'GD-, una letra y tres dígitos, ej. GD-K204|GD-, one letter and three digits, e.g. GD-K204', false),
      chk('mounts', 'Llego con monturas|I am arriving with mounts'),
      area('rumor', 'Rumor que traés|A rumor you bring', 160),
    ],
    contact: ['Deuda de una noche|A night\'s debt', 'Pelea en el salón|Brawl in the common room', 'Contratar a un bardo|Hire a bard', 'Cuarto para un mes|A month-long room'],
    faq: [
      ['¿Hasta qué hora sirven?|How late do you serve?', 'Hasta que el último canto se apaga, normalmente pasada la medianoche.|Until the last song ends, usually past midnight.'],
      ['¿Se puede pagar con trueque?|Can I pay by barter?', 'Con piezas de caza, cueros o leña; el tabernero tasa al momento.|With game, hides or firewood; the innkeeper appraises on the spot.'],
      ['¿Admiten armas en el salón?|Are weapons allowed inside?', 'Las espadas se cuelgan en la entrada, las dagas pequeñas pueden quedar.|Swords hang at the door; small daggers may stay.'],
      ['¿Hay platos sin carne?|Any meatless dishes?', 'La sopa de cebolla, la tabla de quesos y las gachas de avena.|The onion soup, the cheese board and oat porridge.'],
      ['¿Dónde duerme mi caballo?|Where does my horse sleep?', 'En el establo trasero, con un mozo de guardia toda la noche.|In the rear stable with a stable hand on watch all night.'],
    ],
    posts: [
      ['El rumor del mes|Rumor of the month', 'Alguien vio un grifo volando sobre el molino.|Someone saw a griffin over the mill.', 'Tabernero Gorm Eldric'],
      ['Receta del estofado de cazador|Hunter\'s stew recipe', 'Seis horas de fuego y paciencia.|Six hours of fire and patience.', 'Cocinera Dagna Pell'],
      ['Canciones de barra: las cinco más pedidas|Bar songs: the top five requests', 'Con letra completa y coro.|With full lyrics and chorus.', 'Bardo Lysander Quill'],
    ],
    wiz: {
      title: 'Reservá una noche|Book a night',
      steps: [
        ['Cómo llegás|How you arrive', [rad('arrival', 'Cómo llegás|How you arrive', ['A pie|On foot', 'A caballo|On horseback'])]],
        ['Fecha y noches|Date and nights', [date('night', 'Fecha de llegada|Arrival date', 'noPast'), num('nightsStay', 'Noches|Nights', 1, 14)]],
        ['Monturas|Mounts', [num('horses', 'Cantidad de caballos|Number of horses', 1, 8)]],
        ['Cena|Dinner', [chk('dinner', 'Incluir cena de bienvenida|Include a welcome dinner')]],
      ],
      cond: ['arrival', 'on-horseback', ['horses']],
    },
    dash: { cols: ['Plato|Dish', 'Raciones servidas|Portions served', 'Noche|Night', 'Cobrado|Takings'], pool: ['Cerveza negra|Dark ale', 'Estofado del cazador|Hunter\'s stew', 'Cordero con ciruelas|Lamb with plums', 'Hogaza con ajo|Garlic loaf', 'Cuarto privado|Private room', 'Establo|Stable'], n: [4, 90], m: [30, 800] },
  },
  {
    id: 'biblioteca-grimorios-hoja-negra',
    name: 'Archivo de Grimorios Hoja Negra|Black Leaf Grimoire Archive',
    tag: 'Los libros muerden: pedí permiso antes de abrirlos|The books bite: ask permission before opening them',
    style: [250, 20, 'serif', 4, 'ornate'],
    cur: ['✦', 'TNT', 0, 'after'],
    nouns: ['grimorio|grimorios|grimoire|grimoires', 'lector|lectores|reader|readers', 'préstamo|préstamos|loan|loans', 'estante|estantes|shelf|shelves'],
    nav: ['Sala de lectura|Reading room', 'Mis volúmenes|My volumes', 'Firmar préstamo|Sign a loan', 'Catálogo del archivista|Archivist catalog', 'Notas al margen|Marginalia'],
    cats: ['Hechizos básicos|Basic spells', 'Conjuros prohibidos|Forbidden incantations', 'Historia de la magia|History of magic', 'Bestiarios|Bestiaries'],
    items: [
      ['Compendio de chispas|Compendium of Sparks', 'Primer libro de todo aprendiz|Every apprentice\'s first book', 12, 0],
      ['Manual de levitación|Levitation Manual', 'Ilustrado con tiras de papel flotante|Illustrated with floating paper strips', 14, 0],
      ['Los cuarenta sellos|The Forty Seals', 'Cada sello con su contrasello|Each seal with its counter-seal', 18, 0],
      ['Invocaciones de la sombra baja|Low Shadow Invocations', 'Se presta con un testigo y un cubo de agua|Lent with a witness and a bucket of water', 40, 1],
      ['El libro rojo del miedo|The Red Book of Fear', 'No leer solo ni después de cenar|Do not read alone or after dinner', 45, 1],
      ['Conjuros de un siglo|Spells of a Century', 'Páginas selladas con cera lacrada|Pages sealed with lacquer wax', 55, 1],
      ['Crónica de las siete guerras arcanas|Chronicle of the Seven Arcane Wars', 'Tres tomos con mapas plegables|Three volumes with folding maps', 25, 2],
      ['Genealogía de los magos|Genealogy of Mages', 'Quién enseñó a quién, y quién se peleó|Who taught whom, and who quarreled', 20, 2],
      ['Cómo se perdió la magia del norte|How the Northern Magic Was Lost', 'Una investigación que nadie esperaba|An investigation nobody expected', 22, 2],
      ['Bestiario de criaturas menores|Bestiary of Lesser Creatures', 'Hadas, duendes y gnomos con dibujos|Fairies, sprites and gnomes with drawings', 16, 3],
      ['Atlas de dragones|Dragon Atlas', 'Mapas de nidos con avisos de seguridad|Nest maps with safety notices', 28, 3],
      ['Guía de espectros de biblioteca|Guide to Library Ghosts', 'Cómo pedirles silencio con educación|How to ask them politely for silence', 14, 3],
    ],
    fields: [
      text('readerName', 'Nombre del lector|Reader name', { minLength: 3, maxLength: 60 }),
      pat('readerCard', 'Carnet de lector arcano|Arcane reader card', '^HN-\\d{6}$', 'HN- y seis dígitos, ej. HN-041873|HN- and six digits, e.g. HN-041873'),
      sel('clearance', 'Nivel de acceso|Clearance level', ['Público|Public', 'Aprendiz|Apprentice', 'Maestro|Master']),
      num('daysRequested', 'Días de préstamo|Loan days', 1, 30),
      chk('witness', 'Cuento con un testigo para libros prohibidos|I have a witness for forbidden books'),
      area('research', 'Tema de investigación|Research topic', 200),
    ],
    contact: ['Libro que susurra|A book that whispers', 'Página arrancada|Torn page', 'Acceso a la sala restringida|Restricted-room access', 'Donar un grimorio|Donate a grimoire'],
    faq: [
      ['¿Quién puede llevarse un grimorio?|Who may take a grimoire?', 'Quien tenga carnet vigente y nivel acorde al libro.|Anyone with a valid card and a level suited to the book.'],
      ['¿Qué pasa si un libro muerde?|What if a book bites?', 'Se registra el incidente y el archivista aplica el ungüento de la casa.|The incident is logged and the archivist applies the house ointment.'],
      ['¿Se puede copiar un hechizo?|May I copy a spell?', 'Sí, a mano y con tinta del archivo; las fotografías mágicas están prohibidas.|Yes, by hand with archive ink; magical photographs are banned.'],
      ['¿Hay horario nocturno?|Are there night hours?', 'La sala abre hasta medianoche, cuando los libros están más dóciles.|The room opens until midnight, when books are most docile.'],
      ['¿Cómo devuelvo un libro vencido?|How do I return an overdue book?', 'Se lleva a ventanilla sin abrir y se suspende el préstamo por una luna.|Bring it unopened to the desk; loans are suspended for one moon.'],
    ],
    posts: [
      ['Cómo abrir un libro rebelde|How to open a rebellious book', 'Cinco gestos y un silbido.|Five gestures and a whistle.', 'Archivista Selma Quarrel'],
      ['Tinta de nogal: receta del archivo|Walnut ink: the archive recipe', 'Para copiar sin quemar el papel.|For copying without scorching the page.', 'Archivista Selma Quarrel'],
      ['Los fantasmas lectores|The ghost readers', 'Tres presencias que vuelven cada otoño.|Three presences that return each autumn.', 'Lector Ambrosio Fell'],
    ],
    wiz: {
      title: 'Solicitar acceso a la sala restringida|Request restricted-room access',
      steps: [
        ['Estudio|Study', [rad('studyKind', 'Tipo de estudio|Study type', ['Historia|History', 'Conjuros|Incantations'])]],
        ['Duración|Duration', [date('startDay', 'Inicio de consulta|Consultation start', 'noPast'), num('weeks', 'Semanas de trabajo|Weeks of work', 1, 26)]],
        ['Aval|Endorsement', [text('mentor', 'Maestro que te avala|Endorsing master', { minLength: 3, maxLength: 60 })]],
        ['Compromiso|Pledge', [chk('pledge', 'Prometo no leer en voz alta|I promise not to read aloud', true)]],
      ],
      cond: ['studyKind', 'incantations', ['mentor']],
    },
    dash: { cols: ['Estante|Shelf', 'Préstamos|Loans', 'Fecha de registro|Logged date', 'Fianzas|Deposits'], pool: ['Hechizos básicos|Basic spells', 'Conjuros prohibidos|Forbidden incantations', 'Historia de la magia|History of magic', 'Bestiarios|Bestiaries', 'Atlas de dragones|Dragon atlas', 'Crónicas|Chronicles'], n: [2, 60], m: [0, 900] },
  },
  {
    id: 'establo-unicornios-alba',
    name: 'Establo de Unicornios Alba Dorada|Golden Dawn Unicorn Stables',
    tag: 'Cuidamos astas, crines y el mal humor de los jueves|We care for horns, manes and Thursday moods',
    style: [180, 330, 'rounded', 14, 'playful'],
    cur: ['✿', 'FLR', 0, 'after'],
    nouns: ['servicio|servicios|service|services', 'jinete|jinetes|rider|riders', 'reserva|reservas|booking|bookings', 'pista|pistas|track|tracks'],
    nav: ['Cuadras|Stables', 'Mi cabalgata|My ride', 'Reservar paseo|Book a ride', 'Libro del caballerizo|Stablemaster ledger', 'Cuaderno de crines|Mane diary'],
    cats: ['Paseos|Rides', 'Cuidado y limpieza|Care and grooming', 'Clases de monta|Riding lessons', 'Alimentos y accesorios|Feed and gear'],
    items: [
      ['Paseo al amanecer|Dawn ride', 'Cuarenta minutos sobre el prado de rocío|Forty minutes across the dewy meadow', 25, 0],
      ['Paseo por el bosque de luz|Light-forest ride', 'Con parada en un claro de hadas|With a stop at a fairy clearing', 40, 0],
      ['Cabalgata nocturna|Night ride', 'Con lámpara de luciérnagas, solo para adultos|With firefly lamps, adults only', 55, 0],
      ['Baño con jabón de lavanda|Lavender-soap bath', 'Para astas opacas y crines enredadas|For dull horns and tangled manes', 15, 1],
      ['Pulido de asta|Horn polishing', 'Con cera de abeja y paño de lana|With beeswax and a wool cloth', 12, 1],
      ['Trenzado de crin con flores|Flower mane braiding', 'Estilos de festival y de boda|Festival and wedding styles', 18, 1],
      ['Primera clase de monta|First riding lesson', 'En picadero cercado y con casco|In a fenced ring with a helmet', 30, 2],
      ['Clase de salto bajo|Low jump class', 'Obstáculos de arco iris, treinta centímetros|Rainbow obstacles, thirty centimeters high', 35, 2],
      ['Curso de cuidado básico|Basic care course', 'Cuatro sábados con práctica en el establo|Four Saturdays with hands-on stable work', 90, 2],
      ['Avena con miel de flores|Flower-honey oats', 'Saco de 10 kg, sin aditivos|10 kg sack, no additives', 22, 3],
      ['Cepillo de cerdas suaves|Soft-bristle brush', 'Mango de madera clara|Pale wood handle', 9, 3],
      ['Manta de lana de nube|Cloud-wool blanket', 'Liviana y térmica, lavable|Light, warm and washable', 44, 3],
    ],
    fields: [
      text('riderName', 'Nombre del jinete|Rider name', { minLength: 2, maxLength: 50 }),
      num('riderWeight', 'Peso en kilos (límite 90)|Weight in kilos (limit 90)', 20, 90),
      sel('experience', 'Experiencia|Experience', ['Nunca monté|Never ridden', 'Algunas veces|A few times', 'Soy jinete|I am a rider']),
      pat('licenseNo', 'Licencia de jinete|Rider license', '^UNI-\\d{4}$', 'UNI- y cuatro dígitos, ej. UNI-5120|UNI- and four digits, e.g. UNI-5120', false),
      chk('pure', 'Declaro tener corazón puro (requisito del establo)|I declare a pure heart (stable requirement)', true),
    ],
    contact: ['Cancelar por lluvia|Cancel due to rain', 'Unicornio inquieto|A restless unicorn', 'Fiesta de cumpleaños|Birthday party', 'Pensión de un unicornio|Boarding a unicorn'],
    faq: [
      ['¿Los unicornios muerden?|Do unicorns bite?', 'Nunca muerden, pero a veces les gusta pisar zapatillas nuevas.|They never bite, but sometimes like stepping on new shoes.'],
      ['¿Puedo montar sin experiencia?|Can I ride with no experience?', 'Sí, siempre con un guía a pie y casco incluido.|Yes, always with a guide on foot and a helmet included.'],
      ['¿Hay un peso máximo?|Is there a weight limit?', 'Noventa kilos por jinete, incluido el equipo.|Ninety kilos per rider, gear included.'],
      ['¿Qué pasa si llueve?|What if it rains?', 'Se reprograma gratis o se hace la clase en el picadero cubierto.|It is rescheduled free or held in the covered ring.'],
      ['¿Aceptan niños?|Do you accept children?', 'Desde los seis años en paseos de veinte minutos.|From age six on twenty-minute rides.'],
    ],
    posts: [
      ['Por qué los unicornios odian los martes|Why unicorns dislike Tuesdays', 'Una teoría con evidencia de avena.|A theory backed by oat evidence.', 'Caballerizo Tibor Ness'],
      ['Primer galope: lo que sentí|First gallop: what I felt', 'Una jinete cuenta cómo perdió el miedo.|A rider tells how she lost her fear.', 'Marcela Ibáñez'],
      ['Cómo trenzar la crin para un festival|Braiding the mane for a festival', 'Tres estilos paso a paso.|Three styles step by step.', 'Estilista Nuria Ferrel'],
    ],
    wiz: {
      title: 'Planificá tu primer paseo|Plan your first ride',
      steps: [
        ['Experiencia|Experience', [rad('rideLevel', 'Tu experiencia|Your experience', ['Primera vez|First time', 'Ya monté antes|Rode before'])]],
        ['Día y duración|Day and length', [date('rideDay', 'Día del paseo|Ride day', 'noPast'), num('minutes', 'Minutos de paseo|Ride minutes', 20, 120)]],
        ['Antecedentes|Background', [area('rideHistory', 'Dónde y con qué caballo montaste|Where and on which horse you rode', 200)]],
        ['Acompañantes|Companions', [chk('photo', 'Quiero foto de recuerdo|I want a souvenir photo')]],
      ],
      cond: ['rideLevel', 'rode-before', ['rideHistory']],
    },
    dash: { cols: ['Servicio|Service', 'Jinetes atendidos|Riders served', 'Fecha|Date', 'Ingresos|Income'], pool: ['Paseo al amanecer|Dawn ride', 'Bosque de luz|Light forest', 'Cabalgata nocturna|Night ride', 'Pulido de asta|Horn polish', 'Primera clase|First lesson', 'Curso de cuidado|Care course'], n: [2, 30], m: [30, 1100] },
  },
  {
    id: 'cartografos-reinos-brujula-rota',
    name: 'Cartógrafos de la Brújula Rota|The Broken Compass Cartographers',
    tag: 'Mapas de lugares que existen y de algunos que todavía no|Maps of places that exist and some that do not yet',
    style: [38, 200, 'serif', 4, 'ornate'],
    cur: ['⌖', 'PGM', 0, 'after'],
    nouns: ['mapa|mapas|map|maps', 'explorador|exploradores|explorer|explorers', 'pedido|pedidos|order|orders', 'región|regiones|region|regions'],
    nav: ['Mesa de dibujo|Drawing table', 'Mi rollo de mapas|My map roll', 'Pedir un mapa|Order a map', 'Registro de rutas|Route register', 'Cuaderno de ruta|Field journal'],
    cats: ['Mapas de reinos|Realm maps', 'Mapas de ruinas|Ruin maps', 'Cartas náuticas|Sea charts', 'Instrumentos|Instruments'],
    items: [
      ['Mapa del reino de Valdora|Map of the Valdora kingdom', 'Caminos, torres y ríos, a escala 1:50|Roads, towers and rivers at 1:50 scale', 55, 0],
      ['Atlas de las tierras bajas|Lowlands atlas', 'Veintidós hojas encuadernadas|Twenty-two bound sheets', 130, 0],
      ['Plano de la capital|Capital city plan', 'Cada calle con su nombre y su leyenda|Every street with its name and legend', 38, 0],
      ['Mapa de las ruinas de Karn-Eth|Karn-Eth ruins map', 'Salas, trampas y salidas ocultas|Rooms, traps and hidden exits', 75, 1],
      ['Croquis de catacumbas|Catacomb sketch', 'Pasadizos hasta el tercer nivel|Passages down to the third level', 40, 1],
      ['Carta del templo sumergido|Sunken temple chart', 'Con las corrientes del bajo fondo|With the deep-water currents', 85, 1],
      ['Carta náutica del mar Quebrado|Broken Sea nautical chart', 'Sondas, arrecifes y faros|Soundings, reefs and lighthouses', 95, 2],
      ['Derrotero de islas menores|Minor islands sailing guide', 'Anclajes y aguadas conocidas|Known anchorages and water sources', 60, 2],
      ['Corrientes del invierno|Winter currents', 'Hoja plegable en papel encerado|Folding sheet in waxed paper', 35, 2],
      ['Brújula que apunta a casa|A compass that points home', 'Latón y cristal, un poco terca|Brass and glass, slightly stubborn', 120, 3],
      ['Escuadra y compás de bolsillo|Pocket square and compass', 'Para trazar caminos nuevos|For drawing new roads', 28, 3],
      ['Tinta de viaje, seis colores|Travel ink, six colors', 'Seca en un minuto bajo la lluvia|Dries in a minute in the rain', 18, 3],
    ],
    fields: [
      text('explorerName', 'Nombre del explorador|Explorer name', { minLength: 3, maxLength: 60 }),
      sel('terrain', 'Terreno principal|Main terrain', ['Montaña|Mountain', 'Bosque|Forest', 'Desierto|Desert', 'Mar|Sea']),
      num('expeditionDays', 'Días de expedición|Expedition days', 1, 365),
      pat('regionCode', 'Código de región|Region code', '^RG-[A-Z]{2}\\d{2}$', 'RG-, dos letras y dos dígitos, ej. RG-VD12|RG-, two letters and two digits, e.g. RG-VD12'),
      chk('unexplored', 'Mi destino todavía no figura en mapas|My destination is not on any map yet'),
      area('route', 'Ruta que pensás seguir|Route you plan to follow', 200),
    ],
    contact: ['Mapa desactualizado|Outdated map', 'Región sin cartografiar|Unmapped region', 'Mapa personalizado|Custom map', 'Ser cartógrafo|Become a cartographer'],
    faq: [
      ['¿Qué tan fiables son los mapas?|How reliable are the maps?', 'Se verifican en terreno cada cinco años y marcan la fecha del levantamiento.|They are field-checked every five years and carry the survey date.'],
      ['¿Qué hago si el mapa está mal?|What if the map is wrong?', 'Mandanos un croquis y un descuento en tu próximo mapa.|Send us a sketch and get a discount on your next map.'],
      ['¿Hacen mapas del futuro?|Do you make maps of the future?', 'Solo del futuro cercano: caminos en obra y puentes en construcción.|Only the near future: roads under work and bridges being built.'],
      ['¿Vienen impresos?|Are they printed?', 'Dibujados a mano sobre pergamino o reproducidos en grabado.|Hand-drawn on parchment or reproduced as an engraving.'],
      ['¿Cuánto tarda un mapa a pedido?|How long does a custom map take?', 'Tres semanas si la zona está explorada, tres meses si no.|Three weeks if the area is explored, three months if not.'],
    ],
    posts: [
      ['Cómo leer curvas de nivel|How to read contour lines', 'La montaña, explicada con anillos.|The mountain explained with rings.', 'Cartógrafa Rosalind Vey'],
      ['La isla que no aparece|The island that does not appear', 'Una historia de un mapa y de un naufragio.|A story of a map and a shipwreck.', 'Cartógrafo Anselm Dray'],
      ['Tintas de viaje: una guía|Travel inks: a guide', 'Cuál se corre y cuál se queda.|Which one runs and which one stays.', 'Cartógrafa Rosalind Vey'],
    ],
    wiz: {
      title: 'Encargá un mapa|Commission a map',
      steps: [
        ['Tipo de terreno|Terrain type', [sel('mapTerrain', 'Terreno a cartografiar|Terrain to map', ['Tierra firme|Land', 'Mar|Sea', 'Ruinas|Ruins'])]],
        ['Fecha y escala|Date and scale', [date('mapDeadline', 'Plazo|Deadline', 'noPast'), num('km', 'Kilómetros de lado|Kilometers across', 1, 500)]],
        ['Ruinas|Ruins', [area('ruinNotes', 'Qué sabés de las ruinas|What you know about the ruins', 250)]],
        ['Entrega|Delivery', [chk('parchment', 'Prefiero pergamino|I prefer parchment')]],
      ],
      cond: ['mapTerrain', 'ruins', ['ruinNotes']],
    },
    dash: { cols: ['Mapa|Map', 'Copias emitidas|Copies issued', 'Fecha de entrega|Delivery date', 'Cobrado|Charged'], pool: ['Reino de Valdora|Valdora kingdom', 'Ruinas de Karn-Eth|Karn-Eth ruins', 'Mar Quebrado|Broken Sea', 'Plano de la capital|Capital plan', 'Atlas de tierras bajas|Lowlands atlas', 'Catacumbas|Catacombs'], n: [1, 50], m: [35, 1400] },
  },
  {
    id: 'posada-luna-cuarto-creciente',
    name: 'Posada del Cuarto Creciente|Waxing Quarter Inn',
    tag: 'Camas que huelen a lavanda y a camino|Beds that smell of lavender and the road',
    style: [270, 45, 'serif', 8, 'ornate'],
    cur: ['☽', 'LNP', 0, 'after'],
    nouns: ['cama|camas|bed|beds', 'viajero|viajeros|traveler|travelers', 'estadía|estadías|stay|stays', 'cuarto|cuartos|room|rooms'],
    nav: ['Portal de entrada|Entrance hall', 'Mi cuarto|My room', 'Reservar noche|Book a night', 'Libro de huéspedes|Guest book', 'Voces del camino|Voices of the road'],
    cats: ['Cuartos|Rooms', 'Comidas|Meals', 'Servicios de camino|Road services', 'Rituales y descanso|Rituals and rest'],
    items: [
      ['Cuarto del búho|Owl room', 'Cama doble, vista al patio de los álamos|Double bed, poplar courtyard view', 14, 0],
      ['Cuarto de la luciérnaga|Firefly room', 'Dos camas y farol que no se apaga solo|Two beds and a lantern that will not go out on its own', 16, 0],
      ['Dormitorio de los peregrinos|Pilgrim dormitory', 'Ocho camas, ideal para grupos|Eight beds, ideal for groups', 5, 0],
      ['Cena del viajero|Traveler\'s supper', 'Sopa, pan y un vaso de vino aguado|Soup, bread and a glass of watered wine', 3, 1],
      ['Desayuno de camino|Road breakfast', 'Gachas con frutas secas|Porridge with dried fruit', 2, 1],
      ['Cesta de viaje|Trail hamper', 'Queso, pan y manzanas para tres días|Cheese, bread and apples for three days', 5, 1],
      ['Herrado de caballo|Horse shoeing', 'Por cuatro herraduras, en el día|Four shoes, done same day', 6, 2],
      ['Lavado y remiendo de ropa|Laundry and mending', 'Costuras y botones, en una noche|Seams and buttons overnight', 3, 2],
      ['Mensajero a la próxima ciudad|Messenger to the next town', 'Entrega de cartas en un día de marcha|Letters delivered within a day\'s march', 4, 2],
      ['Baño caliente|Hot bath', 'Tina de cobre y toalla tibia|Copper tub and a warm towel', 2, 3],
      ['Infusión de manzanilla nocturna|Night chamomile infusion', 'Para dormir de un tirón|To sleep in one stretch', 1, 3],
      ['Lectura de estrellas|Star reading', 'Presagios de la próxima jornada|Omens for tomorrow\'s journey', 3, 3],
    ],
    fields: [
      text('travelerName', 'Nombre del viajero|Traveler name', { minLength: 2, maxLength: 50 }),
      num('nights', 'Noches de estadía|Nights of stay', 1, 14),
      sel('route', 'Camino que seguís|Road you take', ['Norte|North', 'Sur|South', 'Este|East', 'Oeste|West']),
      pat('travelPass', 'Salvoconducto de viaje|Travel pass', '^SC\\d{3}-[A-Z]{2}$', 'SC, tres dígitos, guion y dos letras, ej. SC512-LN|SC, three digits, a dash and two letters, e.g. SC512-LN', false),
      chk('animals', 'Viajo con animales|I travel with animals'),
    ],
    contact: ['Objeto olvidado|Lost belongings', 'Cuarto ruidoso|Noisy room', 'Cuarto para una caravana|Room for a caravan', 'Cuenta pendiente|Open account'],
    faq: [
      ['¿A qué hora se cierran las puertas?|When do the doors close?', 'A medianoche; si llegás tarde, tocá tres veces y esperá.|At midnight; if you arrive late, knock three times and wait.'],
      ['¿Se puede dormir en el pajar?|May I sleep in the hayloft?', 'Sí, por un cobre, con manta y sin pipas.|Yes, for a copper, with a blanket and no pipes.'],
      ['¿Hay agua caliente?|Is there hot water?', 'Tinas por turnos desde el atardecer.|Tubs by turns from dusk.'],
      ['¿Puedo dejar mi caballo unos días?|Can I leave my horse a few days?', 'Pensión en el establo, a dos cobres por día.|Stable board at two coppers a day.'],
      ['¿Cobran por contar historias?|Do you charge for telling stories?', 'Al revés: el que cuenta una buena cena gratis.|The opposite: whoever tells a good one eats free.'],
    ],
    posts: [
      ['Cinco caminos y sus peajes|Five roads and their tolls', 'Qué esperar al salir de la posada.|What to expect when you leave the inn.', 'Posadera Wilda Marrow'],
      ['La cama que no existe|The bed that does not exist', 'Una historia de viajeros que soñaron con la misma.|A story of travelers who dreamed of the same one.', 'Viajero Dorian Pike'],
      ['Receta de la sopa del viajero|The traveler\'s soup recipe', 'Con lo que sobra en la despensa.|With whatever is left in the pantry.', 'Cocinero Eldon Brask'],
    ],
    wiz: {
      title: 'Reservar para una caravana|Book for a caravan',
      steps: [
        ['Grupo|Group', [rad('groupType', 'Tipo de grupo|Group type', ['Viajero suelto|Lone traveler', 'Caravana de mercaderes|Merchant caravan'])]],
        ['Fecha y personas|Date and people', [date('arrivalDay', 'Día de llegada|Arrival day', 'noPast'), num('people', 'Personas|People', 1, 40)]],
        ['Carretas|Wagons', [num('wagons', 'Cantidad de carretas|Number of wagons', 1, 15)]],
        ['Comida|Meals', [chk('mealsIncluded', 'Incluir cena y desayuno|Include supper and breakfast')]],
      ],
      cond: ['groupType', 'merchant-caravan', ['wagons']],
    },
    dash: { cols: ['Cuarto|Room', 'Noches reservadas|Nights booked', 'Fecha de llegada|Arrival date', 'Pagos|Payments'], pool: ['Cuarto del búho|Owl room', 'Cuarto de la luciérnaga|Firefly room', 'Dormitorio de peregrinos|Pilgrim dormitory', 'Cena del viajero|Traveler\'s supper', 'Herrado|Horse shoeing', 'Baño caliente|Hot bath'], n: [1, 14], m: [3, 140] },
  },
  {
    id: 'gremio-bardos-cuerda-viva',
    name: 'Gremio de Bardos Cuerda Viva|Living String Bards\' Guild',
    tag: 'Si no suena, no es nuestro|If it does not ring, it is not ours',
    style: [330, 40, 'rounded', 10, 'playful'],
    cur: ['♪', 'NTA', 0, 'after'],
    nouns: ['actuación|actuaciones|performance|performances', 'bardo|bardos|bard|bards', 'contratación|contrataciones|booking|bookings', 'estilo|estilos|style|styles'],
    nav: ['Escenario|Stage', 'Mi repertorio|My repertoire', 'Contratar bardo|Hire a bard', 'Cuaderno del tesorero|Treasurer\'s ledger', 'Letras y rimas|Lyrics and rhymes'],
    cats: ['Canciones épicas|Epic songs', 'Música de taberna|Tavern music', 'Ceremonias|Ceremonies', 'Instrumentos|Instruments'],
    items: [
      ['Balada del último dragón|Ballad of the Last Dragon', 'Veinte estrofas con coro del público|Twenty stanzas with an audience chorus', 25, 0],
      ['Canto de guerra y pan|War-and-Bread Chant', 'Mitad marcha, mitad receta|Half march, half recipe', 18, 0],
      ['Elegía del herrero sordo|Elegy of the Deaf Smith', 'Para quien quiere llorar con dignidad|For those who wish to weep with dignity', 22, 0],
      ['Tabernas en ronda|Tavern Round', 'Tres canciones para brindar|Three songs for toasting', 15, 1],
      ['Jarana del carro de feria|Fairground Cart Jig', 'Violín y pandero, pensada para bailar|Fiddle and tambourine, made for dancing', 14, 1],
      ['Coplas con picardía|Cheeky Couplets', 'Se cantan a dúo y con guiño|Sung as a duet with a wink', 12, 1],
      ['Música para boda|Wedding music', 'Procesión, brindis y vals de salida|Procession, toast and exit waltz', 90, 2],
      ['Canto fúnebre breve|Brief funeral chant', 'Un homenaje de cinco minutos|A five-minute tribute', 60, 2],
      ['Himno de gremio|Guild anthem', 'Letra y música a medida, tres ensayos|Custom lyrics and music, three rehearsals', 140, 2],
      ['Laúd de nogal|Walnut lute', 'Caja ligera y cuerdas de tripa|Light body and gut strings', 210, 3],
      ['Flauta de hueso de ciervo|Deer-bone flute', 'Seis agujeros y un tono dulce|Six holes and a sweet tone', 45, 3],
      ['Pandero de piel de cabra|Goatskin tambourine', 'Campanillas de latón|Brass jingles', 28, 3],
    ],
    fields: [
      text('bardName', 'Nombre artístico|Stage name', { minLength: 2, maxLength: 50 }),
      sel('instrument', 'Instrumento principal|Main instrument', ['Laúd|Lute', 'Flauta|Flute', 'Voz|Voice', 'Tambor|Drum']),
      num('repertoireSize', 'Canciones en repertorio|Songs in repertoire', 5, 400),
      pat('guildSeal', 'Sello del gremio|Guild seal', '^BG-\\d{3}[A-Z]$', 'BG-, tres dígitos y una letra, ej. BG-204K|BG-, three digits and a letter, e.g. BG-204K'),
      num('yearsPlaying', 'Años tocando en público|Years playing in public', 0, 70),
      chk('travels', 'Estoy dispuesto a viajar|I am willing to travel'),
    ],
    contact: ['Contratar un coro|Hire a choir', 'Cambiar la fecha de un acto|Change a show date', 'Derechos de una canción|Song rights', 'Audición|Audition'],
    faq: [
      ['¿Cómo se me paga?|How am I paid?', 'El gremio cobra el contrato y gira el setenta por ciento en tres días.|The guild collects the fee and sends seventy percent in three days.'],
      ['¿Se puede improvisar?|May I improvise?', 'Sí, mientras la canción no cambie de tema ni de rey.|Yes, as long as the song does not change theme or king.'],
      ['¿Qué incluye una actuación en una boda?|What does a wedding gig include?', 'Hasta cuatro horas de música y dos descansos con agua y pan.|Up to four hours of music with two breaks and bread and water.'],
      ['¿Puedo ser bardo si desafino?|Can I be a bard if I am off-key?', 'Se desafina, se estudia y se vuelve a intentar; pedimos constancia.|You go off-key, study and retry; we ask for persistence.'],
      ['¿Alquilan instrumentos?|Do you rent instruments?', 'Laúdes y flautas por una moneda semanal con fianza.|Lutes and flutes for a coin a week with deposit.'],
    ],
    posts: [
      ['Tres consejos para afinar un laúd|Three tips for tuning a lute', 'Oído, humedad y paciencia.|Ear, humidity and patience.', 'Bardo Orsino Vale'],
      ['La canción más pedida de 1203|The most requested song of 1203', 'Quién la compuso y por qué nadie recuerda el final.|Who composed it and why nobody remembers the ending.', 'Bardo Orsino Vale'],
      ['Entrevista: una cantora sin voz|Interview: a singer without a voice', 'Cómo canta con las manos.|How she sings with her hands.', 'Cronista Elodie Brandt'],
    ],
    wiz: {
      title: 'Contratar una actuación|Book a performance',
      steps: [
        ['Ocasión|Occasion', [sel('eventKind', 'Tipo de evento|Event type', ['Boda|Wedding', 'Fiesta de pueblo|Village festival', 'Reunión privada|Private gathering'])]],
        ['Fecha y duración|Date and length', [date('gigDay', 'Día del evento|Event day', 'noPast'), num('hours', 'Horas de música|Hours of music', 1, 8)]],
        ['Boda|Wedding', [text('couple', 'Nombres de los novios|Couple\'s names', { minLength: 3, maxLength: 80 })]],
        ['Repertorio|Repertoire', [area('requests', 'Canciones que querés escuchar|Songs you want to hear', 250)]],
      ],
      cond: ['eventKind', 'wedding', ['couple']],
    },
    dash: { cols: ['Actuación|Performance', 'Bardos contratados|Bards hired', 'Fecha|Date', 'Cachet|Fee'], pool: ['Boda del molino|Mill wedding', 'Feria de otoño|Autumn fair', 'Taberna del Grifo|Griffin tavern', 'Funeral breve|Brief funeral', 'Himno de gremio|Guild anthem', 'Fiesta de cosecha|Harvest party'], n: [1, 7], m: [20, 600] },
  },
  {
    id: 'vivero-hadas-rocio-claro',
    name: 'Vivero de Hadas Rocío Claro|Clear Dew Fairy Nursery',
    tag: 'Plantas que ya vienen con huéspedes|Plants that arrive with tenants',
    style: [100, 320, 'rounded', 14, 'playful'],
    cur: ['❀', 'PTL', 0, 'after'],
    nouns: ['planta|plantas|plant|plants', 'jardinero|jardineros|gardener|gardeners', 'pedido|pedidos|order|orders', 'colección|colecciones|collection|collections'],
    nav: ['Invernadero|Greenhouse', 'Mi cesta|My basket', 'Pagar y empacar|Pay and pack', 'Cuaderno del vivero|Nursery log', 'Hojas de otoño|Autumn leaves'],
    cats: ['Plantas con hada|Plants with a fairy', 'Hierbas y aromáticas|Herbs and aromatics', 'Flores de luna|Moon flowers', 'Macetas y accesorios|Pots and gear'],
    items: [
      ['Helecho con hada residente|Fern with resident fairy', 'Un hada joven, algo tímida|A young, somewhat shy fairy', 45, 0],
      ['Violeta con dos duendes|Violet with two sprites', 'Pequeñas disputas por la tierra|Small disputes over soil', 38, 0],
      ['Bonsái de olmo con hada anciana|Elm bonsai with an elderly fairy', 'Da consejos si se la escucha|Gives advice if you listen', 90, 0],
      ['Albahaca de rocío|Dew basil', 'Hojas grandes, aroma intenso|Large leaves, intense aroma', 6, 1],
      ['Menta de arroyo|Brook mint', 'Crece rápido, cuidala de otras macetas|Spreads fast, keep it from other pots', 5, 1],
      ['Tomillo de roca|Rock thyme', 'Resistente a sequías y a visitas|Hardy against droughts and visitors', 6, 1],
      ['Lunaria nocturna|Night moonwort', 'Abre al caer el sol|Opens at sundown', 14, 2],
      ['Dama de noche perfumada|Fragrant night jasmine', 'Se huele a tres cuadras|Smelled from three blocks away', 16, 2],
      ['Orquídea de cristal|Crystal orchid', 'Pétalos casi transparentes|Almost transparent petals', 34, 2],
      ['Maceta de arcilla con puerta|Clay pot with a door', 'Entrada para visitas pequeñas|Entrance for small visitors', 20, 3],
      ['Regadera de cobre|Copper watering can', 'Pico largo para helechos|Long spout for ferns', 24, 3],
      ['Tierra enriquecida con musgo|Moss-enriched soil', 'Bolsa de 10 litros, sin plagas|10-liter bag, pest-free', 9, 3],
    ],
    fields: [
      text('gardenerName', 'Nombre del jardinero|Gardener name', { minLength: 2, maxLength: 50 }),
      sel('light', 'Luz de tu jardín|Garden light', ['Sol pleno|Full sun', 'Media sombra|Partial shade', 'Sombra|Shade']),
      num('gardenArea', 'Superficie en metros cuadrados|Area in square meters', 1, 5000),
      pat('fairyPermit', 'Permiso de hadas|Fairy permit', '^HD-\\d{2}-[A-Z]{2}$', 'HD-, dos dígitos, guion y dos letras, ej. HD-07-RC|HD-, two digits, a dash and two letters, e.g. HD-07-RC', false),
      chk('pets', 'Tengo gatos en el jardín|There are cats in the garden'),
      area('wishes', 'Qué esperás de tu jardín|What you hope for your garden', 200),
    ],
    contact: ['Hada que se fue|A fairy that left', 'Planta enferma|A sick plant', 'Diseño de jardín|Garden design', 'Mayorista|Wholesale'],
    faq: [
      ['¿Las hadas son reales?|Are the fairies real?', 'Dejamos que cada cliente lo decida; la tierra, en cambio, es auténtica.|We let each customer decide; the soil, however, is genuine.'],
      ['¿Qué pasa si el hada se va?|What if the fairy leaves?', 'Reponemos la planta sin cargo; el hada, no prometemos.|We replace the plant free; the fairy, we cannot promise.'],
      ['¿Cómo se riegan las lunarias?|How are moonworts watered?', 'Con agua de lluvia y al atardecer.|With rainwater and at dusk.'],
      ['¿Hacen envíos?|Do you ship?', 'Dentro de la región, en cajas ventiladas y con humedad controlada.|Within the region, in ventilated boxes with controlled humidity.'],
      ['¿Hay plantas seguras para gatos?|Any cat-safe plants?', 'Sí, están marcadas con una patita en la ficha.|Yes, they are marked with a paw on the listing.'],
    ],
    posts: [
      ['Cómo atraer a un hada al balcón|How to lure a fairy to your balcony', 'Poco azúcar, mucha paciencia.|A little sugar and plenty of patience.', 'Jardinera Aurelia Fenn'],
      ['Plantas de luna: calendario|Moon plants: a calendar', 'Cuándo sembrar y cuándo dejarlas dormir.|When to sow and when to let them sleep.', 'Jardinera Aurelia Fenn'],
      ['La maceta con puertita|The pot with a little door', 'Historia de un invento y sus inquilinos.|The story of an invention and its tenants.', 'Artesano Bruno Leaf'],
    ],
    wiz: {
      title: 'Diseñá tu rincón verde|Design your green nook',
      steps: [
        ['Lugar|Place', [rad('placeKind', 'Dónde va a vivir la planta|Where the plant will live', ['Interior|Indoors', 'Jardín|Garden'])]],
        ['Presupuesto y fecha|Budget and date', [num('plantBudget', 'Presupuesto|Budget', 5, 500), date('plantDay', 'Entrega deseada|Desired delivery', 'noPast')]],
        ['Jardín|Garden', [num('plotSize', 'Metros cuadrados disponibles|Available square meters', 1, 2000)]],
        ['Hada|Fairy', [chk('wantFairy', 'Quiero una planta con hada residente|I want a plant with a resident fairy')]],
      ],
      cond: ['placeKind', 'garden', ['plotSize']],
    },
    dash: { cols: ['Planta|Plant', 'Unidades vendidas|Units sold', 'Fecha de venta|Sale date', 'Ingresos|Income'], pool: ['Helecho con hada|Fern with fairy', 'Albahaca|Basil', 'Lunaria|Moonwort', 'Orquídea de cristal|Crystal orchid', 'Maceta con puerta|Clay pot with door', 'Regadera de cobre|Copper watering can'], n: [2, 70], m: [30, 2100] },
  },
  {
    id: 'casa-subastas-reliquias-eco',
    name: 'Casa de Subastas Reliquias del Eco|Echo Relics Auction House',
    tag: 'Lo que fue de alguien, ahora puede ser tuyo|What was once someone\'s may now be yours',
    style: [350, 45, 'serif', 4, 'ornate'],
    cur: ['◉', 'CRN', 0, 'after'],
    nouns: ['lote|lotes|lot|lots', 'postor|postores|bidder|bidders', 'puja|pujas|bid|bids', 'sala|salas|hall|halls'],
    nav: ['Sala de subastas|Auction floor', 'Mis pujas|My bids', 'Confirmar puja|Confirm bid', 'Libro del martillero|Auctioneer\'s ledger', 'Historias de reliquias|Relic stories'],
    cats: ['Armas y armaduras|Arms and armor', 'Joyas y amuletos|Jewels and amulets', 'Libros y pergaminos|Books and scrolls', 'Curiosidades|Curiosities'],
    items: [
      ['Espada del rey sin nombre|Sword of the Nameless King', 'Hoja sin filo por una leyenda de paz|A dull blade due to a legend of peace', 5200, 0],
      ['Yelmo del centinela|The Sentinel\'s helm', 'Muy abollado, sin dueño conocido|Heavily dented, owner unknown', 1800, 0],
      ['Escudo de la gran retirada|Shield of the Great Retreat', 'Pintado con un escudo que nadie reconoce|Painted with a crest nobody recognizes', 2200, 0],
      ['Collar de la tercera luna|Third Moon necklace', 'Zafiros que brillan con la marea|Sapphires that glow with the tide', 6400, 1],
      ['Anillo del mensajero perdido|Lost Messenger\'s ring', 'Grabado con una dirección que no existe|Engraved with an address that does not exist', 1500, 1],
      ['Amuleto de la suerte parcial|Partial luck amulet', 'Funciona en martes y feriados|Works on Tuesdays and holidays', 750, 1],
      ['Pergamino del tratado del lago|Lake Treaty scroll', 'Firmado por tres reyes y un pato|Signed by three kings and a duck', 3100, 2],
      ['Grimorio del jardinero astral|Astral Gardener\'s grimoire', 'Notas al margen con recetas de sopa|Margin notes with soup recipes', 2700, 2],
      ['Mapa de un tesoro ya cobrado|Map to a treasure already claimed', 'Valor histórico, valor emocional|Historic value, sentimental value', 900, 2],
      ['Reloj que marca otra hora|Clock that tells another hour', 'Nadie sabe de qué mundo es|Nobody knows which world it keeps', 1250, 3],
      ['Silla del trono prestado|Borrowed throne chair', 'Dos patas originales y dos de reposición|Two original legs and two replacements', 3300, 3],
      ['Caja de música con una melodía triste|Music box with a sad tune', 'La tapa se cierra sola al amanecer|The lid closes itself at dawn', 480, 3],
    ],
    fields: [
      text('bidderName', 'Nombre del postor|Bidder name', { minLength: 3, maxLength: 60 }),
      pat('paddleNumber', 'Número de paleta|Paddle number', '^PL-\\d{3}$', 'PL- y tres dígitos, ej. PL-045|PL- and three digits, e.g. PL-045'),
      num('maxBid', 'Puja máxima en coronas|Maximum bid in crowns', 50, 100000),
      sel('paymentMode', 'Forma de pago|Payment method', ['Oro en mano|Gold in hand', 'Letra de cambio|Bill of exchange', 'Depósito en bóveda|Vault deposit']),
      chk('insured', 'Quiero seguro de transporte|I want transport insurance'),
      area('provenance', 'Interés específico en el lote|Specific interest in the lot', 200),
    ],
    contact: ['Tasar una reliquia|Appraise a relic', 'Reclamo por un lote|Lot dispute', 'Vender en la casa|Sell with us', 'Envío a otro reino|Shipping to another realm'],
    faq: [
      ['¿Cómo sé si una reliquia es auténtica?|How do I know a relic is authentic?', 'Tres peritos independientes firman el certificado de cada lote.|Three independent experts sign each lot\'s certificate.'],
      ['¿Hay comisión del comprador?|Is there a buyer\'s premium?', 'Sí, del doce por ciento sobre el martillo.|Yes, twelve percent over the hammer price.'],
      ['¿Puedo pujar en ausencia?|Can I bid in absentia?', 'Con carta lacrada o por mensajero hasta una hora antes.|By sealed letter or messenger until one hour before.'],
      ['¿Qué pasa si el objeto está maldito?|What if the object is cursed?', 'Se declara en el catálogo y se vende con aviso y sin devolución.|It is stated in the catalog and sold with warning and no return.'],
      ['¿Aceptan consignaciones?|Do you accept consignments?', 'Sí, tasamos sin cargo y cobramos un diez por ciento si se vende.|Yes, we appraise free and charge ten percent if it sells.'],
    ],
    posts: [
      ['La espada sin filo|The dull sword', 'Por qué vale más que una afilada.|Why it is worth more than a sharp one.', 'Perito Casimiro Ardoin'],
      ['Detectar una falsificación|Spotting a forgery', 'Cinco señales que delatan a un impostor.|Five signs that expose an impostor.', 'Perita Ottilie Drex'],
      ['Subastas famosas del siglo|Famous auctions of the century', 'Un recorrido por las más disputadas.|A tour of the most contested.', 'Martillero Alaric Pontes'],
    ],
    wiz: {
      title: 'Consignar una reliquia|Consign a relic',
      steps: [
        ['Tipo de objeto|Object type', [sel('relicKind', 'Qué querés consignar|What you want to consign', ['Un arma|A weapon', 'Una joya|A jewel', 'Un manuscrito|A manuscript'])]],
        ['Fecha y reserva|Date and reserve', [date('hearingDay', 'Fecha de peritaje|Appraisal date', 'noPast'), num('reserve', 'Precio de reserva|Reserve price', 50, 100000)]],
        ['Manuscrito|Manuscript', [text('language', 'Idioma del manuscrito|Manuscript language', { minLength: 3, maxLength: 40 })]],
        ['Historia|History', [area('relicStory', 'Cómo llegó a tus manos|How it came into your hands', 300)]],
      ],
      cond: ['relicKind', 'a-manuscript', ['language']],
    },
    dash: { cols: ['Lote|Lot', 'Pujas recibidas|Bids received', 'Fecha de remate|Sale date', 'Precio de martillo|Hammer price'], pool: ['Espada sin nombre|Nameless sword', 'Yelmo del centinela|Sentinel helm', 'Collar de la tercera luna|Third Moon necklace', 'Pergamino del tratado|Treaty scroll', 'Reloj de otra hora|Other-hour clock', 'Silla del trono|Throne chair'], n: [1, 45], m: [480, 7800] },
  },
]

export const fantasy = specs.map((s) => defineTheme('fantasy', s))
