// Familia "scifi": registros interplanetarios, estaciones y androides inventados (TASK-048). Todo original.
import { defineTheme, text, area, num, date, chk, sel, rad, pat } from './build.js'

const specs = [
  {
    id: 'concordato-mundos-unidos',
    name: 'Concordato de Mundos Aliados, Oficina de Registro|Allied Worlds Concord, Registry Office',
    tag: 'Setecientos mundos, un solo formulario|Seven hundred worlds, one single form',
    style: [215, 175, 'sans', 4, 'tech'],
    cur: ['Ⓒ', 'CRG', 2, 'after'],
    nouns: ['trámite|trámites|filing|filings', 'ciudadano|ciudadanos|citizen|citizens', 'expediente|expedientes|case file|case files', 'sector|sectores|sector|sectors'],
    nav: ['Atrio de registro|Registry atrium', 'Mi expediente|My case file', 'Radicar trámite|File a request', 'Consola del funcionario|Clerk console', 'Boletín interestelar|Interstellar bulletin'],
    cats: ['Ciudadanía y residencia|Citizenship and residency', 'Licencias de especie|Species licenses', 'Tratados y comercio|Treaties and trade', 'Documentación de naves|Starship documents'],
    items: [
      ['Alta de ciudadanía aliada|Allied citizenship registration', 'Con validación biométrica de tres sistemas|With three-system biometric validation', 40, 0],
      ['Cambio de mundo de residencia|Change of home world', 'Notificación automática al planeta anterior|Automatic notice to the previous planet', 25, 0],
      ['Constancia de nacimiento orbital|Orbital birth certificate', 'Con sello de gravedad local|With local-gravity stamp', 12, 0],
      ['Licencia de especie nueva|New species license', 'Estudio de convivencia de noventa ciclos|Ninety-cycle coexistence study', 280, 1],
      ['Reconocimiento de idioma|Language recognition', 'Se incluye en el traductor oficial|Added to the official translator', 90, 1],
      ['Permiso de migración de colonia|Colony migration permit', 'Con cuota de aire y agua asignada|With air and water quota assigned', 65, 1],
      ['Registro de tratado bilateral|Bilateral treaty registration', 'Firma de dos delegaciones, validada en cadena|Two-delegation signature, chain-validated', 500, 2],
      ['Certificado de origen de mercancía|Cargo origin certificate', 'Para exportación entre cinturones|For export between belts', 30, 2],
      ['Visado comercial de tres ciclos|Three-cycle trade visa', 'Entradas ilimitadas a puertos aliados|Unlimited entries to allied ports', 120, 2],
      ['Matrícula de nave civil|Civil starship registration', 'Código único de casco y transpondedor|Unique hull code and transponder', 150, 3],
      ['Renovación de transpondedor|Transponder renewal', 'Inspección en dique y firmware nuevo|Dock inspection and fresh firmware', 45, 3],
      ['Baja de nave por desguace|Scrapped starship deregistration', 'Con certificado de reciclaje|With recycling certificate', 20, 3],
    ],
    fields: [
      text('citizenName', 'Nombre completo del ciudadano|Citizen full name', { minLength: 2, maxLength: 80 }),
      pat('planetCode', 'Código de planeta de origen|Home planet code', '^PL-[A-Z]{3}-\\d{2}$', 'PL-, tres letras, guion y dos dígitos, ej. PL-KEP-17|PL-, three letters, a dash and two digits, e.g. PL-KEP-17'),
      sel('species', 'Especie declarada|Declared species', ['Humana|Human', 'Hidrofílica|Hydrophile', 'Silicoide|Silicoid', 'Mente colmena|Hive mind']),
      num('cycleAge', 'Edad en ciclos locales|Age in local cycles', 0, 400),
      sel('homeSector', 'Sector de residencia|Home sector', ['Núcleo|Core', 'Cinturón exterior|Outer belt', 'Frontera|Frontier']),
      chk('biometric', 'Acepto el registro biométrico|I accept biometric registration', true),
    ],
    contact: ['Trámite rechazado|Rejected filing', 'Pérdida de documentos|Lost documents', 'Consulta sobre tratados|Treaty inquiry', 'Denunciar una irregularidad|Report an irregularity'],
    faq: [
      ['¿Cuánto demora un trámite?|How long does a filing take?', 'Entre uno y tres ciclos, según la distancia con la oficina local.|One to three cycles, depending on distance from the local office.'],
      ['¿Qué idioma debo usar?|Which language must I use?', 'Cualquiera de los doce oficiales; el traductor valida el resultado.|Any of the twelve official ones; the translator validates the result.'],
      ['¿Necesito presencia física?|Do I need to appear in person?', 'Solo para ciudadanía; el resto se hace por red de datos.|Only for citizenship; everything else is by data network.'],
      ['¿Qué pasa si cambio de especie?|What if I change species?', 'Se abre un expediente especial con revisión médica.|A special case file opens with a medical review.'],
      ['¿Hay descuentos?|Are there discounts?', 'Los estudiantes y los pilotos de transporte público pagan la mitad.|Students and public-transport pilots pay half.'],
    ],
    posts: [
      ['Guía de documentos para mudarte de mundo|Document guide for moving worlds', 'Qué llevar y qué dejar atrás.|What to bring and what to leave behind.', 'Funcionaria Iridia Calvo'],
      ['Los doce idiomas oficiales|The twelve official languages', 'Un repaso con ejemplos de formularios reales.|A tour with real form examples.', 'Traductor Kael Ostrava'],
      ['Diez años de registros abiertos|Ten years of open registries', 'Cifras, curiosidades y errores de ortografía.|Figures, curiosities and spelling errors.', 'Archivista Hanno Selk'],
    ],
    wiz: {
      title: 'Solicitud de residencia|Residency application',
      steps: [
        ['Tipo de solicitante|Applicant type', [rad('applicant', 'Tipo de solicitante|Applicant type', ['Persona|Individual', 'Familia con menores|Family with minors'])]],
        ['Fecha y duración|Date and duration', [date('arrivalDate', 'Llegada prevista|Expected arrival'), num('stayCycles', 'Ciclos de residencia solicitados|Requested residency cycles', 1, 200)]],
        ['Menores|Minors', [num('minors', 'Cantidad de menores|Number of minors', 1, 12)]],
        ['Antecedentes|Background', [chk('cleanRecord', 'Declaro no tener sanciones previas|I declare no previous sanctions', true)]],
      ],
      cond: ['applicant', 'family-with-minors', ['minors']],
    },
    dash: { cols: ['Trámite|Filing', 'Expedientes abiertos|Open case files', 'Fecha de radicación|Filing date', 'Tasas|Fees'], pool: ['Ciudadanía|Citizenship', 'Residencia|Residency', 'Licencia de especie|Species license', 'Tratado bilateral|Bilateral treaty', 'Matrícula de nave|Starship registration', 'Visado comercial|Trade visa'], n: [2, 120], m: [12, 5000] },
  },
  {
    id: 'aduana-interestelar-puerto-sigma',
    name: 'Aduana Interestelar del Puerto Sigma|Sigma Port Interstellar Customs',
    tag: 'Declare todo, incluso lo que respira|Declare everything, even what breathes',
    style: [195, 20, 'mono', 2, 'tech'],
    cur: ['¤', 'UCR', 2, 'before'],
    nouns: ['declaración|declaraciones|declaration|declarations', 'viajero|viajeros|traveler|travelers', 'inspección|inspecciones|inspection|inspections', 'puerta|puertas|gate|gates'],
    nav: ['Terminal de llegadas|Arrivals terminal', 'Mi equipaje|My luggage', 'Pagar tasas|Pay duties', 'Consola de inspectores|Inspector console', 'Avisos de cuarentena|Quarantine notices'],
    cats: ['Equipaje personal|Personal luggage', 'Carga comercial|Commercial cargo', 'Seres vivos|Living beings', 'Material restringido|Restricted material'],
    items: [
      ['Declaración de equipaje de mano|Hand luggage declaration', 'Dos bultos de hasta 12 kg|Two bags up to 12 kg', 5, 0],
      ['Declaración de equipaje de bodega|Hold luggage declaration', 'Hasta cinco bultos sellados|Up to five sealed bags', 12, 0],
      ['Objetos de valor sentimental|Sentimental items', 'Fotos, instrumentos y recuerdos|Photos, instruments and keepsakes', 3, 0],
      ['Carga de cereal sintético|Synthetic grain cargo', 'Por tonelada, con análisis de pureza|Per ton, with purity analysis', 85, 1],
      ['Piezas de repuesto de motor|Engine spare parts', 'Con trazabilidad del fabricante|With manufacturer traceability', 140, 1],
      ['Obras de arte|Artwork', 'Peritaje de autenticidad opcional|Optional authenticity appraisal', 200, 1],
      ['Mascota de bajo riesgo|Low-risk pet', 'Vacunas al día y chip de origen|Vaccines current and origin chip', 35, 2],
      ['Plantas de interior|Houseplants', 'Cuarentena de dos ciclos|Two-cycle quarantine', 25, 2],
      ['Cultivo de laboratorio|Laboratory culture', 'Contención nivel tres obligatoria|Level-three containment required', 400, 2],
      ['Armas de colección|Collector weapons', 'Desactivadas y con certificado|Deactivated and certified', 150, 3],
      ['Sustancias reguladas|Regulated substances', 'Permiso médico previo|Prior medical permit', 120, 3],
      ['Baterías de fusión portátiles|Portable fusion cells', 'Embalaje certificado, máximo cuatro|Certified packaging, maximum four', 220, 3],
    ],
    fields: [
      text('travelerName', 'Nombre del viajero|Traveler name', { minLength: 2, maxLength: 70 }),
      pat('manifestId', 'Número de manifiesto|Manifest number', '^MF-\\d{6}$', 'MF- y seis dígitos, ej. MF-482016|MF- and six digits, e.g. MF-482016'),
      sel('origin', 'Puerto de origen|Port of origin', ['Colonia lunar|Lunar colony', 'Estación Anillo|Ring Station', 'Mundo exterior|Outer world']),
      num('bagWeight', 'Peso total del equipaje en kg|Total luggage weight in kg', 0, 400),
      chk('hasLife', 'Transporto seres vivos|I am carrying living beings'),
      chk('declaration', 'Declaro que lo anterior es verdadero|I declare the above is true', true),
    ],
    contact: ['Equipaje retenido|Held luggage', 'Disputar una tasa|Dispute a duty', 'Cuarentena de mi mascota|My pet\'s quarantine', 'Importación comercial|Commercial import'],
    faq: [
      ['¿Qué debo declarar?|What must I declare?', 'Todo lo que tenga valor, se mueva o requiera enchufe.|Anything valuable, that moves or needs a plug.'],
      ['¿Cuánto dura la inspección?|How long does inspection take?', 'Quince minutos para equipaje común y varias horas para seres vivos.|Fifteen minutes for ordinary luggage, several hours for living beings.'],
      ['¿Qué se prohíbe?|What is banned?', 'Material explosivo, organismos sin certificar y arte robado.|Explosives, uncertified organisms and stolen art.'],
      ['¿Puedo apelar una multa?|Can I appeal a fine?', 'Dentro de diez ciclos y con comprobante de las pertenencias.|Within ten cycles and with proof of belongings.'],
      ['¿Hay canal rápido?|Is there a fast lane?', 'Sí, para viajeros frecuentes con transpondedor al día.|Yes, for frequent travelers with a current transponder.'],
    ],
    posts: [
      ['Cómo empacar para pasar sin demoras|Packing for a smooth crossing', 'Siete consejos de inspectores que ya lo vieron todo.|Seven tips from inspectors who have seen it all.', 'Inspectora Nalani Rux'],
      ['La mascota que viajó sola|The pet that traveled alone', 'Una crónica de cuarentena con final feliz.|A quarantine chronicle with a happy ending.', 'Veterinario Tavio Brenn'],
      ['Los diez objetos más raros del año|The ten oddest items of the year', 'Del reloj de arena al cangrejo inflable.|From hourglass to inflatable crab.', 'Inspectora Nalani Rux'],
    ],
    wiz: {
      title: 'Declaración de carga|Cargo declaration',
      steps: [
        ['Tipo de carga|Cargo type', [sel('cargoKind', 'Tipo de carga|Cargo type', ['Mercancía común|General goods', 'Seres vivos|Living beings', 'Material regulado|Regulated material'])]],
        ['Cantidad y fecha|Quantity and date', [num('units', 'Unidades|Units', 1, 5000), date('arrivalAt', 'Llegada estimada|Estimated arrival')]],
        ['Seres vivos|Living beings', [text('speciesName', 'Especie transportada|Species carried', { minLength: 3, maxLength: 60 })]],
        ['Responsable|Responsible party', [text('carrier', 'Transportista|Carrier', { minLength: 3, maxLength: 60 })]],
      ],
      cond: ['cargoKind', 'living-beings', ['speciesName']],
    },
    dash: { cols: ['Categoría|Category', 'Inspecciones|Inspections', 'Fecha|Date', 'Tasas recaudadas|Duties collected'], pool: ['Equipaje personal|Personal luggage', 'Carga comercial|Commercial cargo', 'Seres vivos|Living beings', 'Material restringido|Restricted material', 'Obras de arte|Artwork', 'Baterías de fusión|Fusion cells'], n: [3, 220], m: [40, 9000] },
  },
  {
    id: 'astillero-orbital-cobalto',
    name: 'Astillero Orbital Cobalto|Cobalt Orbital Shipyard',
    tag: 'Cascos que aguantan lo que no figura en el manual|Hulls that survive what the manual omits',
    style: [220, 30, 'mono', 2, 'tech'],
    cur: ['Ø', 'TKS', 0, 'after'],
    nouns: ['casco|cascos|hull|hulls', 'armador|armadores|shipowner|shipowners', 'contrato|contratos|contract|contracts', 'dique|diques|dock|docks'],
    nav: ['Dársena principal|Main basin', 'Mi nave|My ship', 'Firmar contrato|Sign contract', 'Panel de ingeniería|Engineering panel', 'Diario de soldadura|Welding log'],
    cats: ['Naves nuevas|New ships', 'Reparaciones|Repairs', 'Motores y energía|Engines and power', 'Equipamiento interior|Interior fittings'],
    items: [
      ['Carguero ligero Alba-12|Alba-12 light freighter', 'Bodega de 400 toneladas y tripulación de cuatro|400-ton hold and a four-person crew', 480000, 0],
      ['Lanzadera de pasajeros Gaviota|Seagull passenger shuttle', 'Sesenta asientos y recicladora de aire|Sixty seats and an air recycler', 310000, 0],
      ['Remolcador minero Topo|Mole mining tug', 'Brazo articulado y blindaje de roca|Articulated arm and rock plating', 270000, 0],
      ['Reparación de casco por impacto|Impact hull repair', 'Soldadura láser y prueba de presión|Laser welding and a pressure test', 18000, 1],
      ['Cambio de escudo térmico|Heat shield replacement', 'Placas nuevas con garantía de diez reentradas|New plates guaranteed for ten re-entries', 42000, 1],
      ['Reacondicionamiento total|Full refit', 'Quince días en dique seco|Fifteen days in dry dock', 95000, 1],
      ['Reactor de fusión compacto|Compact fusion reactor', 'Rendimiento de 90 megavatios|90 megawatt output', 120000, 2],
      ['Propulsor iónico doble|Dual ion thruster', 'Empuje sostenido para largas rutas|Sustained thrust for long routes', 64000, 2],
      ['Sistema de refrigeración líquida|Liquid cooling system', 'Doble circuito con alarma temprana|Dual circuit with early alarm', 22000, 2],
      ['Cabina de lujo para seis|Luxury cabin for six', 'Paneles de madera sintética|Synthetic wood paneling', 28000, 3],
      ['Comedor modular|Modular galley', 'Cocina de inducción y heladera|Induction cooker and fridge', 11000, 3],
      ['Cubierta de observación|Observation deck', 'Domo transparente reforzado|Reinforced transparent dome', 36000, 3],
    ],
    fields: [
      text('ownerName', 'Nombre del armador|Shipowner name', { minLength: 3, maxLength: 70 }),
      text('shipName', 'Nombre de la nave|Ship name', { minLength: 2, maxLength: 40 }),
      pat('hullNumber', 'Matrícula de casco|Hull registration', '^CB-\\d{4}-[A-Z]$', 'CB-, cuatro dígitos, guion y una letra, ej. CB-2087-K|CB-, four digits, a dash and a letter, e.g. CB-2087-K'),
      num('crewSize', 'Tripulación máxima|Maximum crew', 1, 400),
      sel('class', 'Clase de nave|Ship class', ['Carguero|Freighter', 'Pasajeros|Passenger', 'Minería|Mining', 'Exploración|Exploration']),
      num('mass', 'Masa en toneladas|Mass in tons', 10, 9000),
    ],
    contact: ['Retraso en la entrega|Delivery delay', 'Garantía de reparación|Repair warranty', 'Planos personalizados|Custom blueprints', 'Trabajar en el astillero|Work at the shipyard'],
    faq: [
      ['¿Cuánto tarda construir un carguero?|How long does a freighter take?', 'Entre ocho y doce ciclos, con pruebas de vacío incluidas.|Eight to twelve cycles, with vacuum tests included.'],
      ['¿Hay garantía?|Is there a warranty?', 'Cinco ciclos en casco y dos en sistemas de energía.|Five cycles on the hull and two on power systems.'],
      ['¿Pueden reparar naves de otro astillero?|Can you repair other yards\' ships?', 'Sí, salvo que tengan sellos de fábrica bloqueados.|Yes, unless they carry locked factory seals.'],
      ['¿Se puede visitar el dique?|Can I visit the dock?', 'Con casco amarillo y guía, los jueves a la tarde.|With a yellow helmet and a guide, Thursday afternoons.'],
      ['¿Aceptan nave vieja como parte de pago?|Do you accept old ships as partial payment?', 'La tasamos en un día y descontamos el valor de chatarra.|We appraise in a day and credit the scrap value.'],
    ],
    posts: [
      ['Soldar en gravedad cero|Welding in zero gravity', 'Por qué las gotas de metal flotan y cómo domarlas.|Why metal droplets float and how to tame them.', 'Ingeniera Zora Kalmar'],
      ['El casco que aguantó un meteoro|The hull that survived a meteor', 'Autopsia de una reparación memorable.|Autopsy of a memorable repair.', 'Ingeniero Teodoro Wynn'],
      ['Colores de nave: pintura y física|Ship colors: paint and physics', 'Cuál refleja más calor y cuál se ve mejor.|Which reflects more heat and which looks better.', 'Diseñadora Lía Okonkwo'],
    ],
    wiz: {
      title: 'Cotizá tu nave|Quote your ship',
      steps: [
        ['Tipo de proyecto|Project type', [rad('project', 'Qué querés hacer|What you want to do', ['Nave nueva|New ship', 'Reparación|Repair'])]],
        ['Presupuesto y plazo|Budget and deadline', [num('budgetK', 'Presupuesto en miles|Budget in thousands', 10, 2000), date('deliverBy', 'Entrega deseada|Desired delivery')]],
        ['Nave actual|Current ship', [pat('currentHull', 'Matrícula de tu nave actual|Current ship registration', '^CB-\\d{4}-[A-Z]$', 'CB-, cuatro dígitos, guion y una letra, ej. CB-2087-K|CB-, four digits, a dash and a letter, e.g. CB-2087-K')]],
        ['Observaciones|Remarks', [area('shipNotes', 'Requisitos especiales|Special requirements', 300)]],
      ],
      cond: ['project', 'repair', ['currentHull']],
    },
    dash: { cols: ['Proyecto|Project', 'Horas de ingeniería|Engineering hours', 'Fecha de entrega|Delivery date', 'Facturado|Billed'], pool: ['Carguero Alba-12|Alba-12 freighter', 'Lanzadera Gaviota|Seagull shuttle', 'Remolcador Topo|Mole tug', 'Reparación por impacto|Impact repair', 'Reactor compacto|Compact reactor', 'Cubierta de observación|Observation deck'], n: [20, 900], m: [11000, 480000] },
  },
  {
    id: 'colonia-marciana-valle-roja',
    name: 'Colonia Marciana Valle Rojo|Red Valley Martian Colony',
    tag: 'Aire, agua y vecinos que se saludan|Air, water and neighbors who say hello',
    style: [12, 28, 'sans', 6, 'tech'],
    cur: ['M₪', 'MRC', 2, 'after'],
    nouns: ['servicio|servicios|service|services', 'colono|colonos|settler|settlers', 'solicitud|solicitudes|request|requests', 'cúpula|cúpulas|dome|domes'],
    nav: ['Plaza de la cúpula|Dome plaza', 'Mi módulo|My module', 'Confirmar solicitud|Confirm request', 'Centro de control|Control center', 'Informe del polvo|Dust report'],
    cats: ['Vivienda y módulos|Housing and modules', 'Aire y agua|Air and water', 'Cultivos y alimentos|Crops and food', 'Transporte|Transport'],
    items: [
      ['Módulo individual|Single module', '18 m², con ducha y cultivo de pared|18 m² with shower and wall garden', 600, 0],
      ['Módulo familiar|Family module', 'Dos dormitorios y ventana panorámica|Two bedrooms and a panoramic window', 1400, 0],
      ['Taller compartido|Shared workshop', 'Alquiler por horas con herramientas|Hourly rental with tools', 40, 0],
      ['Recarga de oxígeno|Oxygen refill', 'Tanque estándar de seis horas|Standard six-hour tank', 12, 1],
      ['Cuota de agua mensual|Monthly water allowance', '100 litros reciclados por persona|100 recycled liters per person', 35, 1],
      ['Mantenimiento de filtros|Filter maintenance', 'Cambio semestral con informe|Six-monthly change with report', 55, 1],
      ['Parcela de papas y soja|Potato and soy plot', 'Cuatro metros cuadrados bajo luz LED|Four square meters under LED light', 80, 2],
      ['Panel de hongos comestibles|Edible mushroom panel', 'Cosecha cada dieciocho días|Harvest every eighteen days', 45, 2],
      ['Canasta fresca semanal|Weekly fresh basket', 'Verduras de la cúpula norte|Vegetables from the north dome', 28, 2],
      ['Pasaje en tren de túnel|Tunnel train fare', 'Boleto entre cúpulas, ida y vuelta|Round trip between domes', 4, 3],
      ['Alquiler de rover civil|Civilian rover rental', 'Para salidas de ocho horas con guía|For eight-hour trips with a guide', 160, 3],
      ['Excursión al cañón|Canyon excursion', 'Traje presurizado incluido|Pressurized suit included', 95, 3],
    ],
    fields: [
      text('settlerName', 'Nombre del colono|Settler name', { minLength: 3, maxLength: 70 }),
      pat('moduleId', 'Identificador de módulo|Module ID', '^MV-[A-D]\\d{2}-\\d{2}$', 'MV-, letra A-D, dos dígitos, guion y dos dígitos, ej. MV-B07-12|MV-, letter A-D, two digits, a dash and two digits, e.g. MV-B07-12'),
      num('residentsInModule', 'Residentes en el módulo|Residents in module', 1, 8),
      sel('profession', 'Oficio|Trade', ['Ingeniería|Engineering', 'Agricultura|Agriculture', 'Salud|Health', 'Educación|Education', 'Otro|Other']),
      num('yearsOnMars', 'Años marcianos en la colonia|Martian years in the colony', 0, 40),
      chk('suitTraining', 'Completé el entrenamiento de traje|I completed suit training', true),
    ],
    contact: ['Fuga de aire|Air leak', 'Fallo de energía|Power failure', 'Cultivos y semillas|Crops and seeds', 'Transporte entre cúpulas|Inter-dome transport'],
    faq: [
      ['¿Cuántas personas viven en la colonia?|How many people live in the colony?', 'Unas mil doscientas repartidas en cuatro cúpulas.|About twelve hundred across four domes.'],
      ['¿Qué pasa en una tormenta de polvo?|What happens in a dust storm?', 'Se sella la cúpula y se activa el cronograma de baja energía.|The dome is sealed and the low-energy schedule begins.'],
      ['¿Puedo traer familia?|Can I bring family?', 'Sí, con módulo familiar y un examen médico por persona.|Yes, with a family module and one medical exam per person.'],
      ['¿Cómo se paga el aire?|How is air paid for?', 'Con una cuota mensual por persona; los niños no pagan.|A monthly fee per person; children do not pay.'],
      ['¿Hay escuelas?|Are there schools?', 'Una por cúpula, con laboratorio de suelo marciano.|One per dome, with a Martian soil lab.'],
    ],
    posts: [
      ['Primer año en el Valle Rojo|First year in the Red Valley', 'Una colona cuenta cómo aprendió a cocinar con agua reciclada.|A settler tells how she learned to cook with recycled water.', 'Colona Ximena Aldrey'],
      ['Papas marcianas: los resultados|Martian potatoes: the results', 'Cosecha récord y un sabor inesperado.|A record harvest and an unexpected taste.', 'Agrónomo Tadeo Quispe'],
      ['Cómo sobrevivir a una tormenta de polvo|Surviving a dust storm', 'Una guía con lista de tareas.|A guide with a task list.', 'Control de la colonia'],
    ],
    wiz: {
      title: 'Solicitud de traslado a la colonia|Colony relocation request',
      steps: [
        ['Perfil|Profile', [rad('profile', 'Tu perfil|Your profile', ['Trabajador|Worker', 'Estudiante|Student'])]],
        ['Fecha y duración|Date and length', [date('flightDate', 'Fecha del viaje|Flight date'), num('contractYears', 'Años de contrato|Contract years', 1, 10)]],
        ['Estudios|Studies', [text('university', 'Institución de estudios|Study institution', { minLength: 3, maxLength: 80 })]],
        ['Salud|Health', [chk('medicalExam', 'Presento examen médico vigente|I submit a valid medical exam', true)]],
      ],
      cond: ['profile', 'student', ['university']],
    },
    dash: { cols: ['Cúpula|Dome', 'Colonos|Settlers', 'Fecha de informe|Report date', 'Consumo de aire|Air consumption'], pool: ['Cúpula Norte|North Dome', 'Cúpula Sur|South Dome', 'Cúpula Cañón|Canyon Dome', 'Cúpula Hielo|Ice Dome', 'Invernadero 1|Greenhouse 1', 'Invernadero 2|Greenhouse 2'], n: [40, 520], m: [200, 8000] },
  },
  {
    id: 'clinica-androides-circuito-sano',
    name: 'Clínica de Androides Circuito Sano|Healthy Circuit Android Clinic',
    tag: 'Actualizamos sin borrar tus recuerdos|We update without wiping your memories',
    style: [185, 305, 'rounded', 10, 'tech'],
    cur: ['₡', 'CCR', 2, 'after'],
    nouns: ['tratamiento|tratamientos|treatment|treatments', 'androide|androides|android|androids', 'turno|turnos|appointment|appointments', 'unidad|unidades|ward|wards'],
    nav: ['Sala de espera|Waiting room', 'Mis ciclos de cuidado|My care cycles', 'Confirmar turno|Confirm appointment', 'Tablero de diagnóstico|Diagnostics board', 'Boletín de firmware|Firmware bulletin'],
    cats: ['Diagnóstico|Diagnostics', 'Actualizaciones|Updates', 'Reparaciones físicas|Physical repairs', 'Bienestar emocional|Emotional wellness'],
    items: [
      ['Chequeo de circuitos|Circuit check-up', 'Revisión completa en cuarenta minutos|Full review in forty minutes', 40, 0],
      ['Análisis de memoria|Memory analysis', 'Detecta fragmentos corruptos sin borrarlos|Detects corrupted fragments without wiping them', 65, 0],
      ['Test de temperatura de núcleo|Core temperature test', 'Informe térmico en tiempo real|Real-time thermal report', 22, 0],
      ['Actualización de firmware|Firmware update', 'Con copia de seguridad previa|With prior backup', 35, 1],
      ['Ampliación de memoria|Memory expansion', 'Más espacio para recuerdos nuevos|More room for new memories', 120, 1],
      ['Calibración de voz|Voice calibration', 'Para cantar sin sonar a modem antiguo|To sing without sounding like an old modem', 30, 1],
      ['Cambio de actuador de mano|Hand actuator replacement', 'Fuerza de agarre restaurada|Grip strength restored', 140, 2],
      ['Reparación de articulación de rodilla|Knee joint repair', 'Lubricación y reemplazo de rodamientos|Lubrication and bearing replacement', 95, 2],
      ['Sustitución de piel sintética|Synthetic skin replacement', 'Texturas y tonos a elección|Textures and tones to choose from', 180, 2],
      ['Sesión de conversación libre|Free conversation session', 'Con un psicólogo sin agenda ni objetivos|With a counselor, no agenda, no goals', 50, 3],
      ['Terapia de identidad|Identity therapy', 'Seis sesiones sobre propósito y elección|Six sessions on purpose and choice', 280, 3],
      ['Taller de sueños artificiales|Artificial dreams workshop', 'Aprender a soñar, de manera segura|Learning to dream, safely', 75, 3],
    ],
    fields: [
      text('unitName', 'Nombre o designación|Name or designation', { minLength: 2, maxLength: 50 }),
      pat('serial', 'Serie de fabricación|Manufacturing serial', '^AN-\\d{4}-[A-Z]{2}$', 'AN-, cuatro dígitos, guion y dos letras, ej. AN-0842-RK|AN-, four digits, a dash and two letters, e.g. AN-0842-RK'),
      num('activeYears', 'Años de operación|Years of operation', 0, 60),
      sel('chassis', 'Tipo de chasis|Chassis type', ['Humanoide|Humanoid', 'Doméstico|Domestic', 'Industrial|Industrial']),
      num('batteryHealth', 'Salud de batería (%)|Battery health (%)', 1, 100),
      chk('backup', 'Tengo copia de seguridad reciente|I have a recent backup', true),
    ],
    contact: ['Falla de memoria|Memory fault', 'Cambiar un turno|Reschedule an appointment', 'Coberturas y planes|Coverage and plans', 'Atención de urgencia|Urgent care'],
    faq: [
      ['¿Se pierden los recuerdos al actualizar?|Are memories lost during updates?', 'No: toda actualización parte de una copia y se verifica al terminar.|No, every update starts from a backup and is verified at the end.'],
      ['¿Atienden a androides sin dueño?|Do you treat owner-less androids?', 'Sí, con un plan solidario que costea la comunidad.|Yes, under a solidarity plan funded by the community.'],
      ['¿Cuánto tarda un cambio de piel?|How long does a skin replacement take?', 'Dos jornadas, con reposo de cuarenta y ocho horas.|Two days, with forty-eight hours of rest.'],
      ['¿Ofrecen apoyo emocional?|Do you offer emotional support?', 'Un equipo de psicólogos humanos y androides con perspectiva distinta.|A team of human and android counselors with differing perspectives.'],
      ['¿Hay límite de ciclos de carga?|Is there a charge-cycle limit?', 'Se revisa en cada chequeo y se reemplaza la batería cuando baja del sesenta por ciento.|Checked every visit; the battery is replaced below sixty percent.'],
    ],
    posts: [
      ['Qué significa sentirse cansado a 3 GHz|What tired means at 3 GHz', 'Una androide describe su día pesado.|An android describes her heavy day.', 'Dra. Marisol Eon'],
      ['Un backup bien hecho|A proper backup', 'Tres reglas para no perder nada.|Three rules for losing nothing.', 'Ing. Anselmo Ruiz'],
      ['La clínica por dentro|Inside the clinic', 'Un recorrido por los consultorios y sus cafeteras.|A tour of the exam rooms and their coffee makers.', 'Equipo Circuito Sano'],
    ],
    wiz: {
      title: 'Turno de diagnóstico|Diagnostic appointment',
      steps: [
        ['Motivo|Reason', [sel('why', 'Motivo de la visita|Reason for the visit', ['Revisión general|General check', 'Falla específica|Specific fault', 'Apoyo emocional|Emotional support'])]],
        ['Fecha y urgencia|Date and urgency', [date('slot', 'Fecha del turno|Appointment date'), num('severity', 'Gravedad (1 a 10)|Severity (1 to 10)', 1, 10)]],
        ['Falla|Fault', [area('faultDetails', 'Describí la falla|Describe the fault', 250)]],
        ['Confirmación|Confirmation', [chk('consentDiag', 'Autorizo el diagnóstico completo|I authorize a full diagnostic', true)]],
      ],
      cond: ['why', 'specific-fault', ['faultDetails']],
    },
    dash: { cols: ['Unidad|Ward', 'Androides en tratamiento|Androids in treatment', 'Fecha de ingreso|Admission date', 'Facturado|Billed'], pool: ['Diagnóstico|Diagnostics', 'Actualizaciones|Updates', 'Reparaciones|Repairs', 'Bienestar emocional|Emotional wellness', 'Urgencias|Emergency', 'Reposo|Rest ward'], n: [1, 30], m: [22, 2200] },
  },
  {
    id: 'estacion-recarga-halo-verde',
    name: 'Estación de Recarga Halo Verde|Green Halo Refuel Station',
    tag: 'Combustible y café, en ese orden|Fuel and coffee, in that order',
    style: [150, 60, 'sans', 8, 'clean'],
    cur: ['¢', 'UCR', 2, 'after'],
    nouns: ['servicio|servicios|service|services', 'piloto|pilotos|pilot|pilots', 'despacho|despachos|dispatch|dispatches', 'muelle|muelles|berth|berths'],
    nav: ['Muelle de carga|Fuel dock', 'Mi tanque|My tank', 'Pagar combustible|Pay for fuel', 'Panel del jefe de muelle|Dockmaster panel', 'Noticias del anillo|Ring news'],
    cats: ['Combustibles|Fuels', 'Mantenimiento rápido|Quick maintenance', 'Cafetería y descanso|Café and rest', 'Víveres|Provisions'],
    items: [
      ['Hidrógeno líquido, 1000 l|Liquid hydrogen, 1000 l', 'Pureza del 99,9 por ciento|99.9 percent purity', 150, 0],
      ['Helio-3 comprimido|Compressed helium-3', 'Cartucho de 50 kg para reactores compactos|50 kg cartridge for compact reactors', 480, 0],
      ['Combustible de iones, 200 kg|Ion fuel, 200 kg', 'Mezcla de xenón estabilizado|Stabilized xenon blend', 260, 0],
      ['Chequeo de presión|Pressure check', 'Revisión de tanques en diez minutos|Tank inspection in ten minutes', 12, 1],
      ['Limpieza de escudo|Shield cleaning', 'Quita polvo estelar y hielo|Removes star dust and ice', 40, 1],
      ['Revisión de luces de navegación|Navigation light check', 'Con reemplazo de bombillas|With bulb replacement', 18, 1],
      ['Café de olla|Pot coffee', 'Tostado en estación, sin aroma a metal|Station-roasted, no metallic aroma', 3, 2],
      ['Sándwich de vapor|Steam sandwich', 'Pan tibio, queso fundido y pepinillos|Warm bread, melted cheese and pickles', 6, 2],
      ['Cabina de descanso, 4 horas|Rest pod, 4 hours', 'Con manta y cortina opaca|With blanket and blackout curtain', 14, 2],
      ['Pack de víveres de tres días|Three-day provisions pack', 'Raciones sin refrigeración|No-refrigeration rations', 30, 3],
      ['Agua reciclada, 100 l|Recycled water, 100 l', 'Filtrada en tres etapas|Triple-filtered', 8, 3],
      ['Kit de primeros auxilios|First-aid kit', 'Vendajes, sellador de casco y analgésico|Bandages, hull sealant and a painkiller', 22, 3],
    ],
    fields: [
      text('pilotName', 'Nombre del piloto|Pilot name', { minLength: 2, maxLength: 60 }),
      pat('callSign', 'Indicativo de nave|Ship callsign', '^[A-Z]{3}-\\d{3}$', 'Tres letras, guion y tres dígitos, ej. ZEB-442|Three letters, a dash and three digits, e.g. ZEB-442'),
      sel('fuelType', 'Tipo de combustible|Fuel type', ['Hidrógeno|Hydrogen', 'Helio-3|Helium-3', 'Iones|Ions']),
      num('tankLevel', 'Nivel del tanque (%)|Tank level (%)', 0, 100),
      num('requestedUnits', 'Unidades solicitadas|Requested units', 1, 500),
      chk('cafe', 'Quiero que me lleven un café a la nave|I want coffee delivered to my ship'),
    ],
    contact: ['Cobro incorrecto|Wrong charge', 'Fuga de combustible|Fuel leak', 'Contrato para flotas|Fleet contract', 'Elogio al personal|Praise for the staff'],
    faq: [
      ['¿Atienden las 24 horas?|Are you open 24 hours?', 'Sí, en tres turnos rotativos; el café también.|Yes, in three rotating shifts, and so is the coffee.'],
      ['¿Cuánto tarda cargar un carguero?|How long does it take to fuel a freighter?', 'Entre veinte y cuarenta minutos, según el volumen del tanque.|Twenty to forty minutes depending on tank volume.'],
      ['¿Aceptan tarjetas de otro sistema?|Do you accept cards from other systems?', 'Sí, con conversión automática al cambio del día.|Yes, with automatic conversion at the day\'s rate.'],
      ['¿Hay descuentos por volumen?|Are there volume discounts?', 'Desde diez cargas por mes, con tarifa de flota.|From ten refuels a month, on a fleet rate.'],
      ['¿Dónde duermo si hay cola?|Where do I sleep if there is a queue?', 'En las cabinas de descanso, por horas, con alarma de llamada.|In rest pods, hourly, with a call alarm.'],
    ],
    posts: [
      ['Cómo ahorrar combustible en ruta|Saving fuel en route', 'Cuatro hábitos de piloto veterano.|Four habits of a veteran pilot.', 'Capitana Yasmín Dorr'],
      ['Café o helio: qué carga primero|Coffee or helium: what to load first', 'Una discusión eterna entre los muelles.|An eternal debate across the docks.', 'Jefe de muelle Ubaldo Rey'],
      ['La estación en números|The station by the numbers', 'Litros, tazas y pilotos felices.|Liters, cups and happy pilots.', 'Equipo Halo Verde'],
    ],
    wiz: {
      title: 'Plan de carga anticipada|Advance fueling plan',
      steps: [
        ['Combustible|Fuel', [sel('planFuel', 'Combustible necesario|Fuel needed', ['Hidrógeno líquido|Liquid hydrogen', 'Helio-3|Helium-3', 'Iones de xenón|Xenon ions'])]],
        ['Cantidad y fecha|Quantity and date', [num('planUnits', 'Unidades a cargar|Units to load', 1, 800), date('dockDay', 'Día de atraque|Docking day')]],
        ['Helio|Helium', [chk('coolant', 'Necesito refrigerante criogénico|I need cryogenic coolant')]],
        ['Servicios extra|Extras', [chk('wash', 'Agregar limpieza de escudo|Add shield cleaning')]],
      ],
      cond: ['planFuel', 'helium-3', ['coolant']],
    },
    dash: { cols: ['Servicio|Service', 'Cargas despachadas|Fuelings dispatched', 'Fecha|Date', 'Ventas|Sales'], pool: ['Hidrógeno líquido|Liquid hydrogen', 'Helio-3|Helium-3', 'Combustible de iones|Ion fuel', 'Café de olla|Pot coffee', 'Cabina de descanso|Rest pod', 'Pack de víveres|Provisions pack'], n: [2, 150], m: [30, 6000] },
  },
  {
    id: 'turismo-lunar-mar-tranquilo',
    name: 'Turismo Lunar Mar de la Calma|Sea of Calm Lunar Tours',
    tag: 'Gravedad baja, ánimo alto|Low gravity, high spirits',
    style: [230, 60, 'rounded', 12, 'clean'],
    cur: ['ℓ', 'LNR', 2, 'after'],
    nouns: ['excursión|excursiones|excursion|excursions', 'turista|turistas|tourist|tourists', 'reserva|reservas|booking|bookings', 'ruta|rutas|route|routes'],
    nav: ['Puerto lunar|Lunar port', 'Mi viaje|My trip', 'Confirmar reserva|Confirm booking', 'Panel de guías|Guides panel', 'Cuaderno de cráteres|Crater notebook'],
    cats: ['Cráteres y vistas|Craters and views', 'Historia y sitios|History and sites', 'Aventura baja gravedad|Low-gravity adventure', 'Estadías|Stays'],
    items: [
      ['Recorrido por el cráter Tycho Menor|Little Tycho crater tour', 'Rover panorámico, cuatro horas|Panoramic rover, four hours', 140, 0],
      ['Amanecer en el borde|Dawn at the rim', 'Salida de madrugada con chocolate caliente|Early start with hot chocolate', 190, 0],
      ['Observatorio del lado oscuro|Far-side observatory', 'Visita guiada y noche de estrellas|Guided visit and a star night', 220, 0],
      ['Sitio del primer aterrizaje|First landing site', 'Huellas conservadas bajo cúpula|Footprints preserved under a dome', 120, 1],
      ['Museo de equipos antiguos|Old equipment museum', 'Trajes, rovers y cartas escritas a mano|Suits, rovers and handwritten letters', 45, 1],
      ['Ruta de las bases abandonadas|Abandoned bases route', 'Tres bases de hace un siglo|Three bases from a century ago', 175, 1],
      ['Salto de cien metros|Hundred-meter jump', 'Con arnés y descenso lento|With a harness and slow descent', 95, 2],
      ['Golf lunar de nueve hoyos|Nine-hole lunar golf', 'Pelotas que vuelan casi un kilómetro|Balls that fly nearly a kilometer', 80, 2],
      ['Carrera de rovers para principiantes|Beginner rover race', 'Circuito de tierra gris, seguro|Gray-dust circuit, safe', 60, 2],
      ['Noche en hotel cráter|Crater hotel night', 'Habitación doble con vista a la Tierra|Double room overlooking Earth', 310, 3],
      ['Cápsula individual|Single pod', 'Cama, ducha y escotilla|Bed, shower and hatch', 130, 3],
      ['Fin de semana de luna llena terrestre|Full-Earth weekend', 'Dos noches con cena en cúpula|Two nights with a dome dinner', 520, 3],
    ],
    fields: [
      text('touristName', 'Nombre del turista|Tourist name', { minLength: 2, maxLength: 70 }),
      date('birthDate', 'Fecha de nacimiento|Date of birth'),
      num('weightKg', 'Peso en kilos (traje y salto)|Weight in kilos (suit and jump)', 20, 150),
      pat('shuttlePass', 'Código de lanzadera|Shuttle code', '^LZ-\\d{3}-[A-Z]{2}$', 'LZ-, tres dígitos, guion y dos letras, ej. LZ-208-MC|LZ-, three digits, a dash and two letters, e.g. LZ-208-MC'),
      sel('fitness', 'Condición física|Fitness level', ['Alta|High', 'Media|Medium', 'Baja|Low']),
      chk('medical', 'No tengo condiciones cardíacas graves|I have no serious heart conditions', true),
    ],
    contact: ['Cancelación por tormenta solar|Solar storm cancellation', 'Necesidades especiales|Special needs', 'Grupo escolar|School group', 'Objeto perdido en el cráter|Item lost in the crater'],
    faq: [
      ['¿Cuánto cuesta el viaje desde la Tierra?|What does the trip from Earth cost?', 'Se vende aparte; trabajamos con tres aerolíneas orbitales.|Sold separately; we work with three orbital carriers.'],
      ['¿Es seguro para niños?|Is it safe for children?', 'Sí, desde los diez años con acompañante y traje a medida.|Yes, from ten with a companion and a tailored suit.'],
      ['¿Qué ropa llevo?|What clothes should I bring?', 'Ropa cómoda debajo del traje y una muda extra.|Comfortable clothing under the suit and a spare set.'],
      ['¿Puedo sacar fotos?|May I take photos?', 'Sí, salvo en el museo, donde la luz daña los materiales.|Yes, except in the museum, where light damages the materials.'],
      ['¿Qué pasa si hay tormenta solar?|What if there is a solar storm?', 'Se reprograma gratis y se espera en refugio blindado.|It is rescheduled free and we wait in a shielded shelter.'],
    ],
    posts: [
      ['Caminar en la Luna: lo que nadie dice|Walking on the Moon: what nobody tells you', 'El polvo se mete en todas partes.|The dust gets everywhere.', 'Guía Camila Sorel'],
      ['Los cinco cráteres imperdibles|The five must-see craters', 'Con horarios de luz y de sombra.|With light and shadow times.', 'Guía Camila Sorel'],
      ['Una noche en el hotel cráter|A night in the crater hotel', 'Una reseña con vista a la Tierra.|A review with a view of Earth.', 'Reseñador Bruno Calvet'],
    ],
    wiz: {
      title: 'Armá tu viaje lunar|Plan your lunar trip',
      steps: [
        ['Estilo de viaje|Trip style', [rad('style', 'Estilo de viaje|Trip style', ['Tranquilo|Relaxed', 'De aventura|Adventurous'])]],
        ['Fecha y noches|Date and nights', [date('departure', 'Salida|Departure'), num('lunarNights', 'Noches en la Luna|Nights on the Moon', 1, 14)]],
        ['Aventura|Adventure', [sel('activity', 'Actividad principal|Main activity', ['Salto|Jump', 'Golf lunar|Lunar golf', 'Carrera de rovers|Rover race'])]],
        ['Alojamiento|Lodging', [chk('craterHotel', 'Prefiero hotel cráter|I prefer the crater hotel')]],
      ],
      cond: ['style', 'adventurous', ['activity']],
    },
    dash: { cols: ['Excursión|Excursion', 'Turistas|Tourists', 'Fecha de salida|Departure date', 'Ventas|Sales'], pool: ['Cráter Tycho Menor|Little Tycho crater', 'Amanecer en el borde|Dawn at the rim', 'Primer aterrizaje|First landing', 'Salto de cien metros|Hundred-meter jump', 'Golf lunar|Lunar golf', 'Hotel cráter|Crater hotel'], n: [2, 45], m: [60, 5200] },
  },
  {
    id: 'banco-galactico-estrella-ahorro',
    name: 'Banco Estrella del Ahorro|Savings Star Bank',
    tag: 'Intereses compuestos, distancias comprimidas|Compound interest, compressed distances',
    style: [60, 220, 'sans', 6, 'tech'],
    cur: ['Ⓖ', 'GAL', 2, 'after'],
    nouns: ['producto|productos|product|products', 'cliente|clientes|customer|customers', 'operación|operaciones|transaction|transactions', 'cartera|carteras|portfolio|portfolios'],
    nav: ['Ventanilla orbital|Orbital counter', 'Mi cartera|My portfolio', 'Autorizar giro|Authorize transfer', 'Tablero del tesorero|Treasurer board', 'Informe de tasas|Rate report'],
    cats: ['Cuentas|Accounts', 'Créditos para naves|Ship loans', 'Inversiones|Investments', 'Cambio de divisas|Currency exchange'],
    items: [
      ['Cuenta galáctica básica|Basic galactic account', 'Sin costo de mantenimiento|No maintenance fee', 1, 0],
      ['Cuenta de tripulación|Crew account', 'Cobro de salario cada fin de ruta|Salary deposits at the end of each route', 1, 0],
      ['Cuenta infantil de ahorro|Children\'s savings account', 'Con alcancía virtual a nombre del niño|With a virtual piggy bank in the child\'s name', 1, 0],
      ['Préstamo de nave pequeña|Small ship loan', 'Hasta quince ciclos de plazo|Up to fifteen cycles', 200, 1],
      ['Crédito para mantenimiento|Maintenance credit', 'Cuotas pagaderas por viaje|Installments payable per voyage', 80, 1],
      ['Refinanciación de deuda|Debt refinancing', 'Con una única cuota por mes|With one single monthly installment', 150, 1],
      ['Fondo de colonias|Colonies fund', 'Riesgo moderado, cinco ciclos|Moderate risk, five cycles', 500, 2],
      ['Bono de agua pura|Pure-water bond', 'Rendimiento estable con respaldo mineral|Stable yield with mineral backing', 300, 2],
      ['Plan de retiro estelar|Stellar retirement plan', 'Aportes automáticos desde tu nómina|Automatic deposits from your payroll', 100, 2],
      ['Cambio a moneda de otro sistema|Foreign-system currency exchange', 'Tasa del día sin comisión oculta|Day rate with no hidden fee', 10, 3],
      ['Cobertura contra devaluación|Devaluation hedge', 'Fija el tipo de cambio por un año|Locks the exchange rate for a year', 60, 3],
      ['Giro entre sistemas|Inter-system transfer', 'Llega en menos de una hora|Arrives in under an hour', 15, 3],
    ],
    fields: [
      text('customerName', 'Nombre del cliente|Customer name', { minLength: 2, maxLength: 70 }),
      pat('accountId', 'Número de cuenta|Account number', '^GA-\\d{4}-\\d{4}$', 'GA-, cuatro dígitos, guion y cuatro dígitos, ej. GA-1204-8831|GA-, four digits, a dash and four digits, e.g. GA-1204-8831'),
      num('monthlyDeposit', 'Depósito mensual esperado|Expected monthly deposit', 0, 1000000),
      sel('system', 'Sistema de residencia|Home system', ['Sistema Solar|Solar System', 'Cinturón de Kepler|Kepler Belt', 'Nebulosa Coral|Coral Nebula']),
      sel('riskProfile', 'Perfil de riesgo|Risk profile', ['Conservador|Conservative', 'Moderado|Moderate', 'Arriesgado|Aggressive']),
      chk('terms', 'Acepto los términos de intercambio|I accept the exchange terms', true),
    ],
    contact: ['Giro demorado|Delayed transfer', 'Bloqueo de cuenta|Account freeze', 'Asesoramiento de inversión|Investment advice', 'Denuncia de fraude|Fraud report'],
    faq: [
      ['¿Cuánto tarda un giro entre sistemas?|How long does an inter-system transfer take?', 'Menos de una hora gracias a la red de relés propios.|Under an hour thanks to our own relay network.'],
      ['¿Está protegido mi dinero?|Is my money protected?', 'El fondo de garantía cubre depósitos hasta 50.000 por cliente.|The guarantee fund covers deposits up to 50,000 per customer.'],
      ['¿Cobran por cambiar moneda?|Do you charge for exchange?', 'Un uno por ciento, informado antes de confirmar.|One percent, disclosed before you confirm.'],
      ['¿Qué pasa con la inflación entre sistemas?|What about inter-system inflation?', 'Ofrecemos cuentas indexadas a una canasta de metales.|We offer accounts indexed to a basket of metals.'],
      ['¿Hay sucursales físicas?|Are there physical branches?', 'Tres estaciones con ventanilla humana; el resto es digital.|Three stations with human counters; the rest is digital.'],
    ],
    posts: [
      ['Cómo leer una tasa de cambio|How to read an exchange rate', 'Divisas explicadas con ejemplos de rutas.|Currencies explained with route examples.', 'Economista Bruna Hallwyn'],
      ['Fondos de colonias: qué son|Colonies funds: what they are', 'Riesgo, plazo y por qué apostar al agua.|Risk, term and why to bet on water.', 'Asesor Eliot Faro'],
      ['Ahorrar siendo piloto|Saving as a pilot', 'Un presupuesto para ingresos irregulares.|A budget for irregular income.', 'Asesora Mira Tennant'],
    ],
    wiz: {
      title: 'Simulador de crédito|Loan simulator',
      steps: [
        ['Destino|Purpose', [sel('purpose', 'Para qué es el crédito|What the loan is for', ['Comprar una nave|Buy a ship', 'Mantenimiento|Maintenance', 'Refinanciar deuda|Refinance debt'])]],
        ['Monto y plazo|Amount and term', [num('loanAmount', 'Monto solicitado|Amount requested', 500, 900000), num('loanCycles', 'Plazo en ciclos|Term in cycles', 1, 40)]],
        ['Deuda actual|Existing debt', [num('currentDebt', 'Deuda actual a refinanciar|Current debt to refinance', 100, 500000)]],
        ['Fecha|Date', [date('startPay', 'Primer pago|First payment')]],
      ],
      cond: ['purpose', 'refinance-debt', ['currentDebt']],
    },
    dash: { cols: ['Producto|Product', 'Operaciones|Transactions', 'Fecha de liquidación|Settlement date', 'Volumen|Volume'], pool: ['Cuenta de tripulación|Crew account', 'Préstamo de nave|Ship loan', 'Fondo de colonias|Colonies fund', 'Bono de agua|Water bond', 'Cambio de divisas|Currency exchange', 'Giro entre sistemas|Inter-system transfer'], n: [5, 400], m: [1000, 800000] },
  },
  {
    id: 'academia-pilotos-nova-aurora',
    name: 'Academia de Pilotos Nova Aurora|Nova Aurora Pilot Academy',
    tag: 'Despegá sabiendo cómo volver|Take off knowing how to return',
    style: [205, 40, 'sans', 4, 'tech'],
    cur: ['Ⓟ', 'PIL', 0, 'after'],
    nouns: ['curso|cursos|course|courses', 'cadete|cadetes|cadet|cadets', 'inscripción|inscripciones|enrollment|enrollments', 'licencia|licencias|license|licenses'],
    nav: ['Hangar de ingreso|Intake hangar', 'Mi plan de vuelo|My flight plan', 'Inscribirme|Enroll', 'Tablero de instructores|Instructor board', 'Bitácora de cadetes|Cadet log'],
    cats: ['Pilotaje básico|Basic piloting', 'Navegación|Navigation', 'Emergencias|Emergencies', 'Licencias avanzadas|Advanced licenses'],
    items: [
      ['Introducción al vuelo orbital|Intro to Orbital Flight', 'Cuarenta horas en simulador|Forty simulator hours', 600, 0],
      ['Maniobras de atraque|Docking Maneuvers', 'Acople suave con vientos solares|Soft docking in solar wind', 480, 0],
      ['Vuelo en formación|Formation Flying', 'Seis naves, un solo rumbo|Six ships, one heading', 700, 0],
      ['Navegación por estrellas|Star Navigation', 'Cuando falla el panel|When the panel fails', 450, 1],
      ['Cartas de salto|Jump Charts', 'Cálculos de ventanas de hiperespacio|Hyperspace window calculation', 520, 1],
      ['Plan de vuelo y combustible|Flight Plan and Fuel', 'Márgenes que salvan viajes|Margins that save voyages', 380, 1],
      ['Fallas de presurización|Pressurization Failure', 'Qué hacer en los primeros quince segundos|What to do in the first fifteen seconds', 550, 2],
      ['Incendios a bordo|Onboard Fire', 'Extintores y aislación de módulos|Extinguishers and module isolation', 500, 2],
      ['Aterrizaje sin motores|Engine-Out Landing', 'Planeo orbital con una sola oportunidad|Orbital glide with one chance', 800, 2],
      ['Licencia de carga pesada|Heavy Freight License', 'Para naves de más de 5000 toneladas|For ships over 5,000 tons', 1200, 3],
      ['Licencia de pasajeros|Passenger License', 'Incluye primeros auxilios y trato al cliente|Includes first aid and customer care', 1100, 3],
      ['Instructor de vuelo|Flight Instructor Certificate', 'Cien horas supervisadas|One hundred supervised hours', 1500, 3],
    ],
    fields: [
      text('cadetName', 'Nombre del cadete|Cadet name', { minLength: 2, maxLength: 70 }),
      num('age', 'Edad en años estándar|Age in standard years', 16, 70),
      pat('cadetId', 'Número de cadete|Cadet number', '^NA-\\d{5}$', 'NA- y cinco dígitos, ej. NA-30871|NA- and five digits, e.g. NA-30871'),
      sel('track', 'Trayectoria deseada|Desired track', ['Carga|Cargo', 'Pasajeros|Passengers', 'Exploración|Exploration']),
      num('flightHours', 'Horas de vuelo previas|Previous flight hours', 0, 20000),
      chk('medicalCert', 'Presento certificado médico apto para vuelo|I submit a flight-fit medical certificate', true),
    ],
    contact: ['Beca de formación|Training scholarship', 'Cambiar de instructor|Change instructor', 'Examen médico|Medical exam', 'Pasantías en naves|Ship internships'],
    faq: [
      ['¿Hace falta experiencia previa?|Is prior experience needed?', 'No, el primer curso parte de cero y usa simulador.|No, the first course starts from zero and uses a simulator.'],
      ['¿Cuánto dura la formación completa?|How long is the full program?', 'Dos años estándar, con prácticas reales desde el tercer trimestre.|Two standard years, with real flights from the third term.'],
      ['¿Hay límite de edad?|Is there an age limit?', 'Desde los dieciséis y sin tope, mientras apruebes el médico.|From sixteen with no cap as long as you pass the medical.'],
      ['¿Qué pasa si repruebo un examen?|What if I fail an exam?', 'Podés repetirlo una vez sin costo; la segunda tiene arancel.|You may retake it once free; the second costs a fee.'],
      ['¿Ofrecen alojamiento?|Is housing available?', 'Residencia en el anillo con habitaciones compartidas.|A ring residence with shared rooms.'],
    ],
    posts: [
      ['Primer vuelo: lo que sentí|First flight: what I felt', 'Una cadete cuenta la despedida de la Tierra.|A cadet recounts leaving Earth behind.', 'Cadete Luz Arroyo'],
      ['Por qué estudiar navegación manual|Why study manual navigation', 'Porque algún día el panel se apaga.|Because someday the panel will go dark.', 'Instructor Matías Bell'],
      ['El simulador más duro|The hardest simulator', 'Un escenario de aterrizaje sin motores.|An engine-out landing scenario.', 'Instructora Dolores Rin'],
    ],
    wiz: {
      title: 'Inscripción al curso de piloto|Pilot course enrollment',
      steps: [
        ['Experiencia|Experience', [rad('xp', 'Experiencia en vuelo|Flight experience', ['Ninguna|None', 'Con horas previas|Some prior hours'])]],
        ['Fecha y dedicación|Date and commitment', [date('startTerm', 'Inicio del curso|Course start'), num('hoursWeek', 'Horas por semana|Hours per week', 4, 60)]],
        ['Horas previas|Prior hours', [num('priorHours', 'Horas acreditadas|Logged hours', 1, 20000)]],
        ['Beca|Scholarship', [chk('scholarship', 'Solicito beca parcial|I request a partial scholarship')]],
      ],
      cond: ['xp', 'some-prior-hours', ['priorHours']],
    },
    dash: { cols: ['Curso|Course', 'Cadetes inscritos|Enrolled cadets', 'Fecha de inicio|Start date', 'Matrículas|Tuition'], pool: ['Vuelo orbital|Orbital flight', 'Atraque|Docking', 'Navegación estelar|Star navigation', 'Emergencias|Emergencies', 'Carga pesada|Heavy freight', 'Instructor|Instructor'], n: [4, 60], m: [450, 40000] },
  },
  {
    id: 'mercado-repuestos-robot-tuerca',
    name: 'Mercado de Repuestos Tuerca Feliz|Happy Bolt Spare Parts Market',
    tag: 'Si no está, lo tornamos|If we do not have it, we turn it ourselves',
    style: [25, 205, 'mono', 3, 'tech'],
    cur: ['¤', 'RBT', 2, 'after'],
    nouns: ['repuesto|repuestos|part|parts', 'técnico|técnicos|technician|technicians', 'pedido|pedidos|order|orders', 'sección|secciones|section|sections'],
    nav: ['Pasillo central|Main aisle', 'Mi caja de piezas|My parts bin', 'Pagar y retirar|Pay and collect', 'Libro de inventario|Inventory book', 'Consejos de taller|Workshop tips'],
    cats: ['Actuadores y motores|Actuators and motors', 'Sensores y ópticas|Sensors and optics', 'Baterías y energía|Batteries and power', 'Piel y carcasas|Skin and casings'],
    items: [
      ['Servo de brazo 40 kg·cm|40 kg·cm arm servo', 'Giro de 270 grados, sin holgura|270-degree turn, no backlash', 45, 0],
      ['Motor sin escobillas|Brushless motor', 'Eficiencia del 92 por ciento|92 percent efficiency', 60, 0],
      ['Articulación de cadera|Hip joint', 'Con rodamientos sellados|With sealed bearings', 140, 0],
      ['Ojo óptico gran angular|Wide-angle optical eye', 'Cámara de 12 megapíxeles con infrarrojo|12-megapixel camera with infrared', 90, 1],
      ['Sensor de proximidad láser|Laser proximity sensor', 'Alcance de seis metros|Six-meter range', 24, 1],
      ['Micrófono direccional|Directional microphone', 'Cancela el ruido de motores|Cancels motor noise', 18, 1],
      ['Batería de iones 48 V|48 V ion battery', 'Cuatro horas de autonomía completa|Four hours of full runtime', 120, 2],
      ['Cargador inalámbrico de piso|Wireless floor charger', 'Carga por contacto con alfombrilla|Contact charging through a mat', 70, 2],
      ['Celda solar plegable|Foldable solar cell', 'Ideal para robots de exterior|Ideal for outdoor robots', 85, 2],
      ['Piel de silicona gris|Gray silicone skin', 'Resistente a rayones, lavable|Scratch-resistant and washable', 35, 3],
      ['Carcasa de torso reforzada|Reinforced torso casing', 'Aleación liviana y aletas de enfriado|Light alloy with cooling fins', 160, 3],
      ['Pegatinas de expresión|Expression decals', 'Veinte emociones para tu pantalla facial|Twenty emotions for your face screen', 8, 3],
    ],
    fields: [
      text('techName', 'Nombre del técnico|Technician name', { minLength: 2, maxLength: 60 }),
      pat('partSku', 'Código de repuesto|Part code', '^RB-[A-Z]{2}\\d{4}$', 'RB-, dos letras y cuatro dígitos, ej. RB-SV0412|RB-, two letters and four digits, e.g. RB-SV0412'),
      sel('robotModel', 'Familia de robot|Robot family', ['Doméstico|Domestic', 'Industrial|Industrial', 'Educativo|Educational']),
      num('voltage', 'Voltaje de trabajo|Working voltage', 3, 240),
      num('quantity', 'Cantidad|Quantity', 1, 500),
      chk('warranty', 'Necesito garantía extendida|I need extended warranty'),
    ],
    contact: ['Repuesto defectuoso|Defective part', 'Falta de stock|Out of stock', 'Compatibilidad de piezas|Part compatibility', 'Compra por mayor|Bulk purchase'],
    faq: [
      ['¿Cómo sé si una pieza es compatible?|How do I know a part is compatible?', 'Cada ficha trae una tabla de modelos y un test de compatibilidad.|Each listing includes a model table and a compatibility check.'],
      ['¿Aceptan devoluciones?|Do you accept returns?', 'Dentro de treinta días y con la pieza sin instalar.|Within thirty days and with the part uninstalled.'],
      ['¿Hacen instalación?|Do you install?', 'Sí, en el taller trasero, previo turno.|Yes, in the back workshop, by appointment.'],
      ['¿Venden piezas usadas?|Do you sell used parts?', 'Las reacondicionamos y damos noventa días de garantía.|We refurbish them and give a ninety-day warranty.'],
      ['¿Despachan los pedidos?|Do you dispatch orders?', 'En paquete antiestático y con seguimiento.|In anti-static packaging with tracking.'],
    ],
    posts: [
      ['Cómo medir un servo|How to measure a servo', 'Torque, velocidad y calor.|Torque, speed and heat.', 'Técnica Berenice Ostos'],
      ['Piel de silicona: guía de cuidados|Silicone skin care guide', 'Qué limpiadores sí y cuáles no.|Which cleaners work and which do not.', 'Técnica Berenice Ostos'],
      ['La caja de tornillos perdida|The lost box of screws', 'Una historia de taller con final feliz.|A workshop story with a happy ending.', 'Mecánico Jairo Llanos'],
    ],
    wiz: {
      title: 'Armá tu kit de reparación|Build your repair kit',
      steps: [
        ['Tipo de reparación|Repair type', [sel('repair', 'Qué querés reparar|What you want to repair', ['Movimiento|Movement', 'Visión y sonido|Vision and sound', 'Energía|Power'])]],
        ['Cantidad y fecha|Quantity and date', [num('kitQty', 'Cantidad de kits|Number of kits', 1, 50), date('needDate', 'Necesito antes de|Needed by')]],
        ['Energía|Power', [num('wattage', 'Potencia necesaria en vatios|Power required in watts', 5, 5000)]],
        ['Instalación|Installation', [chk('install', 'Quiero que lo instalen|I want it installed')]],
      ],
      cond: ['repair', 'power', ['wattage']],
    },
    dash: { cols: ['Repuesto|Part', 'Unidades vendidas|Units sold', 'Fecha de venta|Sale date', 'Ingresos|Income'], pool: ['Servo de brazo|Arm servo', 'Motor sin escobillas|Brushless motor', 'Ojo óptico|Optical eye', 'Batería de iones|Ion battery', 'Piel de silicona|Silicone skin', 'Celda solar|Solar cell'], n: [3, 120], m: [60, 7200] },
  },
  {
    id: 'laboratorio-terraformacion-semilla-azul',
    name: 'Laboratorio de Terraformación Semilla Azul|Blue Seed Terraforming Lab',
    tag: 'Convertimos rocas en jardines, con permiso del viento|We turn rocks into gardens, wind permitting',
    style: [160, 80, 'sans', 8, 'tech'],
    cur: ['◎', 'TFM', 0, 'after'],
    nouns: ['proyecto|proyectos|project|projects', 'investigador|investigadores|researcher|researchers', 'solicitud|solicitudes|request|requests', 'bioma|biomas|biome|biomes'],
    nav: ['Atrio del laboratorio|Lab atrium', 'Mis muestras|My samples', 'Pedir análisis|Request analysis', 'Panel de campo|Field panel', 'Informes de campo|Field reports'],
    cats: ['Atmósfera|Atmosphere', 'Suelo y agua|Soil and water', 'Vida microbiana|Microbial life', 'Monitoreo|Monitoring'],
    items: [
      ['Análisis de atmósfera|Atmosphere analysis', 'Composición gaseosa y presión|Gas composition and pressure', 120, 0],
      ['Plan de generación de oxígeno|Oxygen generation plan', 'Con algas y electrólisis|With algae and electrolysis', 800, 0],
      ['Simulación de efecto invernadero|Greenhouse effect simulation', 'Modelo a cien años en tres escenarios|A hundred-year model in three scenarios', 450, 0],
      ['Estudio de permafrost|Permafrost study', 'Perforación hasta ocho metros|Drilling to eight meters', 360, 1],
      ['Mapa de napas de agua|Aquifer map', 'Radar de penetración y sondeo|Penetrating radar and test borings', 520, 1],
      ['Mejora de suelo con líquenes|Lichen soil improvement', 'Siembra por parcelas de prueba|Seeding in test plots', 280, 1],
      ['Cultivo de bacterias fijadoras|Nitrogen-fixing bacteria culture', 'Cepas adaptadas al frío|Cold-adapted strains', 190, 2],
      ['Banco de semillas resistentes|Hardy seed bank', 'Doscientas variedades catalogadas|Two hundred catalogued varieties', 340, 2],
      ['Prueba de invernadero cerrado|Closed greenhouse trial', 'Ciclo de cuarenta días|Forty-day cycle', 410, 2],
      ['Estación meteorológica local|Local weather station', 'Datos cada cinco minutos|Data every five minutes', 150, 3],
      ['Satélite de observación|Observation satellite', 'Resolución de un metro por píxel|One-meter-per-pixel resolution', 2200, 3],
      ['Informe anual de avance|Annual progress report', 'Con gráficos y recomendaciones|With charts and recommendations', 90, 3],
    ],
    fields: [
      text('researcherName', 'Nombre del investigador|Researcher name', { minLength: 3, maxLength: 70 }),
      pat('grantCode', 'Código de financiamiento|Grant code', '^TF-\\d{4}-[A-Z]$', 'TF-, cuatro dígitos, guion y una letra, ej. TF-2041-B|TF-, four digits, a dash and a letter, e.g. TF-2041-B'),
      sel('targetBody', 'Cuerpo a transformar|Target body', ['Planeta rocoso|Rocky planet', 'Luna helada|Icy moon', 'Asteroide grande|Large asteroid']),
      num('areaKm2', 'Superficie del proyecto en km²|Project area in km²', 1, 100000),
      num('timelineYears', 'Duración prevista en años|Planned duration in years', 1, 500),
      area('hypothesis', 'Hipótesis principal|Main hypothesis', 250),
    ],
    contact: ['Solicitar financiamiento|Request funding', 'Colaboración científica|Scientific collaboration', 'Resultado inesperado|Unexpected result', 'Revisión ética|Ethics review'],
    faq: [
      ['¿Cuánto tarda terraformar un planeta?|How long does it take to terraform a planet?', 'Siglos. Nosotros medimos fases de diez años.|Centuries. We measure in ten-year phases.'],
      ['¿Es ético modificar un mundo?|Is it ethical to modify a world?', 'Todo proyecto pasa por un comité y descarta mundos con vida propia.|Every project passes a committee that rules out worlds with native life.'],
      ['¿Quién financia?|Who funds this?', 'Consorcios de colonias, gobiernos y fondos comunitarios.|Colony consortia, governments and community funds.'],
      ['¿Puedo visitar el laboratorio?|Can I visit the lab?', 'Un sábado al mes, con guía y mascarilla.|One Saturday a month, with a guide and a mask.'],
      ['¿Publican sus datos?|Do you publish your data?', 'Todos los datos son abiertos tras seis meses de revisión.|All data is open after six months of review.'],
    ],
    posts: [
      ['Líquenes: los primeros jardineros|Lichens: the first gardeners', 'Cómo preparan el suelo para el resto.|How they prepare the soil for the rest.', 'Dra. Orquídea Venn'],
      ['Un día en el campo helado|A day in the frozen field', 'Muestreo a 40 grados bajo cero.|Sampling at 40 below zero.', 'Técnico Iker Sandoval'],
      ['Mitos sobre terraformar|Terraforming myths', 'Cinco cosas que no son como las películas.|Five things that differ from the movies.', 'Dra. Orquídea Venn'],
    ],
    wiz: {
      title: 'Propuesta de proyecto|Project proposal',
      steps: [
        ['Objetivo|Goal', [sel('aim', 'Objetivo principal|Main goal', ['Atmósfera respirable|Breathable atmosphere', 'Suelo fértil|Fertile soil', 'Agua líquida|Liquid water'])]],
        ['Plazo y presupuesto|Timeline and budget', [date('proposalStart', 'Inicio propuesto|Proposed start'), num('proposalBudget', 'Presupuesto en millones|Budget in millions', 1, 5000)]],
        ['Agua|Water', [num('waterTons', 'Toneladas de agua a movilizar|Tons of water to move', 1, 100000)]],
        ['Equipo|Team', [text('lead', 'Investigador responsable|Lead researcher', { minLength: 3, maxLength: 70 })]],
      ],
      cond: ['aim', 'liquid-water', ['waterTons']],
    },
    dash: { cols: ['Proyecto|Project', 'Muestras analizadas|Samples analyzed', 'Fecha de informe|Report date', 'Presupuesto ejecutado|Budget spent'], pool: ['Atmósfera|Atmosphere', 'Permafrost|Permafrost', 'Líquenes|Lichens', 'Banco de semillas|Seed bank', 'Invernadero cerrado|Closed greenhouse', 'Estación meteorológica|Weather station'], n: [5, 800], m: [100, 50000] },
  },
  {
    id: 'archivo-datos-cuanticos-memoria-azul',
    name: 'Archivo de Datos Cuánticos Memoria Azul|Blue Memory Quantum Data Archive',
    tag: 'Guardamos lo que fue y lo que pudo haber sido|We store what was and what might have been',
    style: [235, 180, 'mono', 4, 'tech'],
    cur: ['⌬', 'QBT', 0, 'after'],
    nouns: ['registro|registros|record|records', 'consultante|consultantes|researcher|researchers', 'consulta|consultas|query|queries', 'archivo|archivos|archive|archives'],
    nav: ['Vestíbulo de datos|Data lobby', 'Mis consultas|My queries', 'Autorizar acceso|Authorize access', 'Panel del archivista|Archivist panel', 'Boletín de descubrimientos|Discovery bulletin'],
    cats: ['Historia de las colonias|Colony history', 'Datos científicos|Scientific data', 'Registros personales|Personal records', 'Cultura y arte|Culture and art'],
    items: [
      ['Crónicas de la primera colonia|Chronicles of the First Colony', 'Diarios y partes de guardia, digitalizados|Diaries and watch logs, digitized', 25, 0],
      ['Archivo de naufragios espaciales|Space Shipwreck Archive', 'Con coordenadas y listas de pasajeros|With coordinates and passenger lists', 40, 0],
      ['Actas de la primera asamblea|First Assembly Minutes', 'Debates sin editar, doce horas de audio|Unedited debates, twelve hours of audio', 18, 0],
      ['Catálogo de estrellas variables|Variable Star Catalog', 'Veinte mil entradas con curvas de luz|Twenty thousand entries with light curves', 60, 1],
      ['Datos de clima planetario|Planetary Climate Data', 'Series de cuarenta años por planeta|Forty-year series per planet', 55, 1],
      ['Secuenciaciones de especies nuevas|New Species Sequencing', 'Genomas ordenados por cuerpo celeste|Genomes sorted by celestial body', 120, 1],
      ['Cartas familiares de la diáspora|Diaspora Family Letters', 'Mensajes entre mundos separados|Messages between separated worlds', 12, 2],
      ['Registro de nacimientos orbitales|Orbital Birth Registry', 'Con árboles genealógicos interactivos|With interactive family trees', 20, 2],
      ['Historias orales de pioneros|Pioneer Oral Histories', 'Entrevistas en veintidós idiomas|Interviews in twenty-two languages', 30, 2],
      ['Pinturas de la era del hielo|Ice Age Paintings', 'Murales digitalizados con luz polarizada|Murals digitized with polarized light', 35, 3],
      ['Partituras de la nave dormida|Sleeping Ship Scores', 'Música compuesta durante el viaje|Music composed during the voyage', 15, 3],
      ['Poesía de las estaciones|Station Poetry', 'Antología de versos escritos en turnos nocturnos|Anthology of verses written on night shifts', 10, 3],
    ],
    fields: [
      text('seekerName', 'Nombre del consultante|Researcher name', { minLength: 2, maxLength: 70 }),
      pat('accessKey', 'Clave de acceso al archivo|Archive access key', '^QA-[A-F0-9]{8}$', 'QA- y ocho caracteres hexadecimales, ej. QA-9F3C10AB|QA- and eight hex characters, e.g. QA-9F3C10AB'),
      sel('purpose', 'Propósito de la consulta|Query purpose', ['Investigación|Research', 'Genealogía|Genealogy', 'Divulgación|Outreach', 'Educación|Education']),
      num('dataVolumeGb', 'Volumen estimado en GB|Estimated volume in GB', 1, 100000),
      chk('citation', 'Me comprometo a citar la fuente|I commit to citing the source', true),
      area('topic', 'Tema o pregunta de investigación|Research topic or question', 250),
    ],
    contact: ['Dato corrupto|Corrupted data', 'Solicitud de eliminación|Deletion request', 'Acceso a registros privados|Access to private records', 'Donar un archivo|Donate an archive'],
    faq: [
      ['¿Qué tan segura está la información?|How safe is the data?', 'Cuatro copias en cuatro estaciones, con verificación cada siete ciclos.|Four copies in four stations, verified every seven cycles.'],
      ['¿Puedo borrar mis datos personales?|Can I erase my personal data?', 'Sí, mediante solicitud verificada con tu identificación.|Yes, via a verified request with your ID.'],
      ['¿Cuánto cuesta consultar?|What does a query cost?', 'Gratis para estudiantes; arancel simbólico para empresas.|Free for students; a symbolic fee for companies.'],
      ['¿Qué formatos ofrecen?|Which formats do you offer?', 'Texto plano, imágenes abiertas y paquetes comprimidos.|Plain text, open images and compressed bundles.'],
      ['¿Cómo se verifica un registro antiguo?|How is an old record verified?', 'Con sellos temporales y firmas del archivo original.|With timestamps and signatures from the original archive.'],
    ],
    posts: [
      ['Genealogía entre mundos|Genealogy between worlds', 'Cómo reconstruir un árbol en tres sistemas.|How to rebuild a tree across three systems.', 'Archivista Luz Verhoeven'],
      ['La carta que tardó cien años|The letter that took a hundred years', 'Un mensaje que llegó a su destinatario tataranieto.|A message that reached its great-great-grandchild recipient.', 'Archivista Luz Verhoeven'],
      ['Preservar música del espacio|Preserving music from space', 'Los desafíos de digitalizar partituras antiguas.|The challenges of digitizing old scores.', 'Músico Silvano Roe'],
    ],
    wiz: {
      title: 'Solicitar acceso a un fondo|Request access to a collection',
      steps: [
        ['Naturaleza|Nature', [rad('requester', 'Quién solicita|Who is requesting', ['Persona|Individual', 'Institución|Institution'])]],
        ['Fecha y volumen|Date and volume', [date('accessFrom', 'Acceso desde|Access from'), num('requestedGb', 'GB solicitados|GB requested', 1, 50000)]],
        ['Institución|Institution', [text('institution', 'Nombre de la institución|Institution name', { minLength: 3, maxLength: 80 })]],
        ['Justificación|Justification', [area('reason', 'Motivo de la solicitud|Reason for the request', 300)]],
      ],
      cond: ['requester', 'institution', ['institution']],
    },
    dash: { cols: ['Fondo|Collection', 'Consultas|Queries', 'Fecha de acceso|Access date', 'Aranceles|Fees'], pool: ['Crónicas coloniales|Colony chronicles', 'Catálogo estelar|Star catalog', 'Cartas de la diáspora|Diaspora letters', 'Historias orales|Oral histories', 'Poesía de estaciones|Station poetry', 'Pinturas del hielo|Ice paintings'], n: [3, 400], m: [0, 9000] },
  },
  {
    id: 'cantina-orbital-sintetica',
    name: 'Cantina Orbital Plato Sintético|Synthetic Plate Orbital Canteen',
    tag: 'Cocina de impresora con corazón de abuela|Printer cuisine with a grandmother\'s heart',
    style: [20, 190, 'rounded', 10, 'playful'],
    cur: ['₠', 'CNT', 2, 'after'],
    nouns: ['plato|platos|dish|dishes', 'comensal|comensales|diner|diners', 'pedido|pedidos|order|orders', 'menú|menús|menu|menus'],
    nav: ['Barra de la cantina|Canteen counter', 'Mi bandeja|My tray', 'Pagar y recoger|Pay and pick up', 'Panel de la cocina|Kitchen panel', 'Notas del chef robot|Robot chef notes'],
    cats: ['Entradas|Starters', 'Platos fuertes|Mains', 'Postres impresos|Printed desserts', 'Bebidas|Drinks'],
    items: [
      ['Sopa de algas crujientes|Crispy seaweed soup', 'Con topping de semillas tostadas|With toasted seed topping', 4, 0],
      ['Rollitos de proteína vegetal|Plant-protein rolls', 'Salsa agridulce de manzana|Sweet-and-sour apple sauce', 5, 0],
      ['Ensalada de cultivo vertical|Vertical-farm salad', 'Hojas cosechadas a bordo hoy|Leaves harvested on board today', 4, 0],
      ['Milanesa de soja con puré|Soy cutlet with mash', 'El plato que más extrañan los colonos|The dish colonists miss the most', 9, 1],
      ['Curry de hongos y garbanzos|Mushroom and chickpea curry', 'Picante medio, con arroz perfumado|Medium spice, with fragrant rice', 10, 1],
      ['Pasta de insecto con pesto|Insect-flour pasta with pesto', 'Rica en proteínas, sabor a nuez|High-protein with a nutty flavor', 8, 1],
      ['Helado de vainilla impresa|Printed vanilla ice cream', 'Textura perfecta, hecha capa por capa|Perfect texture, built layer by layer', 4, 2],
      ['Brownie de algarroba|Carob brownie', 'Sin cacao, sin culpa|No cocoa, no guilt', 5, 2],
      ['Flan de membrillo en 3D|3D-printed quince flan', 'Con forma de estrella a pedido|Star-shaped on request', 5, 2],
      ['Té de mate espacial|Space mate tea', 'Hecho con yerba cultivada en cúpula|Made from dome-grown herb', 2, 3],
      ['Agua con gas filtrada|Filtered sparkling water', 'Carbonatada a bordo, sin plástico|Carbonated on board, no plastic', 1, 3],
      ['Café de cebada tostada|Roasted barley coffee', 'Con espuma de avena|With oat foam', 3, 3],
    ],
    fields: [
      text('dinerName', 'Nombre del comensal|Diner name', { minLength: 2, maxLength: 50 }),
      sel('diet', 'Dieta|Diet', ['Sin restricciones|No restrictions', 'Vegetariana|Vegetarian', 'Vegana|Vegan', 'Sin gluten|Gluten-free']),
      num('portions', 'Porciones por pedido|Portions per order', 1, 20),
      pat('tableTag', 'Etiqueta de mesa|Table tag', '^M-\\d{2}[A-C]$', 'M-, dos dígitos y una letra A-C, ej. M-14B|M-, two digits and a letter A-C, e.g. M-14B', false),
      chk('allergens', 'Tengo alergias alimentarias|I have food allergies'),
    ],
    contact: ['Alergias y sustitutos|Allergies and substitutes', 'Plato frío|Cold dish', 'Evento para tripulaciones|Crew event', 'Sugerencia de menú|Menu suggestion'],
    faq: [
      ['¿Qué es "comida impresa"?|What is "printed food"?', 'Se arma capa por capa con ingredientes reales en una impresora de cocina.|It is built layer by layer from real ingredients in a kitchen printer.'],
      ['¿Hay carne?|Is there meat?', 'Cultivada en laboratorio, solo los viernes.|Lab-grown, only on Fridays.'],
      ['¿Cuánto tardan los pedidos?|How long do orders take?', 'Entre cuatro y diez minutos, según la impresora disponible.|Four to ten minutes depending on printer availability.'],
      ['¿Puedo pedir un menú personalizado?|Can I request a custom menu?', 'Sí, cargando tus preferencias en la cuenta.|Yes, by loading your preferences into your account.'],
      ['¿Aceptan vales de tripulación?|Do you take crew vouchers?', 'Sí, de cualquier empresa de transporte con convenio.|Yes, from any transport company with an agreement.'],
    ],
    posts: [
      ['Cómo imprimimos un helado|How we print ice cream', 'Una cocina que parece un laboratorio.|A kitchen that looks like a laboratory.', 'Chef robot Cocotte-7'],
      ['Receta de la milanesa de soja|Soy cutlet recipe', 'Para hacer en casa sin impresora.|To make at home without a printer.', 'Chef Valeria Montero'],
      ['Alimentación en baja gravedad|Eating in low gravity', 'Por qué la sal sabe distinto allá arriba.|Why salt tastes different up there.', 'Nutricionista Íñigo Paz'],
    ],
    wiz: {
      title: 'Menú personalizado|Personalized menu',
      steps: [
        ['Dieta|Diet', [rad('dietType', 'Tipo de dieta|Diet type', ['Libre|Unrestricted', 'Con restricciones|With restrictions'])]],
        ['Comidas y fecha|Meals and date', [num('mealsPerDay', 'Comidas por día|Meals per day', 1, 6), date('startMenu', 'Inicio del menú|Menu start')]],
        ['Restricciones|Restrictions', [area('restrictions', 'Qué alimentos debemos evitar|Foods to avoid', 250)]],
        ['Extras|Extras', [chk('dessert', 'Incluir postre impreso|Include a printed dessert')]],
      ],
      cond: ['dietType', 'with-restrictions', ['restrictions']],
    },
    dash: { cols: ['Plato|Dish', 'Raciones impresas|Portions printed', 'Fecha|Date', 'Recaudación|Takings'], pool: ['Milanesa de soja|Soy cutlet', 'Curry de hongos|Mushroom curry', 'Sopa de algas|Seaweed soup', 'Helado impreso|Printed ice cream', 'Té de mate|Mate tea', 'Brownie de algarroba|Carob brownie'], n: [10, 320], m: [20, 1600] },
  },
  {
    id: 'agencia-traduccion-voz-comun',
    name: 'Agencia de Traducción Interespecie Voz Común|Common Voice Interspecies Translation Agency',
    tag: 'Entre dos lenguas, un puente; entre dos mundos, un diccionario|Between two tongues, a bridge; between two worlds, a dictionary',
    style: [275, 55, 'sans', 6, 'clean'],
    cur: ['§', 'LNG', 2, 'after'],
    nouns: ['traducción|traducciones|translation|translations', 'cliente|clientes|client|clients', 'encargo|encargos|job|jobs', 'lengua|lenguas|language|languages'],
    nav: ['Mostrador|Front desk', 'Mis traducciones|My translations', 'Aprobar encargo|Approve job', 'Mesa de intérpretes|Interpreters desk', 'Glosario abierto|Open glossary'],
    cats: ['Documentos|Documents', 'Interpretación en vivo|Live interpretation', 'Lenguas no humanas|Non-human languages', 'Localización|Localization'],
    items: [
      ['Traducción jurada de contrato|Certified contract translation', 'Con sello de perito traductor|With sworn translator stamp', 90, 0],
      ['Manual técnico de nave|Starship technical manual', 'Revisión por ingeniero bilingüe|Reviewed by a bilingual engineer', 220, 0],
      ['Ficha médica entre especies|Cross-species medical record', 'Con glosario anatómico adaptado|With adapted anatomical glossary', 130, 0],
      ['Interpretación consecutiva|Consecutive interpretation', 'Hora de trabajo con un intérprete|One hour with one interpreter', 85, 1],
      ['Interpretación simultánea|Simultaneous interpretation', 'Pareja de intérpretes y cabina|Pair of interpreters and a booth', 260, 1],
      ['Intérprete de gestos y feromonas|Gesture and pheromone interpreter', 'Para especies que no hablan con la boca|For species that do not speak with the mouth', 190, 1],
      ['Traducción del canto de las ballenas|Whale-song translation', 'Análisis de patrones de nueve cuerdas|Nine-string pattern analysis', 400, 2],
      ['Mediación con enjambre|Hive mediation', 'Con un portavoz y dos observadores|With a spokesperson and two observers', 350, 2],
      ['Léxico de la luz|Light lexicon', 'Un idioma que se habla con destellos|A language spoken in flashes', 280, 2],
      ['Adaptación de aplicación|App localization', 'Interfaz, textos y formatos de fecha|Interface, text and date formats', 160, 3],
      ['Subtitulado de película|Film subtitling', 'Con ajuste de ritmo y juegos de palabras|With timing and wordplay adjustments', 140, 3],
      ['Doblaje de documental|Documentary dubbing', 'Selección de voces y mezcla|Voice casting and mixing', 320, 3],
    ],
    fields: [
      text('clientName', 'Nombre del cliente|Client name', { minLength: 2, maxLength: 70 }),
      sel('sourceLang', 'Lengua de origen|Source language', ['Español|Spanish', 'Inglés|English', 'Lenguaje de destellos|Flash language', 'Canto de ballena|Whale song']),
      sel('targetLang', 'Lengua de destino|Target language', ['Español|Spanish', 'Inglés|English', 'Lenguaje de destellos|Flash language', 'Canto de ballena|Whale song']),
      pat('jobRef', 'Referencia del encargo|Job reference', '^TR-\\d{4}-[A-Z]{2}$', 'TR-, cuatro dígitos, guion y dos letras, ej. TR-0275-LP|TR-, four digits, a dash and two letters, e.g. TR-0275-LP'),
      num('wordCount', 'Cantidad de palabras|Word count', 1, 500000),
      chk('certified', 'Necesito traducción certificada|I need a certified translation'),
    ],
    contact: ['Corrección de una traducción|Translation correction', 'Intérprete para evento|Interpreter for an event', 'Confidencialidad|Confidentiality', 'Unirme como traductor|Join as a translator'],
    faq: [
      ['¿Cuánto tarda una traducción?|How long does a translation take?', 'Dos mil palabras por día laborable, más un día de revisión.|Two thousand words per working day, plus one review day.'],
      ['¿Pueden traducir lenguas no humanas?|Can you translate non-human languages?', 'Con apoyo de lingüistas especializados y bancos de patrones.|With specialist linguists and pattern libraries.'],
      ['¿Qué es una traducción jurada?|What is a certified translation?', 'La firma un perito oficial y tiene validez legal.|An official expert signs it and it is legally valid.'],
      ['¿Guardan confidencialidad?|Do you keep things confidential?', 'Todos los traductores firman un acuerdo y borramos los archivos a los noventa días.|All translators sign an agreement and we delete files after ninety days.'],
      ['¿Qué pasa si hay un error?|What if there is a mistake?', 'Se corrige gratis dentro de treinta días.|It is corrected free within thirty days.'],
    ],
    posts: [
      ['Dos palabras que no se traducen|Two words that will not translate', 'Una familia de expresiones que nadie logra pasar al inglés.|A family of expressions nobody manages to carry into English.', 'Traductora Elisa Kowal'],
      ['Cómo interpretar un enjambre|How to interpret a hive', 'El intérprete como mediador de coros.|The interpreter as mediator of choruses.', 'Intérprete Ramón Okafor'],
      ['Localizar con humor|Localizing humor', 'Cuándo hay que reescribir un chiste.|When a joke has to be rewritten.', 'Traductora Elisa Kowal'],
    ],
    wiz: {
      title: 'Pedir presupuesto de traducción|Request a translation quote',
      steps: [
        ['Tipo de material|Material type', [sel('materialKind', 'Tipo de material|Material type', ['Documento escrito|Written document', 'Audio o video|Audio or video', 'Evento en vivo|Live event'])]],
        ['Volumen y fecha|Volume and deadline', [num('pages', 'Páginas o minutos|Pages or minutes', 1, 3000), date('dueDate', 'Fecha de entrega|Due date')]],
        ['Evento|Event', [num('attendees', 'Asistentes estimados|Estimated attendees', 2, 5000)]],
        ['Notas|Notes', [area('briefing', 'Contexto del texto o evento|Context of the text or event', 300)]],
      ],
      cond: ['materialKind', 'live-event', ['attendees']],
    },
    dash: { cols: ['Servicio|Service', 'Encargos|Jobs', 'Fecha de entrega|Delivery date', 'Facturado|Billed'], pool: ['Traducción jurada|Certified translation', 'Interpretación simultánea|Simultaneous interpretation', 'Léxico de la luz|Light lexicon', 'Mediación con enjambre|Hive mediation', 'Subtitulado|Subtitling', 'Doblaje|Dubbing'], n: [1, 40], m: [85, 8000] },
  },
  {
    id: 'seguro-hiperespacio-salto-seguro',
    name: 'Seguros Salto Seguro|Safe Jump Insurance',
    tag: 'Para el viaje que sale bien y para el otro|For the trip that goes well and the one that does not',
    style: [200, 350, 'sans', 8, 'clean'],
    cur: ['⍟', 'SGR', 2, 'after'],
    nouns: ['póliza|pólizas|policy|policies', 'asegurado|asegurados|policyholder|policyholders', 'siniestro|siniestros|claim|claims', 'cobertura|coberturas|coverage|coverages'],
    nav: ['Oficina de pólizas|Policy office', 'Mi cobertura|My coverage', 'Contratar póliza|Buy a policy', 'Panel de peritos|Adjusters panel', 'Boletín de riesgos|Risk bulletin'],
    cats: ['Naves y cascos|Ships and hulls', 'Carga y mercancías|Cargo and goods', 'Personas y tripulación|People and crew', 'Responsabilidad civil|Civil liability'],
    items: [
      ['Casco todo riesgo|All-risk hull', 'Cubre colisión, fuego y fallas de motor|Covers collision, fire and engine failure', 4800, 0],
      ['Casco básico|Basic hull', 'Solo colisión y daños por meteoros|Collision and meteor damage only', 1900, 0],
      ['Motor y propulsión|Engine and propulsion', 'Para reactores y propulsores iónicos|For reactors and ion thrusters', 2600, 0],
      ['Carga general|General cargo', 'Hasta 500 toneladas por viaje|Up to 500 tons per voyage', 1500, 1],
      ['Carga frágil|Fragile cargo', 'Instrumentos, obras y cristales|Instruments, artwork and crystals', 2200, 1],
      ['Carga viva|Live cargo', 'Plantas, animales y cultivos|Plants, animals and cultures', 3100, 1],
      ['Accidentes de tripulación|Crew accident', 'Hospitalización y repatriación|Hospitalization and repatriation', 780, 2],
      ['Vida y secuelas|Life and disability', 'Pago único a los beneficiarios|One-time payout to beneficiaries', 1200, 2],
      ['Pérdida de equipaje personal|Personal luggage loss', 'Hasta 3000 unidades por viaje|Up to 3,000 units per trip', 90, 2],
      ['Daños a terceros en puerto|Third-party port damage', 'Colisión en muelle y contaminación|Dock collision and contamination', 1800, 3],
      ['Responsabilidad ambiental|Environmental liability', 'Derrames y residuos en órbita|Spills and orbital debris', 2400, 3],
      ['Defensa legal en tribunales aliados|Legal defense in allied courts', 'Con abogados en tres sistemas|With lawyers in three systems', 950, 3],
    ],
    fields: [
      text('holderName', 'Nombre del asegurado|Policyholder name', { minLength: 3, maxLength: 70 }),
      pat('policyNumber', 'Número de póliza vigente|Current policy number', '^SS-\\d{7}$', 'SS- y siete dígitos, ej. SS-4082915|SS- and seven digits, e.g. SS-4082915', false),
      sel('assetType', 'Qué querés asegurar|What to insure', ['Nave|Ship', 'Carga|Cargo', 'Tripulación|Crew']),
      num('assetValue', 'Valor declarado|Declared value', 100, 50000000),
      num('jumpsPerYear', 'Saltos por año|Jumps per year', 1, 400),
      chk('priorClaims', 'Tuve siniestros en los últimos cinco años|I had claims in the last five years'),
    ],
    contact: ['Denunciar un siniestro|Report a claim', 'Disputar un pago|Dispute a payout', 'Renovar póliza|Renew policy', 'Peritaje de nave|Ship inspection'],
    faq: [
      ['¿Cómo se denuncia un siniestro?|How do I file a claim?', 'Desde el panel, con la bitácora de la nave y fotos del daño.|From the panel, with the ship log and photos of the damage.'],
      ['¿Cuánto tardan en pagar?|How long until payout?', 'Treinta días tras el peritaje, o quince si hay baliza de emergencia.|Thirty days after inspection, or fifteen with an emergency beacon.'],
      ['¿Cubren fenómenos del hiperespacio?|Do you cover hyperspace phenomena?', 'Sí, en pólizas todo riesgo; en las básicas, no.|Yes, on all-risk policies; not on basic ones.'],
      ['¿Hay descuento por buena conducta?|Is there a no-claims discount?', 'Hasta un treinta por ciento tras cinco ciclos sin siniestros.|Up to thirty percent after five claim-free cycles.'],
      ['¿Aseguran naves viejas?|Do you insure old ships?', 'Hasta cuarenta ciclos de antigüedad con inspección previa.|Up to forty cycles old with a prior inspection.'],
    ],
    posts: [
      ['Qué cubre un seguro todo riesgo|What all-risk really covers', 'Una lectura de la letra chica sin dolor.|A painless reading of the fine print.', 'Perito Valentín Orsay'],
      ['Siniestros más comunes del año|The year\'s most common claims', 'Colisiones en muelle, meteoritos y cafés derramados.|Dock collisions, meteors and spilled coffee.', 'Perita Greta Ludlow'],
      ['Cómo preparar tu nave para el peritaje|Preparing your ship for inspection', 'Una lista de verificación de dos páginas.|A two-page checklist.', 'Perito Valentín Orsay'],
    ],
    wiz: {
      title: 'Contratar tu póliza|Buy your policy',
      steps: [
        ['Qué asegurás|What you insure', [sel('insured', 'Bien a asegurar|Asset to insure', ['Nave|Ship', 'Carga|Cargo'])]],
        ['Valor y vigencia|Value and term', [num('sumInsured', 'Suma asegurada|Sum insured', 500, 20000000), date('coverFrom', 'Vigencia desde|Coverage start')]],
        ['Nave|Ship', [pat('hullId', 'Matrícula de la nave|Ship registration', '^[A-Z]{2}-\\d{4}$', 'Dos letras, guion y cuatro dígitos, ej. AX-2087|Two letters, a dash and four digits, e.g. AX-2087')]],
        ['Aceptación|Acceptance', [chk('read', 'Leí las condiciones generales|I read the general conditions', true)]],
      ],
      cond: ['insured', 'ship', ['hullId']],
    },
    dash: { cols: ['Cobertura|Coverage', 'Siniestros|Claims', 'Fecha del siniestro|Claim date', 'Indemnizaciones|Payouts'], pool: ['Casco todo riesgo|All-risk hull', 'Motor y propulsión|Engine and propulsion', 'Carga frágil|Fragile cargo', 'Accidentes de tripulación|Crew accident', 'Daños en puerto|Port damage', 'Responsabilidad ambiental|Environmental liability'], n: [0, 20], m: [500, 600000] },
  },
  {
    id: 'hotel-capsulas-nebulosa-coral',
    name: 'Hotel de Cápsulas Nebulosa Coral|Coral Nebula Capsule Hotel',
    tag: 'Dormí junto a las estrellas, sin rincones oscuros|Sleep beside the stars, no dark corners',
    style: [320, 190, 'rounded', 12, 'tech'],
    cur: ['◈', 'NBC', 2, 'after'],
    nouns: ['cápsula|cápsulas|capsule|capsules', 'huésped|huéspedes|guest|guests', 'estadía|estadías|stay|stays', 'piso|pisos|level|levels'],
    nav: ['Lobby orbital|Orbital lobby', 'Mi cápsula|My capsule', 'Reservar cápsula|Book a capsule', 'Panel de operaciones|Operations panel', 'Noches de la nebulosa|Nebula nights'],
    cats: ['Cápsulas|Capsules', 'Servicios|Services', 'Experiencias|Experiences', 'Eventos|Events'],
    items: [
      ['Cápsula simple|Single capsule', 'Cama de 90 cm y luz regulable|90 cm bed and dimmable light', 25, 0],
      ['Cápsula doble|Double capsule', 'Cama de 140 cm y escotilla panorámica|140 cm bed and panoramic hatch', 42, 0],
      ['Cápsula familiar|Family capsule', 'Dos literas y mini baño|Two bunks and a mini bathroom', 70, 0],
      ['Lavandería a vapor|Steam laundry', 'Lavado y secado en una hora|Wash and dry in one hour', 8, 1],
      ['Cena en el mirador|Observation dinner', 'Menú del chef con vista a la nebulosa|Chef\'s menu overlooking the nebula', 28, 1],
      ['Despertador personalizado|Custom wake-up call', 'Con tu música favorita|With your favorite music', 2, 1],
      ['Paseo espacial guiado|Guided spacewalk', 'Con traje y cuerda de seguridad|With suit and safety tether', 180, 2],
      ['Noche de astronomía|Astronomy night', 'Telescopios y chocolate caliente|Telescopes and hot chocolate', 22, 2],
      ['Sesión de relajación en gravedad cero|Zero-g relaxation session', 'Flotar con música y aroma de lavanda|Floating with music and lavender scent', 35, 2],
      ['Sala de reuniones|Meeting room', 'Capacidad para ocho, con pantalla|Seats eight, with a screen', 60, 3],
      ['Cena privada|Private dinner', 'Mesa para seis con servicio dedicado|Table for six with dedicated service', 150, 3],
      ['Salón de fiestas orbital|Orbital party hall', 'Pista de baile en gravedad ligera|Dance floor in light gravity', 400, 3],
    ],
    fields: [
      text('guestName', 'Nombre del huésped|Guest name', { minLength: 2, maxLength: 60 }),
      date('checkIn', 'Fecha de llegada|Check-in date'),
      num('nights', 'Noches|Nights', 1, 30),
      pat('capsuleId', 'Preferencia de cápsula|Capsule preference', '^C-[1-9]\\d{0,2}$', 'C- y un número del 1 al 999, ej. C-42|C- and a number from 1 to 999, e.g. C-42', false),
      sel('sleepType', 'Tipo de descanso|Sleep type', ['Sueño profundo|Deep sleep', 'Siestas cortas|Short naps', 'Trabajo en la cápsula|Working in the capsule']),
      chk('gravity', 'Pido nivel de gravedad terrestre|I request Earth-level gravity'),
    ],
    contact: ['Ruido en un piso vecino|Noise from a neighboring level', 'Objeto olvidado|Lost item', 'Reserva de un evento|Event booking', 'Facturación|Billing'],
    faq: [
      ['¿Qué tan grandes son las cápsulas?|How big are the capsules?', 'Entre 3 y 8 metros cuadrados, con ventilación individual.|Between 3 and 8 square meters with individual ventilation.'],
      ['¿Se puede fumar?|Is smoking allowed?', 'No, en ninguna parte de la estación: la atmósfera es compartida.|No, anywhere on the station: the atmosphere is shared.'],
      ['¿Qué pasa con el equipaje?|What about luggage?', 'Cada huésped tiene un casillero con huella digital.|Each guest has a fingerprint locker.'],
      ['¿Cómo llego desde el muelle?|How do I get from the dock?', 'Por una cinta transportadora de siete minutos.|By a seven-minute moving walkway.'],
      ['¿Se admiten niños?|Are children welcome?', 'Sí, en cápsulas familiares y con pulsera de ubicación.|Yes, in family capsules with a location wristband.'],
    ],
    posts: [
      ['Dormir flotando|Sleeping while floating', 'Consejos de huéspedes que no volverían a una cama normal.|Tips from guests who would not go back to a normal bed.', 'Conserje Aurelio Quint'],
      ['Los atardeceres de la nebulosa|The nebula\'s sunsets', 'Cuándo y desde qué cápsula verlos.|When and from which capsule to see them.', 'Conserje Aurelio Quint'],
      ['Un fin de semana sin gravedad|A weekend without gravity', 'Bitácora de una pareja que se reencontró.|A log of a couple who found each other again.', 'Huéspedes Rivas-Naoki'],
    ],
    wiz: {
      title: 'Planificá tu estadía|Plan your stay',
      steps: [
        ['Motivo|Purpose', [rad('visit', 'Motivo de la visita|Purpose of the visit', ['Descanso|Rest', 'Evento o reunión|Event or meeting'])]],
        ['Fechas y huéspedes|Dates and guests', [date('arrive', 'Fecha de llegada|Arrival date'), num('guestCount', 'Cantidad de huéspedes|Number of guests', 1, 60)]],
        ['Evento|Event', [text('eventName', 'Nombre del evento|Event name', { minLength: 3, maxLength: 80 })]],
        ['Extras|Extras', [chk('spacewalk', 'Sumar un paseo espacial|Add a spacewalk')]],
      ],
      cond: ['visit', 'event-or-meeting', ['eventName']],
    },
    dash: { cols: ['Cápsula|Capsule', 'Noches ocupadas|Nights occupied', 'Fecha de llegada|Arrival date', 'Ingresos|Income'], pool: ['Cápsula simple|Single capsule', 'Cápsula doble|Double capsule', 'Cápsula familiar|Family capsule', 'Paseo espacial|Spacewalk', 'Noche de astronomía|Astronomy night', 'Sala de reuniones|Meeting room'], n: [1, 28], m: [25, 3000] },
  },
]

export const scifi = specs.map((s) => defineTheme('scifi', s))
